package templates

import (
	"time"

	"github.com/dave/jennifer/jen"
)

// SkeletonSubcommand describes a top-level command that must be registered in
// the generated NewCmdRoot function.
type SkeletonSubcommand struct {
	ImportPath  string // e.g. "github.com/org/repo/pkg/cmd/serve"
	PkgAlias    string // e.g. "serve"
	Constructor string // e.g. "NewCmdServe"
}

type SkeletonRootData struct {
	Name                  string
	Description           string
	ReleaseProvider       string
	Host                  string
	Org                   string
	RepoName              string
	Private               bool
	DisabledFeatures      []string
	EnabledFeatures       []string
	HelpType              string // "slack", "teams", or ""
	SlackChannel          string
	SlackTeam             string
	TeamsChannel          string
	TeamsTeam             string
	TelemetryEndpoint     string
	TelemetryOTelEndpoint string
	EnvPrefix             string
	// UpdatePolicy wires props.Tool.UpdatePolicy in the generated root. Empty
	// (or "disabled") leaves the field off so the framework default applies;
	// "prompt"/"enabled" emit the matching props.UpdatePolicy* constant.
	UpdatePolicy string
	// UpdateCheckInterval wires props.Tool.UpdateCheckInterval as a Go duration
	// string (e.g. "24h"). Empty, unparseable, or non-positive values leave the
	// field off so the framework default (24h) applies.
	UpdateCheckInterval string
	// SigningEnabled gates the Signing: props.SigningConfig{...} block.
	// When true the generated tool wires trustkeys.Keys() as its embedded
	// trust anchor; ModulePath supplies the import path for that package.
	SigningEnabled bool
	ModulePath     string
	// AutoInitialise wires props.Tool.Bootstrap.AutoInitialise. When true the
	// generated tool auto-runs a non-interactive init if config is missing.
	AutoInitialise bool
	// SkipConfigCheck wires props.Tool.Bootstrap.SkipConfigCheck — commands
	// (by Name() or full CommandPath()) whose missing-config gate is relaxed.
	SkipConfigCheck []string
	Subcommands     []SkeletonSubcommand
}

func SkeletonRoot(data SkeletonRootData) *jen.File {
	f := jen.NewFile("root")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	f.Comment("//go:embed assets/*")
	f.Var().Id("assets").Qual("embed", "FS")

	// When telemetry is configured, emit the otelAuth var and init() override.
	if data.TelemetryEndpoint != "" || data.TelemetryOTelEndpoint != "" {
		f.Comment("otelAuth is injected at compile time via ldflags.")
		f.Comment("Falls back to OTEL_API_KEY env var for local development.")
		f.Comment("")
		f.Comment("nolint:gochecknoglobals // compile-time injection requires package-level var")
		f.Var().Id("otelAuth").String()

		f.Func().Id("init").Params().Block(
			jen.If(
				jen.Id("v").Op(":=").Qual("os", "Getenv").Call(jen.Lit("OTEL_API_KEY")),
				jen.Id("v").Op("!=").Lit(""),
			).Block(
				jen.Id("otelAuth").Op("=").Id("v"),
			),
		)
	}

	f.ImportAlias("gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root", "gtbRoot")

	pErrorHandler := jen.Id("p").Dot("ErrorHandler").Op("=").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/errorhandling", "New").Call(
		jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/logger", "ToSlog").Call(jen.Id("l")),
		jen.Id("p").Dot("Tool").Dot("Help"),
	)

	subCmdArgs := make([]jen.Code, 0, 1+len(data.Subcommands))
	subCmdArgs = append(subCmdArgs, jen.Id("p"))

	for _, sub := range data.Subcommands {
		f.ImportAlias(sub.ImportPath, sub.PkgAlias)
		subCmdArgs = append(subCmdArgs, jen.Qual(sub.ImportPath, sub.Constructor).Call(jen.Id("p")))
	}

	rootCmdInit := jen.Id("rootCmd").Op(":=").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root", "NewCmdRoot").Call(
		subCmdArgs...,
	)

	toolDict := buildToolDict(data)

	f.Func().Id("NewCmdRoot").Params(
		jen.Id("v").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/version", "Info"),
	).Params(
		jen.Op("*").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/setup", "Command"),
		jen.Op("*").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "Props"),
	).Block(
		jen.Id("l").Op(":=").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/logger", "NewCharm").Call(
			jen.Qual("os", "Stderr"),
			jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/logger", "WithTimestamp").Call(jen.True()),
			jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/logger", "WithLevel").Call(
				jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/logger", "InfoLevel"),
			),
		),
		jen.Line(),
		jen.Id("p").Op(":=").Op("&").Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "Props").Values(jen.Dict{
			jen.Id("Tool"):    jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "Tool").Values(toolDict),
			jen.Id("Logger"):  jen.Id("l"),
			jen.Id("Assets"):  jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "NewAssets").Call(jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "AssetMap").Values(jen.Dict{jen.Lit("root"): jen.Op("&").Id("assets")})),
			jen.Id("FS"):      jen.Qual("github.com/spf13/afero", "NewOsFs").Call(),
			jen.Id("Version"): jen.Id("v"),
		}),
		jen.Line(),
		pErrorHandler,
		jen.Line(),
		rootCmdInit,
		jen.Line(),
		jen.Return(jen.Id("rootCmd"), jen.Id("p")),
	)

	return f
}

func buildToolDict(data SkeletonRootData) jen.Dict {
	toolDict := jen.Dict{
		jen.Id("Name"):          jen.Lit(data.Name),
		jen.Id("Summary"):       jen.Lit(data.Name + " utility"),
		jen.Id("Description"):   jen.Lit(data.Description),
		jen.Id("ReleaseSource"): jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "ReleaseSource").Values(buildReleaseSourceDict(data)),
	}

	if data.EnvPrefix != "" {
		toolDict[jen.Id("EnvPrefix")] = jen.Lit(data.EnvPrefix)
	}

	// Wire a non-default update policy. "disabled" is the framework default, so
	// only "prompt"/"enabled" emit a field (keeps the generated Tool minimal).
	if c := updatePolicyConst(data.UpdatePolicy); c != "" {
		toolDict[jen.Id("UpdatePolicy")] = jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", c)
	}

	// Wire a non-default check interval. Empty/zero means "framework default"
	// (24h), so only a positive duration emits a field.
	if code, ok := updateCheckIntervalCode(data.UpdateCheckInterval); ok {
		toolDict[jen.Id("UpdateCheckInterval")] = code
	}

	switch data.HelpType {
	case "slack":
		toolDict[jen.Id("Help")] = jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/errorhandling", "SlackHelp").Values(jen.Dict{
			jen.Id("Channel"): jen.Lit(data.SlackChannel),
			jen.Id("Team"):    jen.Lit(data.SlackTeam),
		})
	case "teams":
		toolDict[jen.Id("Help")] = jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/errorhandling", "TeamsHelp").Values(jen.Dict{
			jen.Id("Channel"): jen.Lit(data.TeamsChannel),
			jen.Id("Team"):    jen.Lit(data.TeamsTeam),
		})
	}

	if len(data.DisabledFeatures) > 0 || len(data.EnabledFeatures) > 0 {
		toolDict[jen.Id("Features")] = jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "SetFeatures").Call(buildFeatures(data)...)
	}

	applyOptionalToolConfig(toolDict, data)

	return toolDict
}

// applyOptionalToolConfig adds the Telemetry and Signing entries to the
// tool dict when their manifest values are present. Extracted from
// buildToolDict to keep that function's cyclomatic complexity in check.
// updatePolicyConst maps a manifest update-policy value to the matching
// props.UpdatePolicy* constant name, or "" for the framework default
// (empty/"disabled") so no field is emitted. Validation upstream rejects any
// other value before render.
func updatePolicyConst(policy string) string {
	switch policy {
	case "prompt":
		return "UpdatePolicyPrompt"
	case "enabled":
		return "UpdatePolicyEnabled"
	default:
		return ""
	}
}

// updateCheckIntervalCode renders a Go duration string (e.g. "24h") as a
// readable time.Duration expression for the generated Tool literal — choosing
// the largest whole unit (`168 * time.Hour`, `30 * time.Minute`) and falling
// back to a raw time.Duration nanosecond literal for sub-second remainders.
// It returns ok=false for empty, unparseable, or non-positive values so the
// caller omits the field and the framework default (24h) applies. Validation
// upstream rejects malformed values before render; the parse guard here is
// defence-in-depth.
func updateCheckIntervalCode(raw string) (jen.Code, bool) {
	d, err := time.ParseDuration(raw)
	if err != nil || d <= 0 {
		return nil, false
	}

	switch {
	case d%time.Hour == 0:
		return jen.Lit(int(d/time.Hour)).Op("*").Qual("time", "Hour"), true
	case d%time.Minute == 0:
		return jen.Lit(int(d/time.Minute)).Op("*").Qual("time", "Minute"), true
	case d%time.Second == 0:
		return jen.Lit(int(d/time.Second)).Op("*").Qual("time", "Second"), true
	default:
		return jen.Qual("time", "Duration").Call(jen.Lit(int64(d))), true
	}
}

func applyOptionalToolConfig(toolDict jen.Dict, data SkeletonRootData) {
	if telemetry, ok := telemetryConfigValue(data); ok {
		toolDict[jen.Id("Telemetry")] = telemetry
	}

	// When signing is enabled, wire the embedded trust anchor from the
	// generated internal/trustkeys package. Like Telemetry, a conditional
	// dict entry driven entirely from manifest values.
	if data.SigningEnabled && data.ModulePath != "" {
		toolDict[jen.Id("Signing")] = jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "SigningConfig").Values(jen.Dict{
			jen.Id("EmbeddedKeys"): jen.Qual(data.ModulePath+"/internal/trustkeys", "Keys").Call(),
		})
	}

	// Bootstrap policy: emit a props.BootstrapPolicy{...} literal only when a
	// non-default value is set, keeping the generated Tool minimal.
	if bootstrap, ok := bootstrapPolicyValue(data); ok {
		toolDict[jen.Id("Bootstrap")] = bootstrap
	}
}

// bootstrapPolicyValue builds the props.BootstrapPolicy value from the manifest
// bootstrap settings, reporting whether any were set (so the caller omits the
// field when both are zero).
func bootstrapPolicyValue(data SkeletonRootData) (jen.Code, bool) {
	bootstrapDict := jen.Dict{}

	if data.AutoInitialise {
		bootstrapDict[jen.Id("AutoInitialise")] = jen.True()
	}

	if len(data.SkipConfigCheck) > 0 {
		entries := make([]jen.Code, 0, len(data.SkipConfigCheck))
		for _, cmd := range data.SkipConfigCheck {
			entries = append(entries, jen.Lit(cmd))
		}

		bootstrapDict[jen.Id("SkipConfigCheck")] = jen.Index().String().Values(entries...)
	}

	if len(bootstrapDict) == 0 {
		return nil, false
	}

	return jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "BootstrapPolicy").Values(bootstrapDict), true
}

// telemetryConfigValue builds the props.TelemetryConfig value from the
// manifest telemetry settings, reporting whether any were set. OTel takes
// precedence over the plain endpoint.
func telemetryConfigValue(data SkeletonRootData) (jen.Code, bool) {
	telemetryDict := jen.Dict{}

	switch {
	case data.TelemetryOTelEndpoint != "":
		telemetryDict[jen.Id("OTelEndpoint")] = jen.Lit(data.TelemetryOTelEndpoint)
		telemetryDict[jen.Id("OTelHeaders")] = jen.Map(jen.String()).String().Values(jen.Dict{
			jen.Lit("Authorization"): jen.Lit("Basic ").Op("+").Id("otelAuth"),
		})
	case data.TelemetryEndpoint != "":
		telemetryDict[jen.Id("Endpoint")] = jen.Lit(data.TelemetryEndpoint)
	default:
		return nil, false
	}

	return jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "TelemetryConfig").Values(telemetryDict), true
}

func buildReleaseSourceDict(data SkeletonRootData) jen.Dict {
	d := jen.Dict{
		jen.Id("Type"):  jen.Lit(data.ReleaseProvider),
		jen.Id("Host"):  jen.Lit(data.Host),
		jen.Id("Owner"): jen.Lit(data.Org),
		jen.Id("Repo"):  jen.Lit(data.RepoName),
	}

	if data.Private {
		d[jen.Id("Private")] = jen.True()
	}

	return d
}

func buildFeatures(data SkeletonRootData) []jen.Code {
	items := []jen.Code{}

	for _, f := range data.DisabledFeatures {
		if cmd := getFeatureCmd(f); cmd != nil {
			items = append(items, jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "Disable").Call(cmd))
		}
	}

	for _, f := range data.EnabledFeatures {
		if cmd := getFeatureCmd(f); cmd != nil {
			items = append(items, jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", "Enable").Call(cmd))
		}
	}

	return items
}

// getFeatureCmd maps a feature config name to the jen expression naming its
// props FeatureCmd constant, derived from props.FeatureCatalogue — the single
// source of truth shared with the manifest scanner, so the renderer and scanner
// cannot disagree about the constant token for a feature. Returns nil for an
// unknown name (e.g. keychain, which is not a SetFeatures toggle).
func getFeatureCmd(feature string) jen.Code {
	for _, d := range FeatureCatalogue {
		if string(d.Cmd) == feature {
			return jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/props", d.ConstName)
		}
	}

	return nil
}
