package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonTrustKeys generates internal/trustkeys/trustkeys.go for
// scaffolded projects with signing enabled. It mirrors go-tool-base's
// own internal/trustkeys/trustkeys.go: a //go:embed of the keys
// directory plus a Keys() [][]byte accessor that walks keys/*.asc.
//
// The package is generated and regeneration-protected; the author adds
// their minted release public key(s) as files under keys/, never by
// editing this .go. With no keys present Keys returns nil, so signature
// verification stays dormant until a real key is dropped in.
func SkeletonTrustKeys() *jen.File {
	f := jen.NewFile("trustkeys")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")
	f.PackageComment("Package trustkeys exposes the public keys embedded in the binary")
	f.PackageComment("for self-update signature verification.")
	f.PackageComment("")
	f.PackageComment("To embed a release public key, drop its ASCII-armored form into")
	f.PackageComment("internal/trustkeys/keys/<name>.asc. Every *.asc file in that")
	f.PackageComment("directory is embedded at build time and surfaced to the")
	f.PackageComment("SelfUpdater via props.Tool.Signing.EmbeddedKeys.")
	f.PackageComment("")
	f.PackageComment("The directory ships empty (only a .gitkeep): with no keys present")
	f.PackageComment("Keys returns nil, so signature verification stays dormant until a")
	f.PackageComment("real key is added and the rollout flips require_signature.")

	f.Comment("keyFS embeds the keys directory. `all:` is required so the directory")
	f.Comment("matches even when it contains only a dotfile (.gitkeep); without an")
	f.Comment("embeddable entry the //go:embed directive would fail to compile.")
	f.Comment("//go:embed all:keys")
	f.Var().Id("keyFS").Qual("embed", "FS")

	f.Comment("Keys returns every embedded ASCII-armored public key (the contents of")
	f.Comment("internal/trustkeys/keys/*.asc). It returns nil when no key files are")
	f.Comment("present, which leaves the embedded trust anchor unset.")
	f.Func().Id("Keys").Params().Index().Index().Byte().Block(
		jen.Var().Id("out").Index().Index().Byte(),
		jen.Line(),
		jen.Id("_").Op("=").Qual("io/fs", "WalkDir").Call(
			jen.Id("keyFS"),
			jen.Lit("keys"),
			jen.Func().Params(
				jen.Id("p").String(),
				jen.Id("d").Qual("io/fs", "DirEntry"),
				jen.Err().Error(),
			).Error().Block(
				jen.If(jen.Err().Op("!=").Nil().Op("||").Id("d").Dot("IsDir").Call()).Block(
					jen.Return(jen.Err()),
				),
				jen.Line(),
				jen.If(jen.Qual("path", "Ext").Call(jen.Id("p")).Op("!=").Lit(".asc")).Block(
					jen.Return(jen.Nil()),
				),
				jen.Line(),
				jen.List(jen.Id("b"), jen.Id("readErr")).Op(":=").Id("keyFS").Dot("ReadFile").Call(jen.Id("p")),
				jen.If(jen.Id("readErr").Op("!=").Nil()).Block(
					jen.Return(jen.Id("readErr")),
				),
				jen.Line(),
				jen.Id("out").Op("=").Append(jen.Id("out"), jen.Id("b")),
				jen.Line(),
				jen.Return(jen.Nil()),
			),
		),
		jen.Line(),
		jen.Return(jen.Id("out")),
	)

	return f
}
