package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonSigningData carries the manifest signing posture into the
// generated signing.go enforcement defaults.
type SkeletonSigningData struct {
	ExternalKeyEmail          string
	RequireSignature          bool
	KeySource                 string // "embedded" | "external" | "both"; empty → framework default
	RequireExternalCrosscheck bool
}

// SkeletonSigning generates pkg/cmd/root/signing.go for scaffolded
// projects with signing enabled. It mirrors go-tool-base's own
// internal/cmd/root/signing.go split: an init() that sets the
// pkg/setup enforcement defaults, kept in a sibling file to the
// templated root command. The values come from the manifest signing
// block rather than being hand-written, so the author tunes posture
// via `gtb enable signing` flags, not by editing generated code.
//
// Only non-default values are emitted, so a freshly enabled project
// (no email, require_signature off, default key source) produces an
// init() that does nothing until the author configures a posture.
func SkeletonSigning(data SkeletonSigningData) *jen.File {
	f := jen.NewFile("root")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")
	f.PackageComment("Self-update signature-verification enforcement defaults.")
	f.PackageComment("Generated from the .gtb/manifest.yaml signing block; tune the")
	f.PackageComment("posture via `gtb enable signing` flags, never by editing this file.")

	var body []jen.Code

	if data.RequireSignature {
		body = append(body,
			jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/setup", "DefaultRequireSignature").Op("=").True(),
		)
	}

	if data.KeySource != "" {
		body = append(body,
			jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/setup", "DefaultKeySource").Op("=").Lit(data.KeySource),
		)
	}

	if data.RequireExternalCrosscheck {
		body = append(body,
			jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/setup", "DefaultRequireExternalCrosscheck").Op("=").True(),
		)
	}

	if data.ExternalKeyEmail != "" {
		body = append(body,
			jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/setup", "DefaultExternalKeyEmail").Op("=").Lit(data.ExternalKeyEmail),
		)
	}

	if len(body) == 0 {
		// Nothing to enforce yet: emit a no-op init() with a blank
		// reference to the setup package so the import stays meaningful
		// and the file is self-explanatory.
		f.Comment("No enforcement posture configured yet. Set one with")
		f.Comment("`gtb enable signing --email ... --require-signature` once a")
		f.Comment("signed release has shipped (see the N+1 rollout discipline).")
		f.Func().Id("init").Params().Block()

		return f
	}

	f.Func().Id("init").Params().Block(body...)

	return f
}
