package docs_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/phpboyscout/go-tool-base/pkg/docs"
	"gitlab.com/phpboyscout/go-tool-base/pkg/props"
	"gitlab.com/phpboyscout/go-tool-base/pkg/version"
)

// fixtureTree builds a small command tree: root "demo" with a "build"
// subcommand that itself has a "now" subcommand.
func fixtureTree() *cobra.Command {
	root := &cobra.Command{Use: "demo", Short: "demo root", Long: "The demo root command."}
	build := &cobra.Command{Use: "build", Short: "build things", Run: func(*cobra.Command, []string) {}}
	now := &cobra.Command{Use: "now", Short: "build now", Run: func(*cobra.Command, []string) {}}
	build.AddCommand(now)
	root.AddCommand(build)

	return root
}

func TestGenerateManTree_WritesPagePerCommand(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	err := docs.GenerateManTree(fixtureTree(), docs.ManOptions{
		Dir:    dir,
		Source: "demo 1.0.0",
		Manual: "Demo Manual",
	})
	require.NoError(t, err)

	for _, name := range []string{"demo.1", "demo-build.1", "demo-build-now.1"} {
		path := filepath.Join(dir, "man1", name)
		assert.FileExistsf(t, path, "expected man page %s", name)
	}
}

func TestGenerateManTree_HeaderPolicy(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	require.NoError(t, docs.GenerateManTree(fixtureTree(), docs.ManOptions{
		Dir:    dir,
		Source: "demo 1.0.0",
		Manual: "Demo Manual",
	}))

	data, err := os.ReadFile(filepath.Join(dir, "man1", "demo.1"))
	require.NoError(t, err)
	roff := string(data)

	assert.Contains(t, roff, "demo 1.0.0", "configured Source must appear in .TH")
	assert.Contains(t, roff, "Demo Manual", "configured Manual must appear in .TH")
	assert.NotContains(t, roff, "Auto generated by spf13/cobra",
		"the cobra placeholder must never ship")
}

func TestGenerateManTree_DefaultsSourceAndManual(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	require.NoError(t, docs.GenerateManTree(fixtureTree(), docs.ManOptions{Dir: dir}))

	data, err := os.ReadFile(filepath.Join(dir, "man1", "demo.1"))
	require.NoError(t, err)
	roff := string(data)

	assert.Contains(t, roff, "Demo Manual", "Manual defaults to title-cased program name")
	assert.NotContains(t, roff, "Auto generated by spf13/cobra")
}

func TestGenerateManTree_Reproducible(t *testing.T) {
	t.Parallel()

	read := func() []byte {
		dir := t.TempDir()
		require.NoError(t, docs.GenerateManTree(fixtureTree(), docs.ManOptions{
			Dir:    dir,
			Source: "demo 1.0.0",
			Manual: "Demo Manual",
		}))
		data, err := os.ReadFile(filepath.Join(dir, "man1", "demo.1"))
		require.NoError(t, err)

		return data
	}

	// With Date nil the auto-gen trailer is suppressed, so two runs are
	// byte-identical (SOURCE_DATE_EPOCH-independent within the same month).
	first := read()
	second := read()
	assert.Equal(t, first, second)
}

func TestGenerateManTree_DateStamped(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	when := time.Date(2026, time.June, 21, 0, 0, 0, 0, time.UTC)
	require.NoError(t, docs.GenerateManTree(fixtureTree(), docs.ManOptions{
		Dir:    dir,
		Source: "demo 1.0.0",
		Manual: "Demo Manual",
		Date:   &when,
	}))

	data, err := os.ReadFile(filepath.Join(dir, "man1", "demo.1"))
	require.NoError(t, err)
	assert.Contains(t, string(data), "Jun 2026", "explicit --date is stamped into .TH")
}

func TestGenerateManTree_NilRoot(t *testing.T) {
	t.Parallel()

	err := docs.GenerateManTree(nil, docs.ManOptions{Dir: t.TempDir()})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "nil root")
}

func TestGenerateManTree_UnwritableDir(t *testing.T) {
	t.Parallel()

	// Place the output dir under a regular file so MkdirAll fails.
	file := filepath.Join(t.TempDir(), "blocker")
	require.NoError(t, os.WriteFile(file, []byte("x"), 0o600))

	err := docs.GenerateManTree(fixtureTree(), docs.ManOptions{Dir: filepath.Join(file, "sub")})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "man output directory")
}

func TestGenerateManPage_SinglePageToWriter(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	err := docs.GenerateManPage(&buf, fixtureTree(), docs.ManOptions{Source: "demo 1.0.0"})
	require.NoError(t, err)

	out := buf.String()
	// Only the root page is rendered, with GTB's header policy applied: the
	// .TH header carries the defaulted manual title and no auto-gen trailer.
	// The root's own NAME section is present; the subcommand's description is
	// not (its page would be separate), confirming this is a single page.
	assert.Contains(t, out, ".TH")
	assert.Contains(t, out, "Demo Manual")
	assert.Contains(t, out, "demo - demo root")
	assert.NotContains(t, out, "Auto generated by spf13/cobra")
	assert.NotContains(t, out, "build things")
}

func TestGenerateManPage_NilCommand(t *testing.T) {
	t.Parallel()

	err := docs.GenerateManPage(&bytes.Buffer{}, nil, docs.ManOptions{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "nil command")
}

// failWriter fails every write so the doc.GenMan render error is exercised.
type failWriter struct{}

func (failWriter) Write([]byte) (int, error) {
	return 0, assert.AnError
}

func TestGenerateManPage_RenderError(t *testing.T) {
	t.Parallel()

	err := docs.GenerateManPage(failWriter{}, fixtureTree(), docs.ManOptions{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "rendering man page")
}

func TestGenerateManTree_RenderError(t *testing.T) {
	t.Parallel()

	// Pre-create the root page path as a directory so cobra's os.Create fails
	// while the output directory itself is writable.
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "man1", "demo.1"), 0o755))

	err := docs.GenerateManTree(fixtureTree(), docs.ManOptions{Dir: dir})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generating man tree")
}

func TestManPagePaths(t *testing.T) {
	t.Parallel()

	paths := docs.ManPagePaths(fixtureTree(), docs.ManOptions{Dir: "out"})

	assert.Equal(t, []string{
		filepath.Join("out", "man1", "demo-build-now.1"),
		filepath.Join("out", "man1", "demo-build.1"),
		filepath.Join("out", "man1", "demo.1"),
	}, paths)
}

func TestManPagePaths_SectionDefaultAndOverride(t *testing.T) {
	t.Parallel()

	def := docs.ManPagePaths(fixtureTree(), docs.ManOptions{Dir: "out"})
	assert.Contains(t, def, filepath.Join("out", "man1", "demo.1"))

	sec8 := docs.ManPagePaths(fixtureTree(), docs.ManOptions{Dir: "out", Section: "8"})
	assert.Contains(t, sec8, filepath.Join("out", "man8", "demo.8"))
}

func TestManSource(t *testing.T) {
	t.Parallel()

	withVer := &props.Props{Version: version.Info{Version: "1.2.3"}}
	assert.Equal(t, "demo 1.2.3", docs.ManSource("demo", withVer))

	noVer := &props.Props{Version: version.Info{}}
	assert.Equal(t, "demo", docs.ManSource("demo", noVer))

	assert.Equal(t, "demo", docs.ManSource("demo", nil))
}
