// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package release

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/vcs/release"
)

// NewMockChecksumProvider creates a new instance of MockChecksumProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecksumProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecksumProvider {
	mock := &MockChecksumProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecksumProvider is an autogenerated mock type for the ChecksumProvider type
type MockChecksumProvider struct {
	mock.Mock
}

type MockChecksumProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecksumProvider) EXPECT() *MockChecksumProvider_Expecter {
	return &MockChecksumProvider_Expecter{mock: &_m.Mock}
}

// DownloadChecksumManifest provides a mock function for the type MockChecksumProvider
func (_mock *MockChecksumProvider) DownloadChecksumManifest(ctx context.Context, rel release.Release, maxBytes int64) ([]byte, error) {
	ret := _mock.Called(ctx, rel, maxBytes)

	if len(ret) == 0 {
		panic("no return value specified for DownloadChecksumManifest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, release.Release, int64) ([]byte, error)); ok {
		return returnFunc(ctx, rel, maxBytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, release.Release, int64) []byte); ok {
		r0 = returnFunc(ctx, rel, maxBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, release.Release, int64) error); ok {
		r1 = returnFunc(ctx, rel, maxBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecksumProvider_DownloadChecksumManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadChecksumManifest'
type MockChecksumProvider_DownloadChecksumManifest_Call struct {
	*mock.Call
}

// DownloadChecksumManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - rel release.Release
//   - maxBytes int64
func (_e *MockChecksumProvider_Expecter) DownloadChecksumManifest(ctx interface{}, rel interface{}, maxBytes interface{}) *MockChecksumProvider_DownloadChecksumManifest_Call {
	return &MockChecksumProvider_DownloadChecksumManifest_Call{Call: _e.mock.On("DownloadChecksumManifest", ctx, rel, maxBytes)}
}

func (_c *MockChecksumProvider_DownloadChecksumManifest_Call) Run(run func(ctx context.Context, rel release.Release, maxBytes int64)) *MockChecksumProvider_DownloadChecksumManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 release.Release
		if args[1] != nil {
			arg1 = args[1].(release.Release)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChecksumProvider_DownloadChecksumManifest_Call) Return(bytes []byte, err error) *MockChecksumProvider_DownloadChecksumManifest_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChecksumProvider_DownloadChecksumManifest_Call) RunAndReturn(run func(ctx context.Context, rel release.Release, maxBytes int64) ([]byte, error)) *MockChecksumProvider_DownloadChecksumManifest_Call {
	_c.Call.Return(run)
	return _c
}
