// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package release

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/vcs/release"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// GetString provides a mock function for the type MockConfig
func (_mock *MockConfig) GetString(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockConfig_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) GetString(key interface{}) *MockConfig_GetString_Call {
	return &MockConfig_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *MockConfig_GetString_Call) Run(run func(key string)) *MockConfig_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_GetString_Call) Return(s string) *MockConfig_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetString_Call) RunAndReturn(run func(key string) string) *MockConfig_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// Sub provides a mock function for the type MockConfig
func (_mock *MockConfig) Sub(key string) release.Config {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Sub")
	}

	var r0 release.Config
	if returnFunc, ok := ret.Get(0).(func(string) release.Config); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(release.Config)
		}
	}
	return r0
}

// MockConfig_Sub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sub'
type MockConfig_Sub_Call struct {
	*mock.Call
}

// Sub is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) Sub(key interface{}) *MockConfig_Sub_Call {
	return &MockConfig_Sub_Call{Call: _e.mock.On("Sub", key)}
}

func (_c *MockConfig_Sub_Call) Run(run func(key string)) *MockConfig_Sub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_Sub_Call) Return(config release.Config) *MockConfig_Sub_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockConfig_Sub_Call) RunAndReturn(run func(key string) release.Config) *MockConfig_Sub_Call {
	_c.Call.Return(run)
	return _c
}
