// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package root

import (
	"github.com/spf13/pflag"
	mock "github.com/stretchr/testify/mock"
)

// newMockbindable creates a new instance of mockbindable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbindable(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbindable {
	mock := &mockbindable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbindable is an autogenerated mock type for the bindable type
type mockbindable struct {
	mock.Mock
}

type mockbindable_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbindable) EXPECT() *mockbindable_Expecter {
	return &mockbindable_Expecter{mock: &_m.Mock}
}

// BindPFlag provides a mock function for the type mockbindable
func (_mock *mockbindable) BindPFlag(key string, flag *pflag.Flag) error {
	ret := _mock.Called(key, flag)

	if len(ret) == 0 {
		panic("no return value specified for BindPFlag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *pflag.Flag) error); ok {
		r0 = returnFunc(key, flag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbindable_BindPFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindPFlag'
type mockbindable_BindPFlag_Call struct {
	*mock.Call
}

// BindPFlag is a helper method to define mock.On call
//   - key string
//   - flag *pflag.Flag
func (_e *mockbindable_Expecter) BindPFlag(key interface{}, flag interface{}) *mockbindable_BindPFlag_Call {
	return &mockbindable_BindPFlag_Call{Call: _e.mock.On("BindPFlag", key, flag)}
}

func (_c *mockbindable_BindPFlag_Call) Run(run func(key string, flag *pflag.Flag)) *mockbindable_BindPFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *pflag.Flag
		if args[1] != nil {
			arg1 = args[1].(*pflag.Flag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbindable_BindPFlag_Call) Return(err error) *mockbindable_BindPFlag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbindable_BindPFlag_Call) RunAndReturn(run func(key string, flag *pflag.Flag) error) *mockbindable_BindPFlag_Call {
	_c.Call.Return(run)
	return _c
}
