// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package root

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockdebugLogger creates a new instance of mockdebugLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdebugLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdebugLogger {
	mock := &mockdebugLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdebugLogger is an autogenerated mock type for the debugLogger type
type mockdebugLogger struct {
	mock.Mock
}

type mockdebugLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdebugLogger) EXPECT() *mockdebugLogger_Expecter {
	return &mockdebugLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type mockdebugLogger
func (_mock *mockdebugLogger) Debug(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// mockdebugLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type mockdebugLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *mockdebugLogger_Expecter) Debug(msg interface{}, args ...interface{}) *mockdebugLogger_Debug_Call {
	return &mockdebugLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *mockdebugLogger_Debug_Call) Run(run func(msg string, args ...any)) *mockdebugLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockdebugLogger_Debug_Call) Return() *mockdebugLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockdebugLogger_Debug_Call) RunAndReturn(run func(msg string, args ...any)) *mockdebugLogger_Debug_Call {
	_c.Run(run)
	return _c
}
