// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setup

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockboolConfig creates a new instance of mockboolConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockboolConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockboolConfig {
	mock := &mockboolConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockboolConfig is an autogenerated mock type for the boolConfig type
type mockboolConfig struct {
	mock.Mock
}

type mockboolConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *mockboolConfig) EXPECT() *mockboolConfig_Expecter {
	return &mockboolConfig_Expecter{mock: &_m.Mock}
}

// GetBool provides a mock function for the type mockboolConfig
func (_mock *mockboolConfig) GetBool(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockboolConfig_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type mockboolConfig_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - key string
func (_e *mockboolConfig_Expecter) GetBool(key interface{}) *mockboolConfig_GetBool_Call {
	return &mockboolConfig_GetBool_Call{Call: _e.mock.On("GetBool", key)}
}

func (_c *mockboolConfig_GetBool_Call) Run(run func(key string)) *mockboolConfig_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockboolConfig_GetBool_Call) Return(b bool) *mockboolConfig_GetBool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockboolConfig_GetBool_Call) RunAndReturn(run func(key string) bool) *mockboolConfig_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function for the type mockboolConfig
func (_mock *mockboolConfig) IsSet(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockboolConfig_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type mockboolConfig_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - key string
func (_e *mockboolConfig_Expecter) IsSet(key interface{}) *mockboolConfig_IsSet_Call {
	return &mockboolConfig_IsSet_Call{Call: _e.mock.On("IsSet", key)}
}

func (_c *mockboolConfig_IsSet_Call) Run(run func(key string)) *mockboolConfig_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockboolConfig_IsSet_Call) Return(b bool) *mockboolConfig_IsSet_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockboolConfig_IsSet_Call) RunAndReturn(run func(key string) bool) *mockboolConfig_IsSet_Call {
	_c.Call.Return(run)
	return _c
}
