// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setup

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockstringConfig creates a new instance of mockstringConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstringConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstringConfig {
	mock := &mockstringConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstringConfig is an autogenerated mock type for the stringConfig type
type mockstringConfig struct {
	mock.Mock
}

type mockstringConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstringConfig) EXPECT() *mockstringConfig_Expecter {
	return &mockstringConfig_Expecter{mock: &_m.Mock}
}

// GetString provides a mock function for the type mockstringConfig
func (_mock *mockstringConfig) GetString(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockstringConfig_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type mockstringConfig_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *mockstringConfig_Expecter) GetString(key interface{}) *mockstringConfig_GetString_Call {
	return &mockstringConfig_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *mockstringConfig_GetString_Call) Run(run func(key string)) *mockstringConfig_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstringConfig_GetString_Call) Return(s string) *mockstringConfig_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockstringConfig_GetString_Call) RunAndReturn(run func(key string) string) *mockstringConfig_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function for the type mockstringConfig
func (_mock *mockstringConfig) IsSet(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockstringConfig_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type mockstringConfig_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - key string
func (_e *mockstringConfig_Expecter) IsSet(key interface{}) *mockstringConfig_IsSet_Call {
	return &mockstringConfig_IsSet_Call{Call: _e.mock.On("IsSet", key)}
}

func (_c *mockstringConfig_IsSet_Call) Run(run func(key string)) *mockstringConfig_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstringConfig_IsSet_Call) Return(b bool) *mockstringConfig_IsSet_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockstringConfig_IsSet_Call) RunAndReturn(run func(key string) bool) *mockstringConfig_IsSet_Call {
	_c.Call.Return(run)
	return _c
}
