package man_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	cmdman "gitlab.com/phpboyscout/go-tool-base/pkg/cmd/man"
	"gitlab.com/phpboyscout/go-tool-base/pkg/logger"
	p "gitlab.com/phpboyscout/go-tool-base/pkg/props"
	"gitlab.com/phpboyscout/go-tool-base/pkg/version"
)

func newProps() *p.Props {
	return &p.Props{
		Logger:  logger.NewNoop(),
		Version: version.Info{Version: "3.2.1"},
		Tool:    p.Tool{Name: "demo"},
	}
}

// attach mounts the man command under a fake "demo" root so cmd.Root() resolves
// to a real tree, and returns the root ready to Execute.
func attach(t *testing.T) (*cobra.Command, *bytes.Buffer) {
	t.Helper()
	root := &cobra.Command{Use: "demo"}
	root.AddCommand(&cobra.Command{Use: "build", Run: func(*cobra.Command, []string) {}})
	root.AddCommand(cmdman.NewCmdMan(newProps()).Command)

	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)

	return root, &buf
}

func TestNewCmdMan_Hidden(t *testing.T) {
	t.Parallel()

	cmd := cmdman.NewCmdMan(newProps())
	assert.True(t, cmd.Hidden, "man must be hidden from --help listings")
}

func TestRuntimeMan_StdoutSinglePage(t *testing.T) {
	t.Parallel()

	root, buf := attach(t)
	root.SetArgs([]string{"man"})

	require.NoError(t, root.Execute())

	out := buf.String()
	assert.Contains(t, out, ".TH", "roff page is emitted to stdout")
	assert.Contains(t, out, "demo 3.2.1", "source footer carries tool + version")
	assert.NotContains(t, out, "Auto generated by spf13/cobra")
}

func TestRuntimeMan_SourceFallsBackToName(t *testing.T) {
	t.Parallel()

	// Props with no version: source must fall back to the bare program name.
	noVer := &p.Props{Logger: logger.NewNoop(), Version: version.Info{}, Tool: p.Tool{Name: "demo"}}
	root := &cobra.Command{Use: "demo"}
	root.AddCommand(cmdman.NewCmdMan(noVer).Command)

	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetArgs([]string{"man"})

	require.NoError(t, root.Execute())
	assert.Contains(t, buf.String(), ".TH")
}

func TestRuntimeMan_DirWritesTree(t *testing.T) {
	t.Parallel()

	root, _ := attach(t)
	dir := t.TempDir()
	root.SetArgs([]string{"man", "--dir", dir})

	require.NoError(t, root.Execute())

	for _, name := range []string{"demo.1", "demo-build.1"} {
		page := filepath.Join(dir, "man1", name)
		require.FileExistsf(t, page, "expected %s", name)
	}

	data, err := os.ReadFile(filepath.Join(dir, "man1", "demo.1"))
	require.NoError(t, err)
	assert.Contains(t, string(data), "demo 3.2.1")
}
