package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonChatProviders generates cmd/<name>/chat.go: one blank import per
// chat provider module the manifest's chat.providers selects. Deleting the
// file drops every chat SDK from the linked binary; regenerate rewrites it
// from the manifest (spec 0194 D6).
func SkeletonChatProviders(modules []string) *jen.File {
	return blankImportFile(
		"Registers the chat providers this tool ships, one module per line.",
		"Generated from .gtb/manifest.yaml chat.providers; edit the manifest and",
		"regenerate rather than this file. Set providers to [] to ship none.",
		modules,
	)
}

// SkeletonForgeAdapters generates cmd/<name>/forge.go: one blank import per
// forge adapter the manifest's enabled forge features need. Deleting the file
// drops every forge SDK from the linked binary; regenerate rewrites it from
// the manifest (spec 0194 D4, D6).
func SkeletonForgeAdapters(modules []string) *jen.File {
	return blankImportFile(
		"Registers the forge adapters this tool ships, one module per line.",
		"Generated from the forge features in .gtb/manifest.yaml; enable or",
		"disable a forge and regenerate rather than editing this file.",
		modules,
	)
}

func blankImportFile(comment1, comment2, comment3 string, modules []string) *jen.File {
	f := jen.NewFile("main")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")
	f.PackageComment(comment1)
	f.PackageComment(comment2)
	f.PackageComment(comment3)

	for _, m := range modules {
		f.Anon(m)
	}

	return f
}
