package templates

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSkeletonChatProviders(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	require.NoError(t, SkeletonChatProviders([]string{
		"gitlab.com/phpboyscout/go/chat-anthropic",
		"gitlab.com/phpboyscout/go/chat-openai",
	}).Render(&buf))

	out := buf.String()
	assert.Contains(t, out, "Code generated by gtb. DO NOT EDIT.")
	assert.Contains(t, out, "package main")
	assert.Contains(t, out, `_ "gitlab.com/phpboyscout/go/chat-anthropic"`)
	assert.Contains(t, out, `_ "gitlab.com/phpboyscout/go/chat-openai"`)
	assert.NotContains(t, out, "chat-gemini")
}

func TestSkeletonForgeAdapters_EmptyIsStillValidGo(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	require.NoError(t, SkeletonForgeAdapters(nil).Render(&buf))

	assert.Contains(t, buf.String(), "package main")
	assert.NotContains(t, buf.String(), "import")
}
