package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonMain generates the cmd/<name>/main.go for scaffolded projects.
// It uses the internal/version package to retrieve version info and passes
// it to the root command constructor. Execution is delegated to
// gtbRoot.Execute, which runs the command tree with a signal-aware context:
// SIGINT/SIGTERM cancel cmd.Context() for graceful shutdown, a second signal
// force-exits, and a signal-terminated run exits 128+signum.
func SkeletonMain(modulePath string) *jen.File {
	f := jen.NewFile("main")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	f.ImportAlias("gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root", "gtbRoot")

	f.Comment("main delegates to gtbRoot.Execute, which runs the command tree with a")
	f.Comment("signal-aware context: SIGINT/SIGTERM cancel cmd.Context() for graceful")
	f.Comment("shutdown, a second signal force-exits immediately, and a signal-terminated")
	f.Comment("run exits 128+signum (130 SIGINT, 143 SIGTERM).")
	f.Func().Id("main").Params().Block(
		jen.List(jen.Id("rootCmd"), jen.Id("p")).Op(":=").Qual(modulePath+"/pkg/cmd/root", "NewCmdRoot").Call(
			jen.Qual(modulePath+"/internal/version", "Get").Call(),
		),
		jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root", "Execute").Call(jen.Id("rootCmd"), jen.Id("p")),
	)

	return f
}
