package templates

import (
	"github.com/dave/jennifer/jen"

	"gitlab.com/phpboyscout/go-tool-base/pkg/props"
)

// FrameworkLinks are the catalogue's link kinds that name a package to
// blank-import: the features a scaffold turns on by carrying
// cmd/<name>/<id>.go (keychain, mcp). A generated adapter link (chat-*,
// forge-*) names no package; the scaffold's own chat.go and forge.go declare
// those beside the imports they record (spec 0202 D6).
func FrameworkLinks() []props.FeatureDescriptor {
	var out []props.FeatureDescriptor

	for _, d := range Catalogue() {
		if d.Kind == props.KindLink && d.ConstPackage != "" {
			out = append(out, d)
		}
	}

	return out
}

// SkeletonLink generates cmd/<name>/<id>.go for a framework link: a main
// package file whose only statement is the blank import of the package the
// descriptor names. The file is the feature: the manifest's entry writes or
// removes it through the shared sync, and a build without it links nothing
// the package reaches, which build info on the artefact can verify.
func SkeletonLink(d props.FeatureDescriptor) *jen.File {
	id := string(d.ID)

	f := jen.NewFile("main")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")
	f.PackageComment("Links the " + id + " feature by blank-importing the framework")
	f.PackageComment("package that declares it and contributes what it needs. The")
	f.PackageComment("file is the switch: toggle it with `gtb enable " + id + "` /")
	f.PackageComment("`gtb disable " + id + "`, and a build without this file carries")
	f.PackageComment("nothing the package reaches.")

	f.Anon(d.ConstPackage)

	return f
}
