package templates_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/phpboyscout/go-tool-base/cli/pkg/generator/templates"
	"gitlab.com/phpboyscout/go-tool-base/pkg/mcp"
	"gitlab.com/phpboyscout/go-tool-base/pkg/props"
	"gitlab.com/phpboyscout/go-tool-base/pkg/setup/keychain"
)

// TestFrameworkLinks: the links the generator writes as cmd/<name>/<id>.go are
// the catalogue's link kinds that name a package to import; the keychain and
// mcp today (spec 0202 D6). A generated adapter link (chat-*, forge-*) names
// no package and is the scaffold's own file.
func TestFrameworkLinks(t *testing.T) {
	t.Parallel()

	byID := map[props.FeatureID]props.FeatureDescriptor{}
	for _, d := range templates.FrameworkLinks() {
		assert.Equal(t, props.KindLink, d.Kind)
		assert.NotEmpty(t, d.ConstPackage, "%s: a framework link names the package to import", d.ID)
		byID[d.ID] = d
	}

	require.Contains(t, byID, keychain.KeychainFeature)
	require.Contains(t, byID, props.McpCmd)
	assert.Equal(t, keychain.PackagePath, byID[keychain.KeychainFeature].ConstPackage)
	assert.Equal(t, mcp.PackagePath, byID[props.McpCmd].ConstPackage)
}

// TestSkeletonLink: one template renders every framework link, a main-package
// file whose only statement is the blank import, with a comment that names the
// feature and the toggle.
func TestSkeletonLink(t *testing.T) {
	t.Parallel()

	for _, d := range templates.FrameworkLinks() {
		src := templates.SkeletonLink(d).GoString()

		assert.Contains(t, src, "Code generated by gtb. DO NOT EDIT.")
		assert.Contains(t, src, "package main")
		assert.Contains(t, src, `_ "`+d.ConstPackage+`"`)
		assert.Contains(t, src, "gtb enable "+string(d.ID))
		assert.Contains(t, src, "gtb disable "+string(d.ID))
	}
}
