package templates

import (
	"bytes"
	"go/parser"
	"go/token"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSkeletonChatProviders(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	require.NoError(t, SkeletonChatProviders([]string{
		"gitlab.com/phpboyscout/go/chat-anthropic",
		"gitlab.com/phpboyscout/go/chat-openai",
	}, false).Render(&buf))

	out := buf.String()
	assert.Contains(t, out, "Code generated by gtb. DO NOT EDIT.")
	assert.Contains(t, out, "package main")
	assert.Contains(t, out, `_ "gitlab.com/phpboyscout/go/chat-anthropic"`)
	assert.Contains(t, out, `_ "gitlab.com/phpboyscout/go/chat-openai"`)
	assert.NotContains(t, out, "chat-gemini")
}

// TestSkeletonChatProviders_WithDefaultsEmbedsTheBundle pins spec 0196 D4:
// the directive is a real //go:embed (jennifer would otherwise render it as a
// comment with a space), the bundle is re-rooted, and the file parses.
func TestSkeletonChatProviders_WithDefaultsEmbedsTheBundle(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	require.NoError(t, SkeletonChatProviders([]string{"gitlab.com/phpboyscout/go/chat-openai"}, true).Render(&buf))

	out := buf.String()
	assert.Contains(t, out, "\n//go:embed chat\nvar chatDefaults embed.FS\n")
	assert.Contains(t, out, `fs.Sub(chatDefaults, "chat")`)
	assert.Contains(t, out, `setup.RegisterAssets(props.AiCmd, "chat", sub)`)

	_, err := parser.ParseFile(token.NewFileSet(), "chat.go", out, parser.ParseComments)
	require.NoError(t, err)
}

func TestSkeletonForgeAdapters_EmptyIsStillValidGo(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	require.NoError(t, SkeletonForgeAdapters(nil).Render(&buf))

	assert.Contains(t, buf.String(), "package main")
	assert.NotContains(t, buf.String(), "import")
}
