package templates

import (
	"go/parser"
	"go/token"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSkeletonTrustKeys(t *testing.T) {
	t.Parallel()

	src := renderGoFile(t, SkeletonTrustKeys())

	assert.Contains(t, src, "// Code generated by gtb. DO NOT EDIT.")
	assert.Contains(t, src, "package trustkeys")
	assert.Contains(t, src, "//go:embed all:keys\nvar keyFS embed.FS")
	assert.Contains(t, src, "func Keys() [][]byte {")
	assert.Contains(t, src, `fs.WalkDir(keyFS, "keys", func(p string, d fs.DirEntry, err error) error {`)
	assert.Contains(t, src, `if path.Ext(p) != ".asc" {`)
	assert.Contains(t, src, "b, readErr := keyFS.ReadFile(p)")
	assert.Contains(t, src, "out = append(out, b)")
}

func TestSkeletonInternalVersion(t *testing.T) {
	t.Parallel()

	src := renderGoFile(t, SkeletonInternalVersion())

	assert.Contains(t, src, "package version")
	assert.Contains(t, src, `pkgversion "gitlab.com/phpboyscout/go-tool-base/pkg/version"`)
	assert.Contains(t, src, `version = "dev"`)
	assert.Contains(t, src, "info, ok := debug.ReadBuildInfo()")
	assert.Contains(t, src, `case "vcs.revision":`)
	assert.Contains(t, src, `case "vcs.time":`)
	assert.Contains(t, src, `commit += "-dirty"`)
	assert.Contains(t, src, `} else if commit != "none" {`)
	assert.Contains(t, src, "func Get() pkgversion.Info {")
	assert.Contains(t, src, "return pkgversion.NewInfo(version, commit, date)")
}

func TestSkeletonSigning(t *testing.T) {
	t.Parallel()

	t.Run("no posture is a no-op init", func(t *testing.T) {
		t.Parallel()

		src := renderGoFile(t, SkeletonSigning(SkeletonSigningData{}))

		assert.Contains(t, src, "package root")
		assert.Contains(t, src, "func init() {}")
		assert.Contains(t, src, "No enforcement posture configured yet.")
		assert.NotContains(t, src, "verify.")
	})

	t.Run("full posture", func(t *testing.T) {
		t.Parallel()

		src := renderGoFile(t, SkeletonSigning(SkeletonSigningData{
			ExternalKeyEmail:          "release@example.org",
			RequireSignature:          true,
			KeySource:                 "both",
			RequireExternalCrosscheck: true,
		}))

		assert.Contains(t, src, `"gitlab.com/phpboyscout/go/signing/verify"`)
		assert.Contains(t, src, "verify.DefaultRequireSignature = true")
		assert.Contains(t, src, `verify.DefaultKeySource = "both"`)
		assert.Contains(t, src, "verify.DefaultRequireExternalCrosscheck = true")
		assert.Contains(t, src, `verify.DefaultExternalKeyEmail = "release@example.org"`)
		assert.NotContains(t, src, "No enforcement posture")
	})

	t.Run("only the stated values", func(t *testing.T) {
		t.Parallel()

		src := renderGoFile(t, SkeletonSigning(SkeletonSigningData{KeySource: "embedded"}))

		assert.Contains(t, src, `verify.DefaultKeySource = "embedded"`)
		assert.NotContains(t, src, "DefaultRequireSignature")
		assert.NotContains(t, src, "DefaultExternalKeyEmail")
	})
}

func TestSkeletonConfigFormats(t *testing.T) {
	t.Parallel()

	src := renderGoFile(t, SkeletonConfigFormats([]string{
		"gitlab.com/phpboyscout/go-tool-base/pkg/config/formats/toml",
	}))

	assert.Contains(t, src, "package main")
	assert.Contains(t, src, "Links the config formats this tool reads beyond YAML")
	assert.Contains(t, src, `_ "gitlab.com/phpboyscout/go-tool-base/pkg/config/formats/toml"`)
}

func TestSkeletonExternalAdapter(t *testing.T) {
	t.Parallel()

	src := SkeletonExternalAdapter()

	_, err := parser.ParseFile(token.NewFileSet(), "attach.go", src, parser.ParseComments)
	require.NoError(t, err, src)

	assert.Contains(t, src, "package external")
	assert.Contains(t, src, "func Commands(p *props.Props) []*setup.Command {")
	assert.Contains(t, src, "this file is yours to edit")
	assert.NotContains(t, src, "DO NOT EDIT", "the adapter is author-owned, not generated output")
}

func TestIsExternalArgToken(t *testing.T) {
	t.Parallel()

	for _, tok := range ExternalArgTokens {
		assert.Truef(t, IsExternalArgToken(tok), "%s is in the vocabulary", tok)
	}

	assert.False(t, IsExternalArgToken("os.Exit(1)"))
	assert.False(t, IsExternalArgToken(""))
}
