package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonMain generates the cmd/<name>/main.go for scaffolded projects.
// It uses the internal/version package to retrieve version info and passes
// it to the root command constructor. Execution is delegated to
// gtbRoot.Execute, which runs the command tree with a signal-aware context:
// SIGINT, SIGTERM and SIGHUP cancel cmd.Context() for graceful shutdown, a
// second signal ends the run at once, and a run a signal ended dies by that
// signal once drained, so a shell sees 128+signum.
func SkeletonMain(modulePath string) *jen.File {
	f := jen.NewFile("main")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	f.ImportAlias("gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root", "gtbRoot")

	f.Comment("main delegates to gtbRoot.Execute, which runs the command tree with a")
	f.Comment("signal-aware context: SIGINT, SIGTERM and SIGHUP cancel cmd.Context() for")
	f.Comment("graceful shutdown, a second signal ends the run immediately, and a run a")
	f.Comment("signal ended dies by that signal once drained (a shell sees 128+signum).")
	f.Comment("A construction error (an unnamed tool, an undeclared feature enabled) is a")
	f.Comment("defect in this project's wiring and exits 2, the usage code, before any")
	f.Comment("command runs.")
	f.Func().Id("main").Params().Block(
		jen.List(jen.Id("rootCmd"), jen.Id("p"), jen.Id("err")).Op(":=").Qual(modulePath+"/pkg/cmd/root", "NewCmdRoot").Call(
			jen.Qual(modulePath+"/internal/version", "Get").Call(),
		),
		jen.If(jen.Id("err").Op("!=").Nil()).Block(
			jen.Qual("fmt", "Fprintln").Call(jen.Qual("os", "Stderr"), jen.Id("err")),
			jen.Qual("os", "Exit").Call(jen.Qual("gitlab.com/phpboyscout/go/errorhandling", "ExitCodeUsage")),
		),
		jen.Qual("gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root", "Execute").Call(jen.Id("rootCmd"), jen.Id("p")),
	)

	return f
}
