// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/chat"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConversationStore creates a new instance of MockConversationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationStore {
	mock := &MockConversationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationStore is an autogenerated mock type for the ConversationStore type
type MockConversationStore struct {
	mock.Mock
}

type MockConversationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationStore) EXPECT() *MockConversationStore_Expecter {
	return &MockConversationStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockConversationStore
func (_mock *MockConversationStore) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConversationStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConversationStore_Expecter) Delete(ctx interface{}, id interface{}) *MockConversationStore_Delete_Call {
	return &MockConversationStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockConversationStore_Delete_Call) Run(run func(ctx context.Context, id string)) *MockConversationStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationStore_Delete_Call) Return(err error) *MockConversationStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockConversationStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockConversationStore
func (_mock *MockConversationStore) List(ctx context.Context) ([]chat.SnapshotSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []chat.SnapshotSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]chat.SnapshotSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []chat.SnapshotSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.SnapshotSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConversationStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConversationStore_Expecter) List(ctx interface{}) *MockConversationStore_List_Call {
	return &MockConversationStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockConversationStore_List_Call) Run(run func(ctx context.Context)) *MockConversationStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConversationStore_List_Call) Return(snapshotSummarys []chat.SnapshotSummary, err error) *MockConversationStore_List_Call {
	_c.Call.Return(snapshotSummarys, err)
	return _c
}

func (_c *MockConversationStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]chat.SnapshotSummary, error)) *MockConversationStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockConversationStore
func (_mock *MockConversationStore) Load(ctx context.Context, id string) (*chat.Snapshot, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *chat.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*chat.Snapshot, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *chat.Snapshot); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConversationStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConversationStore_Expecter) Load(ctx interface{}, id interface{}) *MockConversationStore_Load_Call {
	return &MockConversationStore_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockConversationStore_Load_Call) Run(run func(ctx context.Context, id string)) *MockConversationStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationStore_Load_Call) Return(snapshot *chat.Snapshot, err error) *MockConversationStore_Load_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockConversationStore_Load_Call) RunAndReturn(run func(ctx context.Context, id string) (*chat.Snapshot, error)) *MockConversationStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockConversationStore
func (_mock *MockConversationStore) Save(ctx context.Context, snapshot *chat.Snapshot) error {
	ret := _mock.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chat.Snapshot) error); ok {
		r0 = returnFunc(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConversationStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot *chat.Snapshot
func (_e *MockConversationStore_Expecter) Save(ctx interface{}, snapshot interface{}) *MockConversationStore_Save_Call {
	return &MockConversationStore_Save_Call{Call: _e.mock.On("Save", ctx, snapshot)}
}

func (_c *MockConversationStore_Save_Call) Run(run func(ctx context.Context, snapshot *chat.Snapshot)) *MockConversationStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chat.Snapshot
		if args[1] != nil {
			arg1 = args[1].(*chat.Snapshot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationStore_Save_Call) Return(err error) *MockConversationStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationStore_Save_Call) RunAndReturn(run func(ctx context.Context, snapshot *chat.Snapshot) error) *MockConversationStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
