// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/chat"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPersistentChatClient creates a new instance of MockPersistentChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersistentChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersistentChatClient {
	mock := &MockPersistentChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersistentChatClient is an autogenerated mock type for the PersistentChatClient type
type MockPersistentChatClient struct {
	mock.Mock
}

type MockPersistentChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersistentChatClient) EXPECT() *MockPersistentChatClient_Expecter {
	return &MockPersistentChatClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockPersistentChatClient
func (_mock *MockPersistentChatClient) Add(ctx context.Context, prompt string) error {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistentChatClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockPersistentChatClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockPersistentChatClient_Expecter) Add(ctx interface{}, prompt interface{}) *MockPersistentChatClient_Add_Call {
	return &MockPersistentChatClient_Add_Call{Call: _e.mock.On("Add", ctx, prompt)}
}

func (_c *MockPersistentChatClient_Add_Call) Run(run func(ctx context.Context, prompt string)) *MockPersistentChatClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersistentChatClient_Add_Call) Return(err error) *MockPersistentChatClient_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistentChatClient_Add_Call) RunAndReturn(run func(ctx context.Context, prompt string) error) *MockPersistentChatClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Ask provides a mock function for the type MockPersistentChatClient
func (_mock *MockPersistentChatClient) Ask(ctx context.Context, question string, target any) error {
	ret := _mock.Called(ctx, question, target)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, question, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistentChatClient_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type MockPersistentChatClient_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
//   - target any
func (_e *MockPersistentChatClient_Expecter) Ask(ctx interface{}, question interface{}, target interface{}) *MockPersistentChatClient_Ask_Call {
	return &MockPersistentChatClient_Ask_Call{Call: _e.mock.On("Ask", ctx, question, target)}
}

func (_c *MockPersistentChatClient_Ask_Call) Run(run func(ctx context.Context, question string, target any)) *MockPersistentChatClient_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPersistentChatClient_Ask_Call) Return(err error) *MockPersistentChatClient_Ask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistentChatClient_Ask_Call) RunAndReturn(run func(ctx context.Context, question string, target any) error) *MockPersistentChatClient_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function for the type MockPersistentChatClient
func (_mock *MockPersistentChatClient) Chat(ctx context.Context, prompt string) (string, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersistentChatClient_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockPersistentChatClient_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockPersistentChatClient_Expecter) Chat(ctx interface{}, prompt interface{}) *MockPersistentChatClient_Chat_Call {
	return &MockPersistentChatClient_Chat_Call{Call: _e.mock.On("Chat", ctx, prompt)}
}

func (_c *MockPersistentChatClient_Chat_Call) Run(run func(ctx context.Context, prompt string)) *MockPersistentChatClient_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersistentChatClient_Chat_Call) Return(s string, err error) *MockPersistentChatClient_Chat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPersistentChatClient_Chat_Call) RunAndReturn(run func(ctx context.Context, prompt string) (string, error)) *MockPersistentChatClient_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockPersistentChatClient
func (_mock *MockPersistentChatClient) Restore(snapshot *chat.Snapshot) error {
	ret := _mock.Called(snapshot)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*chat.Snapshot) error); ok {
		r0 = returnFunc(snapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistentChatClient_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockPersistentChatClient_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - snapshot *chat.Snapshot
func (_e *MockPersistentChatClient_Expecter) Restore(snapshot interface{}) *MockPersistentChatClient_Restore_Call {
	return &MockPersistentChatClient_Restore_Call{Call: _e.mock.On("Restore", snapshot)}
}

func (_c *MockPersistentChatClient_Restore_Call) Run(run func(snapshot *chat.Snapshot)) *MockPersistentChatClient_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *chat.Snapshot
		if args[0] != nil {
			arg0 = args[0].(*chat.Snapshot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPersistentChatClient_Restore_Call) Return(err error) *MockPersistentChatClient_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistentChatClient_Restore_Call) RunAndReturn(run func(snapshot *chat.Snapshot) error) *MockPersistentChatClient_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPersistentChatClient
func (_mock *MockPersistentChatClient) Save() (*chat.Snapshot, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *chat.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*chat.Snapshot, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *chat.Snapshot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersistentChatClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPersistentChatClient_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
func (_e *MockPersistentChatClient_Expecter) Save() *MockPersistentChatClient_Save_Call {
	return &MockPersistentChatClient_Save_Call{Call: _e.mock.On("Save")}
}

func (_c *MockPersistentChatClient_Save_Call) Run(run func()) *MockPersistentChatClient_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPersistentChatClient_Save_Call) Return(snapshot *chat.Snapshot, err error) *MockPersistentChatClient_Save_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockPersistentChatClient_Save_Call) RunAndReturn(run func() (*chat.Snapshot, error)) *MockPersistentChatClient_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetTools provides a mock function for the type MockPersistentChatClient
func (_mock *MockPersistentChatClient) SetTools(tools []chat.Tool) error {
	ret := _mock.Called(tools)

	if len(ret) == 0 {
		panic("no return value specified for SetTools")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]chat.Tool) error); ok {
		r0 = returnFunc(tools)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistentChatClient_SetTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTools'
type MockPersistentChatClient_SetTools_Call struct {
	*mock.Call
}

// SetTools is a helper method to define mock.On call
//   - tools []chat.Tool
func (_e *MockPersistentChatClient_Expecter) SetTools(tools interface{}) *MockPersistentChatClient_SetTools_Call {
	return &MockPersistentChatClient_SetTools_Call{Call: _e.mock.On("SetTools", tools)}
}

func (_c *MockPersistentChatClient_SetTools_Call) Run(run func(tools []chat.Tool)) *MockPersistentChatClient_SetTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []chat.Tool
		if args[0] != nil {
			arg0 = args[0].([]chat.Tool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPersistentChatClient_SetTools_Call) Return(err error) *MockPersistentChatClient_SetTools_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistentChatClient_SetTools_Call) RunAndReturn(run func(tools []chat.Tool) error) *MockPersistentChatClient_SetTools_Call {
	_c.Call.Return(run)
	return _c
}
