// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	gochat "gitlab.com/phpboyscout/go/chat"
)

// NewMockStreamingChatClient creates a new instance of MockStreamingChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamingChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamingChatClient {
	mock := &MockStreamingChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamingChatClient is an autogenerated mock type for the StreamingChatClient type
type MockStreamingChatClient struct {
	mock.Mock
}

type MockStreamingChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamingChatClient) EXPECT() *MockStreamingChatClient_Expecter {
	return &MockStreamingChatClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Add(ctx context.Context, prompt string, media ...gochat.Media) error {
	var tmpRet mock.Arguments
	if len(media) > 0 {
		tmpRet = _mock.Called(ctx, prompt, media)
	} else {
		tmpRet = _mock.Called(ctx, prompt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...gochat.Media) error); ok {
		r0 = returnFunc(ctx, prompt, media...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingChatClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockStreamingChatClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - media ...gochat.Media
func (_e *MockStreamingChatClient_Expecter) Add(ctx interface{}, prompt interface{}, media ...interface{}) *MockStreamingChatClient_Add_Call {
	return &MockStreamingChatClient_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx, prompt}, media...)...)}
}

func (_c *MockStreamingChatClient_Add_Call) Run(run func(ctx context.Context, prompt string, media ...gochat.Media)) *MockStreamingChatClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []gochat.Media
		var variadicArgs []gochat.Media
		if len(args) > 2 {
			variadicArgs = args[2].([]gochat.Media)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_Add_Call) Return(err error) *MockStreamingChatClient_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingChatClient_Add_Call) RunAndReturn(run func(ctx context.Context, prompt string, media ...gochat.Media) error) *MockStreamingChatClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Ask provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Ask(ctx context.Context, question string, target any, media ...gochat.Media) error {
	var tmpRet mock.Arguments
	if len(media) > 0 {
		tmpRet = _mock.Called(ctx, question, target, media)
	} else {
		tmpRet = _mock.Called(ctx, question, target)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...gochat.Media) error); ok {
		r0 = returnFunc(ctx, question, target, media...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingChatClient_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type MockStreamingChatClient_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
//   - target any
//   - media ...gochat.Media
func (_e *MockStreamingChatClient_Expecter) Ask(ctx interface{}, question interface{}, target interface{}, media ...interface{}) *MockStreamingChatClient_Ask_Call {
	return &MockStreamingChatClient_Ask_Call{Call: _e.mock.On("Ask",
		append([]interface{}{ctx, question, target}, media...)...)}
}

func (_c *MockStreamingChatClient_Ask_Call) Run(run func(ctx context.Context, question string, target any, media ...gochat.Media)) *MockStreamingChatClient_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []gochat.Media
		var variadicArgs []gochat.Media
		if len(args) > 3 {
			variadicArgs = args[3].([]gochat.Media)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_Ask_Call) Return(err error) *MockStreamingChatClient_Ask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingChatClient_Ask_Call) RunAndReturn(run func(ctx context.Context, question string, target any, media ...gochat.Media) error) *MockStreamingChatClient_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Chat(ctx context.Context, prompt string, media ...gochat.Media) (string, error) {
	var tmpRet mock.Arguments
	if len(media) > 0 {
		tmpRet = _mock.Called(ctx, prompt, media)
	} else {
		tmpRet = _mock.Called(ctx, prompt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...gochat.Media) (string, error)); ok {
		return returnFunc(ctx, prompt, media...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...gochat.Media) string); ok {
		r0 = returnFunc(ctx, prompt, media...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...gochat.Media) error); ok {
		r1 = returnFunc(ctx, prompt, media...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamingChatClient_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockStreamingChatClient_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - media ...gochat.Media
func (_e *MockStreamingChatClient_Expecter) Chat(ctx interface{}, prompt interface{}, media ...interface{}) *MockStreamingChatClient_Chat_Call {
	return &MockStreamingChatClient_Chat_Call{Call: _e.mock.On("Chat",
		append([]interface{}{ctx, prompt}, media...)...)}
}

func (_c *MockStreamingChatClient_Chat_Call) Run(run func(ctx context.Context, prompt string, media ...gochat.Media)) *MockStreamingChatClient_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []gochat.Media
		var variadicArgs []gochat.Media
		if len(args) > 2 {
			variadicArgs = args[2].([]gochat.Media)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_Chat_Call) Return(s string, err error) *MockStreamingChatClient_Chat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStreamingChatClient_Chat_Call) RunAndReturn(run func(ctx context.Context, prompt string, media ...gochat.Media) (string, error)) *MockStreamingChatClient_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// SetTools provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) SetTools(tools []gochat.Tool) error {
	ret := _mock.Called(tools)

	if len(ret) == 0 {
		panic("no return value specified for SetTools")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]gochat.Tool) error); ok {
		r0 = returnFunc(tools)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingChatClient_SetTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTools'
type MockStreamingChatClient_SetTools_Call struct {
	*mock.Call
}

// SetTools is a helper method to define mock.On call
//   - tools []gochat.Tool
func (_e *MockStreamingChatClient_Expecter) SetTools(tools interface{}) *MockStreamingChatClient_SetTools_Call {
	return &MockStreamingChatClient_SetTools_Call{Call: _e.mock.On("SetTools", tools)}
}

func (_c *MockStreamingChatClient_SetTools_Call) Run(run func(tools []gochat.Tool)) *MockStreamingChatClient_SetTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []gochat.Tool
		if args[0] != nil {
			arg0 = args[0].([]gochat.Tool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_SetTools_Call) Return(err error) *MockStreamingChatClient_SetTools_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingChatClient_SetTools_Call) RunAndReturn(run func(tools []gochat.Tool) error) *MockStreamingChatClient_SetTools_Call {
	_c.Call.Return(run)
	return _c
}

// StreamChat provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) StreamChat(ctx context.Context, prompt string, callback gochat.StreamCallback, media ...gochat.Media) (string, error) {
	var tmpRet mock.Arguments
	if len(media) > 0 {
		tmpRet = _mock.Called(ctx, prompt, callback, media)
	} else {
		tmpRet = _mock.Called(ctx, prompt, callback)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StreamChat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, gochat.StreamCallback, ...gochat.Media) (string, error)); ok {
		return returnFunc(ctx, prompt, callback, media...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, gochat.StreamCallback, ...gochat.Media) string); ok {
		r0 = returnFunc(ctx, prompt, callback, media...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, gochat.StreamCallback, ...gochat.Media) error); ok {
		r1 = returnFunc(ctx, prompt, callback, media...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamingChatClient_StreamChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamChat'
type MockStreamingChatClient_StreamChat_Call struct {
	*mock.Call
}

// StreamChat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - callback gochat.StreamCallback
//   - media ...gochat.Media
func (_e *MockStreamingChatClient_Expecter) StreamChat(ctx interface{}, prompt interface{}, callback interface{}, media ...interface{}) *MockStreamingChatClient_StreamChat_Call {
	return &MockStreamingChatClient_StreamChat_Call{Call: _e.mock.On("StreamChat",
		append([]interface{}{ctx, prompt, callback}, media...)...)}
}

func (_c *MockStreamingChatClient_StreamChat_Call) Run(run func(ctx context.Context, prompt string, callback gochat.StreamCallback, media ...gochat.Media)) *MockStreamingChatClient_StreamChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 gochat.StreamCallback
		if args[2] != nil {
			arg2 = args[2].(gochat.StreamCallback)
		}
		var arg3 []gochat.Media
		var variadicArgs []gochat.Media
		if len(args) > 3 {
			variadicArgs = args[3].([]gochat.Media)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_StreamChat_Call) Return(s string, err error) *MockStreamingChatClient_StreamChat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStreamingChatClient_StreamChat_Call) RunAndReturn(run func(ctx context.Context, prompt string, callback gochat.StreamCallback, media ...gochat.Media) (string, error)) *MockStreamingChatClient_StreamChat_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Usage() gochat.Usage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 gochat.Usage
	if returnFunc, ok := ret.Get(0).(func() gochat.Usage); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gochat.Usage)
	}
	return r0
}

// MockStreamingChatClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockStreamingChatClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
func (_e *MockStreamingChatClient_Expecter) Usage() *MockStreamingChatClient_Usage_Call {
	return &MockStreamingChatClient_Usage_Call{Call: _e.mock.On("Usage")}
}

func (_c *MockStreamingChatClient_Usage_Call) Run(run func()) *MockStreamingChatClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingChatClient_Usage_Call) Return(usage gochat.Usage) *MockStreamingChatClient_Usage_Call {
	_c.Call.Return(usage)
	return _c
}

func (_c *MockStreamingChatClient_Usage_Call) RunAndReturn(run func() gochat.Usage) *MockStreamingChatClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
