// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/chat"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStreamingChatClient creates a new instance of MockStreamingChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamingChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamingChatClient {
	mock := &MockStreamingChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamingChatClient is an autogenerated mock type for the StreamingChatClient type
type MockStreamingChatClient struct {
	mock.Mock
}

type MockStreamingChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamingChatClient) EXPECT() *MockStreamingChatClient_Expecter {
	return &MockStreamingChatClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Add(ctx context.Context, prompt string) error {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingChatClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockStreamingChatClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockStreamingChatClient_Expecter) Add(ctx interface{}, prompt interface{}) *MockStreamingChatClient_Add_Call {
	return &MockStreamingChatClient_Add_Call{Call: _e.mock.On("Add", ctx, prompt)}
}

func (_c *MockStreamingChatClient_Add_Call) Run(run func(ctx context.Context, prompt string)) *MockStreamingChatClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_Add_Call) Return(err error) *MockStreamingChatClient_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingChatClient_Add_Call) RunAndReturn(run func(ctx context.Context, prompt string) error) *MockStreamingChatClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Ask provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Ask(ctx context.Context, question string, target any) error {
	ret := _mock.Called(ctx, question, target)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, question, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingChatClient_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type MockStreamingChatClient_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
//   - target any
func (_e *MockStreamingChatClient_Expecter) Ask(ctx interface{}, question interface{}, target interface{}) *MockStreamingChatClient_Ask_Call {
	return &MockStreamingChatClient_Ask_Call{Call: _e.mock.On("Ask", ctx, question, target)}
}

func (_c *MockStreamingChatClient_Ask_Call) Run(run func(ctx context.Context, question string, target any)) *MockStreamingChatClient_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_Ask_Call) Return(err error) *MockStreamingChatClient_Ask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingChatClient_Ask_Call) RunAndReturn(run func(ctx context.Context, question string, target any) error) *MockStreamingChatClient_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) Chat(ctx context.Context, prompt string) (string, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamingChatClient_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockStreamingChatClient_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockStreamingChatClient_Expecter) Chat(ctx interface{}, prompt interface{}) *MockStreamingChatClient_Chat_Call {
	return &MockStreamingChatClient_Chat_Call{Call: _e.mock.On("Chat", ctx, prompt)}
}

func (_c *MockStreamingChatClient_Chat_Call) Run(run func(ctx context.Context, prompt string)) *MockStreamingChatClient_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_Chat_Call) Return(s string, err error) *MockStreamingChatClient_Chat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStreamingChatClient_Chat_Call) RunAndReturn(run func(ctx context.Context, prompt string) (string, error)) *MockStreamingChatClient_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// SetTools provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) SetTools(tools []chat.Tool) error {
	ret := _mock.Called(tools)

	if len(ret) == 0 {
		panic("no return value specified for SetTools")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]chat.Tool) error); ok {
		r0 = returnFunc(tools)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingChatClient_SetTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTools'
type MockStreamingChatClient_SetTools_Call struct {
	*mock.Call
}

// SetTools is a helper method to define mock.On call
//   - tools []chat.Tool
func (_e *MockStreamingChatClient_Expecter) SetTools(tools interface{}) *MockStreamingChatClient_SetTools_Call {
	return &MockStreamingChatClient_SetTools_Call{Call: _e.mock.On("SetTools", tools)}
}

func (_c *MockStreamingChatClient_SetTools_Call) Run(run func(tools []chat.Tool)) *MockStreamingChatClient_SetTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []chat.Tool
		if args[0] != nil {
			arg0 = args[0].([]chat.Tool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_SetTools_Call) Return(err error) *MockStreamingChatClient_SetTools_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingChatClient_SetTools_Call) RunAndReturn(run func(tools []chat.Tool) error) *MockStreamingChatClient_SetTools_Call {
	_c.Call.Return(run)
	return _c
}

// StreamChat provides a mock function for the type MockStreamingChatClient
func (_mock *MockStreamingChatClient) StreamChat(ctx context.Context, prompt string, callback chat.StreamCallback) (string, error) {
	ret := _mock.Called(ctx, prompt, callback)

	if len(ret) == 0 {
		panic("no return value specified for StreamChat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, chat.StreamCallback) (string, error)); ok {
		return returnFunc(ctx, prompt, callback)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, chat.StreamCallback) string); ok {
		r0 = returnFunc(ctx, prompt, callback)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, chat.StreamCallback) error); ok {
		r1 = returnFunc(ctx, prompt, callback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamingChatClient_StreamChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamChat'
type MockStreamingChatClient_StreamChat_Call struct {
	*mock.Call
}

// StreamChat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - callback chat.StreamCallback
func (_e *MockStreamingChatClient_Expecter) StreamChat(ctx interface{}, prompt interface{}, callback interface{}) *MockStreamingChatClient_StreamChat_Call {
	return &MockStreamingChatClient_StreamChat_Call{Call: _e.mock.On("StreamChat", ctx, prompt, callback)}
}

func (_c *MockStreamingChatClient_StreamChat_Call) Run(run func(ctx context.Context, prompt string, callback chat.StreamCallback)) *MockStreamingChatClient_StreamChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 chat.StreamCallback
		if args[2] != nil {
			arg2 = args[2].(chat.StreamCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStreamingChatClient_StreamChat_Call) Return(s string, err error) *MockStreamingChatClient_StreamChat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStreamingChatClient_StreamChat_Call) RunAndReturn(run func(ctx context.Context, prompt string, callback chat.StreamCallback) (string, error)) *MockStreamingChatClient_StreamChat_Call {
	_c.Call.Return(run)
	return _c
}
