@cli @man
Feature: CLI Man Command
  The hidden, opt-in `man` command emits roff man pages for the tool's own
  command tree — to stdout for preview, or to a directory tree for packaging.
  It is gated behind the default-off ManCmd feature (enabled in the e2e binary).

  Background:
    Given the gtb binary is built
    # The keys scratch dir doubles as a generic output directory here.
    And a temporary keys directory

  @smoke
  Scenario: man without --dir prints the tool's roff page to stdout
    When I run gtb with "man"
    Then the exit code is 0
    And stdout contains ".TH"
    And stdout contains "GTB"
    And stdout does not contain "Auto generated by spf13/cobra"

  Scenario: man --dir writes a roff page tree
    When I run gtb with "man --dir {keys_dir}"
    Then the exit code is 0
    And the file "man1/gtb.1" exists in the keys directory
    And the file "man1/gtb.1" in the keys directory contains "gtb"

  Scenario: generate man writes the page tree under man1/
    When I run gtb with "generate man --dir {keys_dir}"
    Then the exit code is 0
    And stdout contains "wrote man pages"
    And the file "man1/gtb.1" exists in the keys directory
