// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"github.com/phpboyscout/go-tool-base/pkg/controls"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthCheckReporter creates a new instance of MockHealthCheckReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckReporter {
	mock := &MockHealthCheckReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthCheckReporter is an autogenerated mock type for the HealthCheckReporter type
type MockHealthCheckReporter struct {
	mock.Mock
}

type MockHealthCheckReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckReporter) EXPECT() *MockHealthCheckReporter_Expecter {
	return &MockHealthCheckReporter_Expecter{mock: &_m.Mock}
}

// GetCheckResult provides a mock function for the type MockHealthCheckReporter
func (_mock *MockHealthCheckReporter) GetCheckResult(name string) (controls.CheckResult, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckResult")
	}

	var r0 controls.CheckResult
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (controls.CheckResult, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) controls.CheckResult); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(controls.CheckResult)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthCheckReporter_GetCheckResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckResult'
type MockHealthCheckReporter_GetCheckResult_Call struct {
	*mock.Call
}

// GetCheckResult is a helper method to define mock.On call
//   - name string
func (_e *MockHealthCheckReporter_Expecter) GetCheckResult(name interface{}) *MockHealthCheckReporter_GetCheckResult_Call {
	return &MockHealthCheckReporter_GetCheckResult_Call{Call: _e.mock.On("GetCheckResult", name)}
}

func (_c *MockHealthCheckReporter_GetCheckResult_Call) Run(run func(name string)) *MockHealthCheckReporter_GetCheckResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheckReporter_GetCheckResult_Call) Return(checkResult controls.CheckResult, b bool) *MockHealthCheckReporter_GetCheckResult_Call {
	_c.Call.Return(checkResult, b)
	return _c
}

func (_c *MockHealthCheckReporter_GetCheckResult_Call) RunAndReturn(run func(name string) (controls.CheckResult, bool)) *MockHealthCheckReporter_GetCheckResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceInfo provides a mock function for the type MockHealthCheckReporter
func (_mock *MockHealthCheckReporter) GetServiceInfo(name string) (controls.ServiceInfo, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceInfo")
	}

	var r0 controls.ServiceInfo
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (controls.ServiceInfo, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) controls.ServiceInfo); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(controls.ServiceInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthCheckReporter_GetServiceInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceInfo'
type MockHealthCheckReporter_GetServiceInfo_Call struct {
	*mock.Call
}

// GetServiceInfo is a helper method to define mock.On call
//   - name string
func (_e *MockHealthCheckReporter_Expecter) GetServiceInfo(name interface{}) *MockHealthCheckReporter_GetServiceInfo_Call {
	return &MockHealthCheckReporter_GetServiceInfo_Call{Call: _e.mock.On("GetServiceInfo", name)}
}

func (_c *MockHealthCheckReporter_GetServiceInfo_Call) Run(run func(name string)) *MockHealthCheckReporter_GetServiceInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheckReporter_GetServiceInfo_Call) Return(serviceInfo controls.ServiceInfo, b bool) *MockHealthCheckReporter_GetServiceInfo_Call {
	_c.Call.Return(serviceInfo, b)
	return _c
}

func (_c *MockHealthCheckReporter_GetServiceInfo_Call) RunAndReturn(run func(name string) (controls.ServiceInfo, bool)) *MockHealthCheckReporter_GetServiceInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Liveness provides a mock function for the type MockHealthCheckReporter
func (_mock *MockHealthCheckReporter) Liveness() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Liveness")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// MockHealthCheckReporter_Liveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Liveness'
type MockHealthCheckReporter_Liveness_Call struct {
	*mock.Call
}

// Liveness is a helper method to define mock.On call
func (_e *MockHealthCheckReporter_Expecter) Liveness() *MockHealthCheckReporter_Liveness_Call {
	return &MockHealthCheckReporter_Liveness_Call{Call: _e.mock.On("Liveness")}
}

func (_c *MockHealthCheckReporter_Liveness_Call) Run(run func()) *MockHealthCheckReporter_Liveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckReporter_Liveness_Call) Return(healthReport controls.HealthReport) *MockHealthCheckReporter_Liveness_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *MockHealthCheckReporter_Liveness_Call) RunAndReturn(run func() controls.HealthReport) *MockHealthCheckReporter_Liveness_Call {
	_c.Call.Return(run)
	return _c
}

// Readiness provides a mock function for the type MockHealthCheckReporter
func (_mock *MockHealthCheckReporter) Readiness() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Readiness")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// MockHealthCheckReporter_Readiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readiness'
type MockHealthCheckReporter_Readiness_Call struct {
	*mock.Call
}

// Readiness is a helper method to define mock.On call
func (_e *MockHealthCheckReporter_Expecter) Readiness() *MockHealthCheckReporter_Readiness_Call {
	return &MockHealthCheckReporter_Readiness_Call{Call: _e.mock.On("Readiness")}
}

func (_c *MockHealthCheckReporter_Readiness_Call) Run(run func()) *MockHealthCheckReporter_Readiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckReporter_Readiness_Call) Return(healthReport controls.HealthReport) *MockHealthCheckReporter_Readiness_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *MockHealthCheckReporter_Readiness_Call) RunAndReturn(run func() controls.HealthReport) *MockHealthCheckReporter_Readiness_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockHealthCheckReporter
func (_mock *MockHealthCheckReporter) Status() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// MockHealthCheckReporter_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockHealthCheckReporter_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockHealthCheckReporter_Expecter) Status() *MockHealthCheckReporter_Status_Call {
	return &MockHealthCheckReporter_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockHealthCheckReporter_Status_Call) Run(run func()) *MockHealthCheckReporter_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckReporter_Status_Call) Return(healthReport controls.HealthReport) *MockHealthCheckReporter_Status_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *MockHealthCheckReporter_Status_Call) RunAndReturn(run func() controls.HealthReport) *MockHealthCheckReporter_Status_Call {
	_c.Call.Return(run)
	return _c
}
