// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/controls"
)

// newMockvalidErrorSetter creates a new instance of mockvalidErrorSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockvalidErrorSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockvalidErrorSetter {
	mock := &mockvalidErrorSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockvalidErrorSetter is an autogenerated mock type for the validErrorSetter type
type mockvalidErrorSetter struct {
	mock.Mock
}

type mockvalidErrorSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockvalidErrorSetter) EXPECT() *mockvalidErrorSetter_Expecter {
	return &mockvalidErrorSetter_Expecter{mock: &_m.Mock}
}

// setValidError provides a mock function for the type mockvalidErrorSetter
func (_mock *mockvalidErrorSetter) setValidError(fn controls.ValidErrorFunc) {
	_mock.Called(fn)
	return
}

// mockvalidErrorSetter_setValidError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setValidError'
type mockvalidErrorSetter_setValidError_Call struct {
	*mock.Call
}

// setValidError is a helper method to define mock.On call
//   - fn controls.ValidErrorFunc
func (_e *mockvalidErrorSetter_Expecter) setValidError(fn interface{}) *mockvalidErrorSetter_setValidError_Call {
	return &mockvalidErrorSetter_setValidError_Call{Call: _e.mock.On("setValidError", fn)}
}

func (_c *mockvalidErrorSetter_setValidError_Call) Run(run func(fn controls.ValidErrorFunc)) *mockvalidErrorSetter_setValidError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 controls.ValidErrorFunc
		if args[0] != nil {
			arg0 = args[0].(controls.ValidErrorFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockvalidErrorSetter_setValidError_Call) Return() *mockvalidErrorSetter_setValidError_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockvalidErrorSetter_setValidError_Call) RunAndReturn(run func(fn controls.ValidErrorFunc)) *mockvalidErrorSetter_setValidError_Call {
	_c.Run(run)
	return _c
}
