// Package openpgpkey mints an ASCII-armored OpenPGP public key from a
// crypto.Signer. It exists to bridge a KMS/HSM-held signing key (which
// exposes only a public key plus a remote Sign operation) into the
// OpenPGP form that the self-update verifier (pkg/setup) and Web Key
// Directory require.
//
// Why this is needed: the verifier rejects a bare public-key packet
// ("v4 entity without any identities") — it needs a User ID and a
// self-signature. Producing that self-signature requires *signing* with
// the private key. go-crypto signs RSA and Ed25519 keys through the
// crypto.Signer interface, so an opaque KMS-backed signer works without
// the private key ever leaving the KMS.
//
// Supported key algorithms:
//
//   - RSA (any *rsa.PublicKey from Public()). Used for the primary
//     signing key path, where AWS KMS only exposes asymmetric
//     SIGN_VERIFY keys as RSA.
//   - Ed25519 (any ed25519.PublicKey from Public()). Used for the
//     rotation-authority key path generated by `gtb keys generate`.
//
// Other key types (ECDSA, DSA, etc.) return ErrUnsupportedKeyType.
//
// Ed25519 keys are emitted as RFC 9580 (OpenPGP v6) Ed25519-native
// public-key packets. Verification requires a recent GnuPG (≥ 2.4) or
// any RFC 9580-aware OpenPGP implementation. Older verifiers that
// only understand the legacy v4 EdDSA framing will reject the key.
// See docs/components/openpgpkey.md.
package openpgpkey

import (
	"bytes"
	"crypto"
	"crypto/ed25519"
	"crypto/rsa"
	"io"
	"time"

	"github.com/ProtonMail/go-crypto/openpgp"
	"github.com/ProtonMail/go-crypto/openpgp/armor"
	pgped25519 "github.com/ProtonMail/go-crypto/openpgp/ed25519"
	"github.com/ProtonMail/go-crypto/openpgp/packet"
	"github.com/cockroachdb/errors"
)

// ErrUnsupportedKeyType is returned by ArmoredPublicKey when the
// signer's Public() returns a key type this package does not handle.
// Supported types are *rsa.PublicKey and ed25519.PublicKey; any other
// concrete type produces this error.
var ErrUnsupportedKeyType = errors.New("unsupported key type: only RSA and Ed25519 are supported")

// ArmoredPublicKey builds a self-signed OpenPGP key from signer and
// returns its ASCII-armored *public* half — ready to embed
// (internal/trustkeys/keys) or publish via WKD. creationTime is baked
// into the key and its self-signature; keep it stable (rotations get a
// new key, not a new timestamp on the same key).
func ArmoredPublicKey(signer crypto.Signer, name, email string, creationTime time.Time) ([]byte, error) {
	var buf bytes.Buffer

	if err := WriteArmoredPublicKey(&buf, signer, name, email, creationTime); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// WriteArmoredPublicKey writes the same content as ArmoredPublicKey
// directly to w. The two-function shape exists so callers that want
// to stream into a file or socket can skip the intermediate buffer;
// it also lets the test suite inject a failing writer to exercise
// the error-wrapping branches around armor.Encode / Close.
func WriteArmoredPublicKey(w io.Writer, signer crypto.Signer, name, email string, creationTime time.Time) error {
	ent, err := entity(signer, name, email, creationTime)
	if err != nil {
		return err
	}

	enc, err := armor.Encode(w, openpgp.PublicKeyType, nil)
	if err != nil {
		return errors.WithStack(err)
	}

	// Entity.Serialize writes the public half (key + UID + self-sig);
	// SerializePrivate would be needed for the secret key.
	if err := ent.Serialize(enc); err != nil {
		return errors.Wrap(err, "serializing public key")
	}

	if err := enc.Close(); err != nil {
		return errors.WithStack(err)
	}

	return nil
}

// entity assembles a self-signed, signing-capable OpenPGP entity
// around signer: a public-key packet + a private-key packet matching
// the signer's algorithm, a User ID, and a positive-cert self-
// signature produced at AddUserId time.
//
// The RSA path supports opaque signers (any crypto.Signer with
// *rsa.PublicKey from Public()) — go-crypto's RSA signing path
// dispatches via the crypto.Signer interface, so a KMS-backed signer
// works.
//
// The Ed25519 path requires a concrete stdlib ed25519.PrivateKey —
// go-crypto's v6 Ed25519 signing path dispatches by concrete type
// and reads the seed bytes directly. Opaque Ed25519 signers (e.g. a
// hypothetical Ed25519-capable KMS) are not supported in v0.1. AWS
// KMS does not expose Ed25519, so this does not block any current
// use case.
func entity(signer crypto.Signer, name, email string, creationTime time.Time) (*openpgp.Entity, error) {
	pubKey, privKey, err := keyPackets(signer, creationTime)
	if err != nil {
		return nil, err
	}

	ent := &openpgp.Entity{
		PrimaryKey: pubKey,
		PrivateKey: privKey,
		Identities: make(map[string]*openpgp.Identity),
		Subkeys:    []openpgp.Subkey{},
		Signatures: []*packet.Signature{},
	}

	cfg := &packet.Config{Time: func() time.Time { return creationTime }}

	// AddUserId attaches the User ID and signs the binding self-
	// signature with ent.PrivateKey, marking the key sign+certify
	// capable.
	if err := ent.AddUserId(name, "", email, cfg); err != nil {
		return nil, errors.Wrap(err, "adding user id / self-signature")
	}

	return ent, nil
}

// keyPackets builds the public+private OpenPGP packets for signer.
// Dispatches by the concrete type of signer.Public(); for Ed25519,
// also requires signer itself to be a concrete ed25519.PrivateKey
// (see entity's doc for why).
func keyPackets(signer crypto.Signer, creationTime time.Time) (*packet.PublicKey, *packet.PrivateKey, error) {
	switch pub := signer.Public().(type) {
	case *rsa.PublicKey:
		pubPkt := packet.NewRSAPublicKey(creationTime, pub)
		// Construct the private-key packet directly (rather than
		// packet.NewSignerPrivateKey, which panics on opaque
		// signers): the crypto.Signer drives the actual signing,
		// so a KMS-backed signer works here.
		privPkt := &packet.PrivateKey{PublicKey: *pubPkt, PrivateKey: signer}

		return pubPkt, privPkt, nil

	case ed25519.PublicKey:
		concrete, ok := signer.(ed25519.PrivateKey)
		if !ok {
			return nil, nil, errors.Wrap(ErrUnsupportedKeyType,
				"Ed25519 minting requires a concrete stdlib ed25519.PrivateKey; opaque signers (HSM/KMS) are not supported for Ed25519 in v0.1")
		}

		// Adapt the stdlib Ed25519 key into go-crypto's internal
		// representation (which the v6 packet path requires).
		// stdlib ed25519.PrivateKey is 64 bytes: seed[32] || pub[32].
		// go-crypto's ed25519.PrivateKey.Key uses the same layout
		// (RFC 8032 "seed | pub key point"), so we copy verbatim.
		pgpPub := pgped25519.NewPublicKey()
		pgpPub.Point = append([]byte(nil), pub...)

		pgpPriv := pgped25519.NewPrivateKey(*pgpPub)
		pgpPriv.Key = append([]byte(nil), concrete...)

		pubPkt := packet.NewEd25519PublicKey(creationTime, pgpPub)
		privPkt := packet.NewEd25519PrivateKey(creationTime, pgpPriv)

		return pubPkt, privPkt, nil

	default:
		return nil, nil, errors.Wrapf(ErrUnsupportedKeyType, "got %T", pub)
	}
}
