// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package credtest

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocktestingT creates a new instance of mocktestingT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktestingT(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktestingT {
	mock := &mocktestingT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktestingT is an autogenerated mock type for the testingT type
type mocktestingT struct {
	mock.Mock
}

type mocktestingT_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktestingT) EXPECT() *mocktestingT_Expecter {
	return &mocktestingT_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type mocktestingT
func (_mock *mocktestingT) Cleanup(fn func()) {
	_mock.Called(fn)
	return
}

// mocktestingT_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type mocktestingT_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - fn func()
func (_e *mocktestingT_Expecter) Cleanup(fn interface{}) *mocktestingT_Cleanup_Call {
	return &mocktestingT_Cleanup_Call{Call: _e.mock.On("Cleanup", fn)}
}

func (_c *mocktestingT_Cleanup_Call) Run(run func(fn func())) *mocktestingT_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktestingT_Cleanup_Call) Return() *mocktestingT_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocktestingT_Cleanup_Call) RunAndReturn(run func(fn func())) *mocktestingT_Cleanup_Call {
	_c.Run(run)
	return _c
}

// Helper provides a mock function for the type mocktestingT
func (_mock *mocktestingT) Helper() {
	_mock.Called()
	return
}

// mocktestingT_Helper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Helper'
type mocktestingT_Helper_Call struct {
	*mock.Call
}

// Helper is a helper method to define mock.On call
func (_e *mocktestingT_Expecter) Helper() *mocktestingT_Helper_Call {
	return &mocktestingT_Helper_Call{Call: _e.mock.On("Helper")}
}

func (_c *mocktestingT_Helper_Call) Run(run func()) *mocktestingT_Helper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocktestingT_Helper_Call) Return() *mocktestingT_Helper_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocktestingT_Helper_Call) RunAndReturn(run func()) *mocktestingT_Helper_Call {
	_c.Run(run)
	return _c
}
