// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package credentials

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Available provides a mock function for the type MockBackend
func (_mock *MockBackend) Available() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Available")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBackend_Available_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Available'
type MockBackend_Available_Call struct {
	*mock.Call
}

// Available is a helper method to define mock.On call
func (_e *MockBackend_Expecter) Available() *MockBackend_Available_Call {
	return &MockBackend_Available_Call{Call: _e.mock.On("Available")}
}

func (_c *MockBackend_Available_Call) Run(run func()) *MockBackend_Available_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_Available_Call) Return(b bool) *MockBackend_Available_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBackend_Available_Call) RunAndReturn(run func() bool) *MockBackend_Available_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBackend
func (_mock *MockBackend) Delete(ctx context.Context, service string, account string) error {
	ret := _mock.Called(ctx, service, account)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, service, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - account string
func (_e *MockBackend_Expecter) Delete(ctx interface{}, service interface{}, account interface{}) *MockBackend_Delete_Call {
	return &MockBackend_Delete_Call{Call: _e.mock.On("Delete", ctx, service, account)}
}

func (_c *MockBackend_Delete_Call) Run(run func(ctx context.Context, service string, account string)) *MockBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_Delete_Call) Return(err error) *MockBackend_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_Delete_Call) RunAndReturn(run func(ctx context.Context, service string, account string) error) *MockBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockBackend
func (_mock *MockBackend) Retrieve(ctx context.Context, service string, account string) (string, error) {
	ret := _mock.Called(ctx, service, account)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, service, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, service, account)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, service, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockBackend_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - account string
func (_e *MockBackend_Expecter) Retrieve(ctx interface{}, service interface{}, account interface{}) *MockBackend_Retrieve_Call {
	return &MockBackend_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, service, account)}
}

func (_c *MockBackend_Retrieve_Call) Run(run func(ctx context.Context, service string, account string)) *MockBackend_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_Retrieve_Call) Return(s string, err error) *MockBackend_Retrieve_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBackend_Retrieve_Call) RunAndReturn(run func(ctx context.Context, service string, account string) (string, error)) *MockBackend_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockBackend
func (_mock *MockBackend) Store(ctx context.Context, service string, account string, secret string) error {
	ret := _mock.Called(ctx, service, account, secret)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, service, account, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockBackend_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - account string
//   - secret string
func (_e *MockBackend_Expecter) Store(ctx interface{}, service interface{}, account interface{}, secret interface{}) *MockBackend_Store_Call {
	return &MockBackend_Store_Call{Call: _e.mock.On("Store", ctx, service, account, secret)}
}

func (_c *MockBackend_Store_Call) Run(run func(ctx context.Context, service string, account string, secret string)) *MockBackend_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_Store_Call) Return(err error) *MockBackend_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_Store_Call) RunAndReturn(run func(ctx context.Context, service string, account string, secret string) error) *MockBackend_Store_Call {
	_c.Call.Return(run)
	return _c
}
