// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authn

import (
	"context"
	"crypto/x509"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/authn"
)

// NewMockCertVerifier creates a new instance of MockCertVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertVerifier {
	mock := &MockCertVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCertVerifier is an autogenerated mock type for the CertVerifier type
type MockCertVerifier struct {
	mock.Mock
}

type MockCertVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertVerifier) EXPECT() *MockCertVerifier_Expecter {
	return &MockCertVerifier_Expecter{mock: &_m.Mock}
}

// VerifyCert provides a mock function for the type MockCertVerifier
func (_mock *MockCertVerifier) VerifyCert(ctx context.Context, verifiedChains [][]*x509.Certificate) (*authn.Identity, error) {
	ret := _mock.Called(ctx, verifiedChains)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCert")
	}

	var r0 *authn.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, [][]*x509.Certificate) (*authn.Identity, error)); ok {
		return returnFunc(ctx, verifiedChains)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, [][]*x509.Certificate) *authn.Identity); ok {
		r0 = returnFunc(ctx, verifiedChains)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authn.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, [][]*x509.Certificate) error); ok {
		r1 = returnFunc(ctx, verifiedChains)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertVerifier_VerifyCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCert'
type MockCertVerifier_VerifyCert_Call struct {
	*mock.Call
}

// VerifyCert is a helper method to define mock.On call
//   - ctx context.Context
//   - verifiedChains [][]*x509.Certificate
func (_e *MockCertVerifier_Expecter) VerifyCert(ctx interface{}, verifiedChains interface{}) *MockCertVerifier_VerifyCert_Call {
	return &MockCertVerifier_VerifyCert_Call{Call: _e.mock.On("VerifyCert", ctx, verifiedChains)}
}

func (_c *MockCertVerifier_VerifyCert_Call) Run(run func(ctx context.Context, verifiedChains [][]*x509.Certificate)) *MockCertVerifier_VerifyCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 [][]*x509.Certificate
		if args[1] != nil {
			arg1 = args[1].([][]*x509.Certificate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCertVerifier_VerifyCert_Call) Return(identity *authn.Identity, err error) *MockCertVerifier_VerifyCert_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockCertVerifier_VerifyCert_Call) RunAndReturn(run func(ctx context.Context, verifiedChains [][]*x509.Certificate) (*authn.Identity, error)) *MockCertVerifier_VerifyCert_Call {
	_c.Call.Return(run)
	return _c
}
