// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authn

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/authn"
)

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Verify(ctx context.Context, credential string) (*authn.Identity, error) {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *authn.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authn.Identity, error)); ok {
		return returnFunc(ctx, credential)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authn.Identity); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authn.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - credential string
func (_e *MockVerifier_Expecter) Verify(ctx interface{}, credential interface{}) *MockVerifier_Verify_Call {
	return &MockVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, credential)}
}

func (_c *MockVerifier_Verify_Call) Run(run func(ctx context.Context, credential string)) *MockVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifier_Verify_Call) Return(identity *authn.Identity, err error) *MockVerifier_Verify_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, credential string) (*authn.Identity, error)) *MockVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
