// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrancher creates a new instance of MockBrancher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrancher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrancher {
	mock := &MockBrancher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrancher is an autogenerated mock type for the Brancher type
type MockBrancher struct {
	mock.Mock
}

type MockBrancher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrancher) EXPECT() *MockBrancher_Expecter {
	return &MockBrancher_Expecter{mock: &_m.Mock}
}

// CreateBranch provides a mock function for the type MockBrancher
func (_mock *MockBrancher) CreateBranch(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrancher_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockBrancher_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - s string
func (_e *MockBrancher_Expecter) CreateBranch(s interface{}) *MockBrancher_CreateBranch_Call {
	return &MockBrancher_CreateBranch_Call{Call: _e.mock.On("CreateBranch", s)}
}

func (_c *MockBrancher_CreateBranch_Call) Run(run func(s string)) *MockBrancher_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBrancher_CreateBranch_Call) Return(err error) *MockBrancher_CreateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrancher_CreateBranch_Call) RunAndReturn(run func(s string) error) *MockBrancher_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}
