// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommitter creates a new instance of MockCommitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitter {
	mock := &MockCommitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommitter is an autogenerated mock type for the Committer type
type MockCommitter struct {
	mock.Mock
}

type MockCommitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitter) EXPECT() *MockCommitter_Expecter {
	return &MockCommitter_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockCommitter
func (_mock *MockCommitter) Commit(s string, commitOptions *git.CommitOptions) (plumbing.Hash, error) {
	ret := _mock.Called(s, commitOptions)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 plumbing.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *git.CommitOptions) (plumbing.Hash, error)); ok {
		return returnFunc(s, commitOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *git.CommitOptions) plumbing.Hash); ok {
		r0 = returnFunc(s, commitOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *git.CommitOptions) error); ok {
		r1 = returnFunc(s, commitOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommitter_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockCommitter_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - s string
//   - commitOptions *git.CommitOptions
func (_e *MockCommitter_Expecter) Commit(s interface{}, commitOptions interface{}) *MockCommitter_Commit_Call {
	return &MockCommitter_Commit_Call{Call: _e.mock.On("Commit", s, commitOptions)}
}

func (_c *MockCommitter_Commit_Call) Run(run func(s string, commitOptions *git.CommitOptions)) *MockCommitter_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *git.CommitOptions
		if args[1] != nil {
			arg1 = args[1].(*git.CommitOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommitter_Commit_Call) Return(hash plumbing.Hash, err error) *MockCommitter_Commit_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockCommitter_Commit_Call) RunAndReturn(run func(s string, commitOptions *git.CommitOptions) (plumbing.Hash, error)) *MockCommitter_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockCommitter
func (_mock *MockCommitter) Push(pushOptions *git.PushOptions) error {
	ret := _mock.Called(pushOptions)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*git.PushOptions) error); ok {
		r0 = returnFunc(pushOptions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommitter_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockCommitter_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - pushOptions *git.PushOptions
func (_e *MockCommitter_Expecter) Push(pushOptions interface{}) *MockCommitter_Push_Call {
	return &MockCommitter_Push_Call{Call: _e.mock.On("Push", pushOptions)}
}

func (_c *MockCommitter_Push_Call) Run(run func(pushOptions *git.PushOptions)) *MockCommitter_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *git.PushOptions
		if args[0] != nil {
			arg0 = args[0].(*git.PushOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommitter_Push_Call) Return(err error) *MockCommitter_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommitter_Push_Call) RunAndReturn(run func(pushOptions *git.PushOptions) error) *MockCommitter_Push_Call {
	_c.Call.Return(run)
	return _c
}
