// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockdiagnosticLogger creates a new instance of mockdiagnosticLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdiagnosticLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdiagnosticLogger {
	mock := &mockdiagnosticLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdiagnosticLogger is an autogenerated mock type for the diagnosticLogger type
type mockdiagnosticLogger struct {
	mock.Mock
}

type mockdiagnosticLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdiagnosticLogger) EXPECT() *mockdiagnosticLogger_Expecter {
	return &mockdiagnosticLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type mockdiagnosticLogger
func (_mock *mockdiagnosticLogger) Debug(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// mockdiagnosticLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type mockdiagnosticLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *mockdiagnosticLogger_Expecter) Debug(msg interface{}, keyvals ...interface{}) *mockdiagnosticLogger_Debug_Call {
	return &mockdiagnosticLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *mockdiagnosticLogger_Debug_Call) Run(run func(msg string, keyvals ...any)) *mockdiagnosticLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockdiagnosticLogger_Debug_Call) Return() *mockdiagnosticLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockdiagnosticLogger_Debug_Call) RunAndReturn(run func(msg string, keyvals ...any)) *mockdiagnosticLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type mockdiagnosticLogger
func (_mock *mockdiagnosticLogger) Warn(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// mockdiagnosticLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type mockdiagnosticLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *mockdiagnosticLogger_Expecter) Warn(msg interface{}, keyvals ...interface{}) *mockdiagnosticLogger_Warn_Call {
	return &mockdiagnosticLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *mockdiagnosticLogger_Warn_Call) Run(run func(msg string, keyvals ...any)) *mockdiagnosticLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockdiagnosticLogger_Warn_Call) Return() *mockdiagnosticLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockdiagnosticLogger_Warn_Call) RunAndReturn(run func(msg string, keyvals ...any)) *mockdiagnosticLogger_Warn_Call {
	_c.Run(run)
	return _c
}
