// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitAccessor creates a new instance of MockGitAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitAccessor {
	mock := &MockGitAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitAccessor is an autogenerated mock type for the GitAccessor type
type MockGitAccessor struct {
	mock.Mock
}

type MockGitAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitAccessor) EXPECT() *MockGitAccessor_Expecter {
	return &MockGitAccessor_Expecter{mock: &_m.Mock}
}

// WithRepo provides a mock function for the type MockGitAccessor
func (_mock *MockGitAccessor) WithRepo(fn func(*git.Repository) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WithRepo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(*git.Repository) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAccessor_WithRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithRepo'
type MockGitAccessor_WithRepo_Call struct {
	*mock.Call
}

// WithRepo is a helper method to define mock.On call
//   - fn func(*git.Repository) error
func (_e *MockGitAccessor_Expecter) WithRepo(fn interface{}) *MockGitAccessor_WithRepo_Call {
	return &MockGitAccessor_WithRepo_Call{Call: _e.mock.On("WithRepo", fn)}
}

func (_c *MockGitAccessor_WithRepo_Call) Run(run func(fn func(*git.Repository) error)) *MockGitAccessor_WithRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*git.Repository) error
		if args[0] != nil {
			arg0 = args[0].(func(*git.Repository) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitAccessor_WithRepo_Call) Return(err error) *MockGitAccessor_WithRepo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAccessor_WithRepo_Call) RunAndReturn(run func(fn func(*git.Repository) error) error) *MockGitAccessor_WithRepo_Call {
	_c.Call.Return(run)
	return _c
}

// WithTree provides a mock function for the type MockGitAccessor
func (_mock *MockGitAccessor) WithTree(fn func(*git.Worktree) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(*git.Worktree) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAccessor_WithTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTree'
type MockGitAccessor_WithTree_Call struct {
	*mock.Call
}

// WithTree is a helper method to define mock.On call
//   - fn func(*git.Worktree) error
func (_e *MockGitAccessor_Expecter) WithTree(fn interface{}) *MockGitAccessor_WithTree_Call {
	return &MockGitAccessor_WithTree_Call{Call: _e.mock.On("WithTree", fn)}
}

func (_c *MockGitAccessor_WithTree_Call) Run(run func(fn func(*git.Worktree) error)) *MockGitAccessor_WithTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*git.Worktree) error
		if args[0] != nil {
			arg0 = args[0].(func(*git.Worktree) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitAccessor_WithTree_Call) Return(err error) *MockGitAccessor_WithTree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAccessor_WithTree_Call) RunAndReturn(run func(fn func(*git.Worktree) error) error) *MockGitAccessor_WithTree_Call {
	_c.Call.Return(run)
	return _c
}
