// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInitializer creates a new instance of MockInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInitializer {
	mock := &MockInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInitializer is an autogenerated mock type for the Initializer type
type MockInitializer struct {
	mock.Mock
}

type MockInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInitializer) EXPECT() *MockInitializer_Expecter {
	return &MockInitializer_Expecter{mock: &_m.Mock}
}

// AddAll provides a mock function for the type MockInitializer
func (_mock *MockInitializer) AddAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInitializer_AddAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAll'
type MockInitializer_AddAll_Call struct {
	*mock.Call
}

// AddAll is a helper method to define mock.On call
func (_e *MockInitializer_Expecter) AddAll() *MockInitializer_AddAll_Call {
	return &MockInitializer_AddAll_Call{Call: _e.mock.On("AddAll")}
}

func (_c *MockInitializer_AddAll_Call) Run(run func()) *MockInitializer_AddAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInitializer_AddAll_Call) Return(err error) *MockInitializer_AddAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInitializer_AddAll_Call) RunAndReturn(run func() error) *MockInitializer_AddAll_Call {
	_c.Call.Return(run)
	return _c
}

// InitLocal provides a mock function for the type MockInitializer
func (_mock *MockInitializer) InitLocal(location string, branch string) (*git.Repository, *git.Worktree, error) {
	ret := _mock.Called(location, branch)

	if len(ret) == 0 {
		panic("no return value specified for InitLocal")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(location, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *git.Repository); ok {
		r0 = returnFunc(location, branch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *git.Worktree); ok {
		r1 = returnFunc(location, branch)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(location, branch)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInitializer_InitLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitLocal'
type MockInitializer_InitLocal_Call struct {
	*mock.Call
}

// InitLocal is a helper method to define mock.On call
//   - location string
//   - branch string
func (_e *MockInitializer_Expecter) InitLocal(location interface{}, branch interface{}) *MockInitializer_InitLocal_Call {
	return &MockInitializer_InitLocal_Call{Call: _e.mock.On("InitLocal", location, branch)}
}

func (_c *MockInitializer_InitLocal_Call) Run(run func(location string, branch string)) *MockInitializer_InitLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInitializer_InitLocal_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockInitializer_InitLocal_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockInitializer_InitLocal_Call) RunAndReturn(run func(location string, branch string) (*git.Repository, *git.Worktree, error)) *MockInitializer_InitLocal_Call {
	_c.Call.Return(run)
	return _c
}
