// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5"
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/vcs/repo"
)

// NewMockOpener creates a new instance of MockOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpener {
	mock := &MockOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpener is an autogenerated mock type for the Opener type
type MockOpener struct {
	mock.Mock
}

type MockOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpener) EXPECT() *MockOpener_Expecter {
	return &MockOpener_Expecter{mock: &_m.Mock}
}

// Clone provides a mock function for the type MockOpener
func (_mock *MockOpener) Clone(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error) {
	var tmpRet mock.Arguments
	if len(cloneOptions) > 0 {
		tmpRet = _mock.Called(s, s1, cloneOptions)
	} else {
		tmpRet = _mock.Called(s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(s, s1, cloneOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) *git.Repository); ok {
		r0 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...repo.CloneOption) *git.Worktree); ok {
		r1 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, ...repo.CloneOption) error); ok {
		r2 = returnFunc(s, s1, cloneOptions...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOpener_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockOpener_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - s string
//   - s1 string
//   - cloneOptions ...repo.CloneOption
func (_e *MockOpener_Expecter) Clone(s interface{}, s1 interface{}, cloneOptions ...interface{}) *MockOpener_Clone_Call {
	return &MockOpener_Clone_Call{Call: _e.mock.On("Clone",
		append([]interface{}{s, s1}, cloneOptions...)...)}
}

func (_c *MockOpener_Clone_Call) Run(run func(s string, s1 string, cloneOptions ...repo.CloneOption)) *MockOpener_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repo.CloneOption
		var variadicArgs []repo.CloneOption
		if len(args) > 2 {
			variadicArgs = args[2].([]repo.CloneOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOpener_Clone_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockOpener_Clone_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockOpener_Clone_Call) RunAndReturn(run func(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error)) *MockOpener_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockOpener
func (_mock *MockOpener) Open(repoType repo.RepoType, s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error) {
	var tmpRet mock.Arguments
	if len(cloneOptions) > 0 {
		tmpRet = _mock.Called(repoType, s, s1, cloneOptions)
	} else {
		tmpRet = _mock.Called(repoType, s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(repo.RepoType, string, string, ...repo.CloneOption) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(repoType, s, s1, cloneOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(repo.RepoType, string, string, ...repo.CloneOption) *git.Repository); ok {
		r0 = returnFunc(repoType, s, s1, cloneOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(repo.RepoType, string, string, ...repo.CloneOption) *git.Worktree); ok {
		r1 = returnFunc(repoType, s, s1, cloneOptions...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(repo.RepoType, string, string, ...repo.CloneOption) error); ok {
		r2 = returnFunc(repoType, s, s1, cloneOptions...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOpener_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockOpener_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - repoType repo.RepoType
//   - s string
//   - s1 string
//   - cloneOptions ...repo.CloneOption
func (_e *MockOpener_Expecter) Open(repoType interface{}, s interface{}, s1 interface{}, cloneOptions ...interface{}) *MockOpener_Open_Call {
	return &MockOpener_Open_Call{Call: _e.mock.On("Open",
		append([]interface{}{repoType, s, s1}, cloneOptions...)...)}
}

func (_c *MockOpener_Open_Call) Run(run func(repoType repo.RepoType, s string, s1 string, cloneOptions ...repo.CloneOption)) *MockOpener_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repo.RepoType
		if args[0] != nil {
			arg0 = args[0].(repo.RepoType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []repo.CloneOption
		var variadicArgs []repo.CloneOption
		if len(args) > 3 {
			variadicArgs = args[3].([]repo.CloneOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockOpener_Open_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockOpener_Open_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockOpener_Open_Call) RunAndReturn(run func(repoType repo.RepoType, s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error)) *MockOpener_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenInMemory provides a mock function for the type MockOpener
func (_mock *MockOpener) OpenInMemory(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error) {
	var tmpRet mock.Arguments
	if len(cloneOptions) > 0 {
		tmpRet = _mock.Called(s, s1, cloneOptions)
	} else {
		tmpRet = _mock.Called(s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for OpenInMemory")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(s, s1, cloneOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) *git.Repository); ok {
		r0 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...repo.CloneOption) *git.Worktree); ok {
		r1 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, ...repo.CloneOption) error); ok {
		r2 = returnFunc(s, s1, cloneOptions...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOpener_OpenInMemory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenInMemory'
type MockOpener_OpenInMemory_Call struct {
	*mock.Call
}

// OpenInMemory is a helper method to define mock.On call
//   - s string
//   - s1 string
//   - cloneOptions ...repo.CloneOption
func (_e *MockOpener_Expecter) OpenInMemory(s interface{}, s1 interface{}, cloneOptions ...interface{}) *MockOpener_OpenInMemory_Call {
	return &MockOpener_OpenInMemory_Call{Call: _e.mock.On("OpenInMemory",
		append([]interface{}{s, s1}, cloneOptions...)...)}
}

func (_c *MockOpener_OpenInMemory_Call) Run(run func(s string, s1 string, cloneOptions ...repo.CloneOption)) *MockOpener_OpenInMemory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repo.CloneOption
		var variadicArgs []repo.CloneOption
		if len(args) > 2 {
			variadicArgs = args[2].([]repo.CloneOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOpener_OpenInMemory_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockOpener_OpenInMemory_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockOpener_OpenInMemory_Call) RunAndReturn(run func(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error)) *MockOpener_OpenInMemory_Call {
	_c.Call.Return(run)
	return _c
}

// OpenLocal provides a mock function for the type MockOpener
func (_mock *MockOpener) OpenLocal(s string, s1 string) (*git.Repository, *git.Worktree, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for OpenLocal")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *git.Repository); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *git.Worktree); ok {
		r1 = returnFunc(s, s1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(s, s1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOpener_OpenLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenLocal'
type MockOpener_OpenLocal_Call struct {
	*mock.Call
}

// OpenLocal is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockOpener_Expecter) OpenLocal(s interface{}, s1 interface{}) *MockOpener_OpenLocal_Call {
	return &MockOpener_OpenLocal_Call{Call: _e.mock.On("OpenLocal", s, s1)}
}

func (_c *MockOpener_OpenLocal_Call) Run(run func(s string, s1 string)) *MockOpener_OpenLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOpener_OpenLocal_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockOpener_OpenLocal_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockOpener_OpenLocal_Call) RunAndReturn(run func(s string, s1 string) (*git.Repository, *git.Worktree, error)) *MockOpener_OpenLocal_Call {
	_c.Call.Return(run)
	return _c
}
