// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSourceState creates a new instance of MockSourceState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceState {
	mock := &MockSourceState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSourceState is an autogenerated mock type for the SourceState type
type MockSourceState struct {
	mock.Mock
}

type MockSourceState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceState) EXPECT() *MockSourceState_Expecter {
	return &MockSourceState_Expecter{mock: &_m.Mock}
}

// SetSource provides a mock function for the type MockSourceState
func (_mock *MockSourceState) SetSource(n int) {
	_mock.Called(n)
	return
}

// MockSourceState_SetSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSource'
type MockSourceState_SetSource_Call struct {
	*mock.Call
}

// SetSource is a helper method to define mock.On call
//   - n int
func (_e *MockSourceState_Expecter) SetSource(n interface{}) *MockSourceState_SetSource_Call {
	return &MockSourceState_SetSource_Call{Call: _e.mock.On("SetSource", n)}
}

func (_c *MockSourceState_SetSource_Call) Run(run func(n int)) *MockSourceState_SetSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceState_SetSource_Call) Return() *MockSourceState_SetSource_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSourceState_SetSource_Call) RunAndReturn(run func(n int)) *MockSourceState_SetSource_Call {
	_c.Run(run)
	return _c
}

// SourceIs provides a mock function for the type MockSourceState
func (_mock *MockSourceState) SourceIs(n int) bool {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for SourceIs")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSourceState_SourceIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceIs'
type MockSourceState_SourceIs_Call struct {
	*mock.Call
}

// SourceIs is a helper method to define mock.On call
//   - n int
func (_e *MockSourceState_Expecter) SourceIs(n interface{}) *MockSourceState_SourceIs_Call {
	return &MockSourceState_SourceIs_Call{Call: _e.mock.On("SourceIs", n)}
}

func (_c *MockSourceState_SourceIs_Call) Run(run func(n int)) *MockSourceState_SourceIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceState_SourceIs_Call) Return(b bool) *MockSourceState_SourceIs_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSourceState_SourceIs_Call) RunAndReturn(run func(n int) bool) *MockSourceState_SourceIs_Call {
	_c.Call.Return(run)
	return _c
}
