// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTreeReader creates a new instance of MockTreeReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeReader {
	mock := &MockTreeReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTreeReader is an autogenerated mock type for the TreeReader type
type MockTreeReader struct {
	mock.Mock
}

type MockTreeReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeReader) EXPECT() *MockTreeReader_Expecter {
	return &MockTreeReader_Expecter{mock: &_m.Mock}
}

// AddToFS provides a mock function for the type MockTreeReader
func (_mock *MockTreeReader) AddToFS(fs afero.Fs, gitFile *object.File, fullPath string) error {
	ret := _mock.Called(fs, gitFile, fullPath)

	if len(ret) == 0 {
		panic("no return value specified for AddToFS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(afero.Fs, *object.File, string) error); ok {
		r0 = returnFunc(fs, gitFile, fullPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTreeReader_AddToFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFS'
type MockTreeReader_AddToFS_Call struct {
	*mock.Call
}

// AddToFS is a helper method to define mock.On call
//   - fs afero.Fs
//   - gitFile *object.File
//   - fullPath string
func (_e *MockTreeReader_Expecter) AddToFS(fs interface{}, gitFile interface{}, fullPath interface{}) *MockTreeReader_AddToFS_Call {
	return &MockTreeReader_AddToFS_Call{Call: _e.mock.On("AddToFS", fs, gitFile, fullPath)}
}

func (_c *MockTreeReader_AddToFS_Call) Run(run func(fs afero.Fs, gitFile *object.File, fullPath string)) *MockTreeReader_AddToFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 afero.Fs
		if args[0] != nil {
			arg0 = args[0].(afero.Fs)
		}
		var arg1 *object.File
		if args[1] != nil {
			arg1 = args[1].(*object.File)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTreeReader_AddToFS_Call) Return(err error) *MockTreeReader_AddToFS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTreeReader_AddToFS_Call) RunAndReturn(run func(fs afero.Fs, gitFile *object.File, fullPath string) error) *MockTreeReader_AddToFS_Call {
	_c.Call.Return(run)
	return _c
}

// DirectoryExists provides a mock function for the type MockTreeReader
func (_mock *MockTreeReader) DirectoryExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DirectoryExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTreeReader_DirectoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirectoryExists'
type MockTreeReader_DirectoryExists_Call struct {
	*mock.Call
}

// DirectoryExists is a helper method to define mock.On call
//   - s string
func (_e *MockTreeReader_Expecter) DirectoryExists(s interface{}) *MockTreeReader_DirectoryExists_Call {
	return &MockTreeReader_DirectoryExists_Call{Call: _e.mock.On("DirectoryExists", s)}
}

func (_c *MockTreeReader_DirectoryExists_Call) Run(run func(s string)) *MockTreeReader_DirectoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTreeReader_DirectoryExists_Call) Return(b bool, err error) *MockTreeReader_DirectoryExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTreeReader_DirectoryExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockTreeReader_DirectoryExists_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type MockTreeReader
func (_mock *MockTreeReader) FileExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTreeReader_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type MockTreeReader_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - s string
func (_e *MockTreeReader_Expecter) FileExists(s interface{}) *MockTreeReader_FileExists_Call {
	return &MockTreeReader_FileExists_Call{Call: _e.mock.On("FileExists", s)}
}

func (_c *MockTreeReader_FileExists_Call) Run(run func(s string)) *MockTreeReader_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTreeReader_FileExists_Call) Return(b bool, err error) *MockTreeReader_FileExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTreeReader_FileExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockTreeReader_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockTreeReader
func (_mock *MockTreeReader) GetFile(s string) (*object.File, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 *object.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*object.File, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *object.File); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTreeReader_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockTreeReader_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - s string
func (_e *MockTreeReader_Expecter) GetFile(s interface{}) *MockTreeReader_GetFile_Call {
	return &MockTreeReader_GetFile_Call{Call: _e.mock.On("GetFile", s)}
}

func (_c *MockTreeReader_GetFile_Call) Run(run func(s string)) *MockTreeReader_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTreeReader_GetFile_Call) Return(file *object.File, err error) *MockTreeReader_GetFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockTreeReader_GetFile_Call) RunAndReturn(run func(s string) (*object.File, error)) *MockTreeReader_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// WalkTree provides a mock function for the type MockTreeReader
func (_mock *MockTreeReader) WalkTree(fn func(*object.File) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WalkTree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(*object.File) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTreeReader_WalkTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalkTree'
type MockTreeReader_WalkTree_Call struct {
	*mock.Call
}

// WalkTree is a helper method to define mock.On call
//   - fn func(*object.File) error
func (_e *MockTreeReader_Expecter) WalkTree(fn interface{}) *MockTreeReader_WalkTree_Call {
	return &MockTreeReader_WalkTree_Call{Call: _e.mock.On("WalkTree", fn)}
}

func (_c *MockTreeReader_WalkTree_Call) Run(run func(fn func(*object.File) error)) *MockTreeReader_WalkTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*object.File) error
		if args[0] != nil {
			arg0 = args[0].(func(*object.File) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTreeReader_WalkTree_Call) Return(err error) *MockTreeReader_WalkTree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTreeReader_WalkTree_Call) RunAndReturn(run func(fn func(*object.File) error) error) *MockTreeReader_WalkTree_Call {
	_c.Call.Return(run)
	return _c
}
