// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorktreeFS creates a new instance of MockWorktreeFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorktreeFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorktreeFS {
	mock := &MockWorktreeFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorktreeFS is an autogenerated mock type for the WorktreeFS type
type MockWorktreeFS struct {
	mock.Mock
}

type MockWorktreeFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorktreeFS) EXPECT() *MockWorktreeFS_Expecter {
	return &MockWorktreeFS_Expecter{mock: &_m.Mock}
}

// WithWorkFS provides a mock function for the type MockWorktreeFS
func (_mock *MockWorktreeFS) WithWorkFS(fn func(afero.Fs) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WithWorkFS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(afero.Fs) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorktreeFS_WithWorkFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithWorkFS'
type MockWorktreeFS_WithWorkFS_Call struct {
	*mock.Call
}

// WithWorkFS is a helper method to define mock.On call
//   - fn func(afero.Fs) error
func (_e *MockWorktreeFS_Expecter) WithWorkFS(fn interface{}) *MockWorktreeFS_WithWorkFS_Call {
	return &MockWorktreeFS_WithWorkFS_Call{Call: _e.mock.On("WithWorkFS", fn)}
}

func (_c *MockWorktreeFS_WithWorkFS_Call) Run(run func(fn func(afero.Fs) error)) *MockWorktreeFS_WithWorkFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(afero.Fs) error
		if args[0] != nil {
			arg0 = args[0].(func(afero.Fs) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorktreeFS_WithWorkFS_Call) Return(err error) *MockWorktreeFS_WithWorkFS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorktreeFS_WithWorkFS_Call) RunAndReturn(run func(fn func(afero.Fs) error) error) *MockWorktreeFS_WithWorkFS_Call {
	_c.Call.Return(run)
	return _c
}

// WorkFS provides a mock function for the type MockWorktreeFS
func (_mock *MockWorktreeFS) WorkFS() (afero.Fs, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkFS")
	}

	var r0 afero.Fs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (afero.Fs, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() afero.Fs); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorktreeFS_WorkFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkFS'
type MockWorktreeFS_WorkFS_Call struct {
	*mock.Call
}

// WorkFS is a helper method to define mock.On call
func (_e *MockWorktreeFS_Expecter) WorkFS() *MockWorktreeFS_WorkFS_Call {
	return &MockWorktreeFS_WorkFS_Call{Call: _e.mock.On("WorkFS")}
}

func (_c *MockWorktreeFS_WorkFS_Call) Run(run func()) *MockWorktreeFS_WorkFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorktreeFS_WorkFS_Call) Return(fs afero.Fs, err error) *MockWorktreeFS_WorkFS_Call {
	_c.Call.Return(fs, err)
	return _c
}

func (_c *MockWorktreeFS_WorkFS_Call) RunAndReturn(run func() (afero.Fs, error)) *MockWorktreeFS_WorkFS_Call {
	_c.Call.Return(run)
	return _c
}
