// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package telemetry

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/telemetry"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockBackend
func (_mock *MockBackend) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBackend_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBackend_Expecter) Close() *MockBackend_Close_Call {
	return &MockBackend_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBackend_Close_Call) Run(run func()) *MockBackend_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_Close_Call) Return(err error) *MockBackend_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_Close_Call) RunAndReturn(run func() error) *MockBackend_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockBackend
func (_mock *MockBackend) Send(ctx context.Context, events []telemetry.Event) error {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []telemetry.Event) error); ok {
		r0 = returnFunc(ctx, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockBackend_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - events []telemetry.Event
func (_e *MockBackend_Expecter) Send(ctx interface{}, events interface{}) *MockBackend_Send_Call {
	return &MockBackend_Send_Call{Call: _e.mock.On("Send", ctx, events)}
}

func (_c *MockBackend_Send_Call) Run(run func(ctx context.Context, events []telemetry.Event)) *MockBackend_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []telemetry.Event
		if args[1] != nil {
			arg1 = args[1].([]telemetry.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_Send_Call) Return(err error) *MockBackend_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_Send_Call) RunAndReturn(run func(ctx context.Context, events []telemetry.Event) error) *MockBackend_Send_Call {
	_c.Call.Return(run)
	return _c
}
