// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package telemetry

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeletionRequestor creates a new instance of MockDeletionRequestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeletionRequestor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeletionRequestor {
	mock := &MockDeletionRequestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeletionRequestor is an autogenerated mock type for the DeletionRequestor type
type MockDeletionRequestor struct {
	mock.Mock
}

type MockDeletionRequestor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeletionRequestor) EXPECT() *MockDeletionRequestor_Expecter {
	return &MockDeletionRequestor_Expecter{mock: &_m.Mock}
}

// RequestDeletion provides a mock function for the type MockDeletionRequestor
func (_mock *MockDeletionRequestor) RequestDeletion(ctx context.Context, machineID string) error {
	ret := _mock.Called(ctx, machineID)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeletion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, machineID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeletionRequestor_RequestDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDeletion'
type MockDeletionRequestor_RequestDeletion_Call struct {
	*mock.Call
}

// RequestDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - machineID string
func (_e *MockDeletionRequestor_Expecter) RequestDeletion(ctx interface{}, machineID interface{}) *MockDeletionRequestor_RequestDeletion_Call {
	return &MockDeletionRequestor_RequestDeletion_Call{Call: _e.mock.On("RequestDeletion", ctx, machineID)}
}

func (_c *MockDeletionRequestor_RequestDeletion_Call) Run(run func(ctx context.Context, machineID string)) *MockDeletionRequestor_RequestDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeletionRequestor_RequestDeletion_Call) Return(err error) *MockDeletionRequestor_RequestDeletion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeletionRequestor_RequestDeletion_Call) RunAndReturn(run func(ctx context.Context, machineID string) error) *MockDeletionRequestor_RequestDeletion_Call {
	_c.Call.Return(run)
	return _c
}
