// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLeveller creates a new instance of MockLeveller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeveller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeveller {
	mock := &MockLeveller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLeveller is an autogenerated mock type for the Leveller type
type MockLeveller struct {
	mock.Mock
}

type MockLeveller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeveller) EXPECT() *MockLeveller_Expecter {
	return &MockLeveller_Expecter{mock: &_m.Mock}
}

// SetLevel provides a mock function for the type MockLeveller
func (_mock *MockLeveller) SetLevel(level slog.Level) {
	_mock.Called(level)
	return
}

// MockLeveller_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type MockLeveller_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level slog.Level
func (_e *MockLeveller_Expecter) SetLevel(level interface{}) *MockLeveller_SetLevel_Call {
	return &MockLeveller_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *MockLeveller_SetLevel_Call) Run(run func(level slog.Level)) *MockLeveller_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 slog.Level
		if args[0] != nil {
			arg0 = args[0].(slog.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLeveller_SetLevel_Call) Return() *MockLeveller_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLeveller_SetLevel_Call) RunAndReturn(run func(level slog.Level)) *MockLeveller_SetLevel_Call {
	_c.Run(run)
	return _c
}
