// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	"context"
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Debug(msg interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, args ...any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// DebugContext provides a mock function for the type MockLogger
func (_mock *MockLogger) DebugContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_DebugContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugContext'
type MockLogger_DebugContext_Call struct {
	*mock.Call
}

// DebugContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) DebugContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_DebugContext_Call {
	return &MockLogger_DebugContext_Call{Call: _e.mock.On("DebugContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_DebugContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_DebugContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_DebugContext_Call) Return() *MockLogger_DebugContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_DebugContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_DebugContext_Call {
	_c.Run(run)
	return _c
}

// Enabled provides a mock function for the type MockLogger
func (_mock *MockLogger) Enabled(ctx context.Context, level slog.Level) bool {
	ret := _mock.Called(ctx, level)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, slog.Level) bool); ok {
		r0 = returnFunc(ctx, level)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockLogger_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockLogger_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - ctx context.Context
//   - level slog.Level
func (_e *MockLogger_Expecter) Enabled(ctx interface{}, level interface{}) *MockLogger_Enabled_Call {
	return &MockLogger_Enabled_Call{Call: _e.mock.On("Enabled", ctx, level)}
}

func (_c *MockLogger_Enabled_Call) Run(run func(ctx context.Context, level slog.Level)) *MockLogger_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 slog.Level
		if args[1] != nil {
			arg1 = args[1].(slog.Level)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogger_Enabled_Call) Return(b bool) *MockLogger_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockLogger_Enabled_Call) RunAndReturn(run func(ctx context.Context, level slog.Level) bool) *MockLogger_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Error(msg interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorContext provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_ErrorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorContext'
type MockLogger_ErrorContext_Call struct {
	*mock.Call
}

// ErrorContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) ErrorContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_ErrorContext_Call {
	return &MockLogger_ErrorContext_Call{Call: _e.mock.On("ErrorContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_ErrorContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_ErrorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorContext_Call) Return() *MockLogger_ErrorContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_ErrorContext_Call {
	_c.Run(run)
	return _c
}

// Handler provides a mock function for the type MockLogger
func (_mock *MockLogger) Handler() slog.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 slog.Handler
	if returnFunc, ok := ret.Get(0).(func() slog.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Handler)
		}
	}
	return r0
}

// MockLogger_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockLogger_Handler_Call struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockLogger_Expecter) Handler() *MockLogger_Handler_Call {
	return &MockLogger_Handler_Call{Call: _e.mock.On("Handler")}
}

func (_c *MockLogger_Handler_Call) Run(run func()) *MockLogger_Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_Handler_Call) Return(handler slog.Handler) *MockLogger_Handler_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockLogger_Handler_Call) RunAndReturn(run func() slog.Handler) *MockLogger_Handler_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Info(msg interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// InfoContext provides a mock function for the type MockLogger
func (_mock *MockLogger) InfoContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_InfoContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoContext'
type MockLogger_InfoContext_Call struct {
	*mock.Call
}

// InfoContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) InfoContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_InfoContext_Call {
	return &MockLogger_InfoContext_Call{Call: _e.mock.On("InfoContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_InfoContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_InfoContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_InfoContext_Call) Return() *MockLogger_InfoContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_InfoContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_InfoContext_Call {
	_c.Run(run)
	return _c
}

// Log provides a mock function for the type MockLogger
func (_mock *MockLogger) Log(ctx context.Context, level slog.Level, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, level, msg, args)
	} else {
		_mock.Called(ctx, level, msg)
	}

	return
}

// MockLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - level slog.Level
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Log(ctx interface{}, level interface{}, msg interface{}, args ...interface{}) *MockLogger_Log_Call {
	return &MockLogger_Log_Call{Call: _e.mock.On("Log",
		append([]interface{}{ctx, level, msg}, args...)...)}
}

func (_c *MockLogger_Log_Call) Run(run func(ctx context.Context, level slog.Level, msg string, args ...any)) *MockLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 slog.Level
		if args[1] != nil {
			arg1 = args[1].(slog.Level)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Log_Call) Return() *MockLogger_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Log_Call) RunAndReturn(run func(ctx context.Context, level slog.Level, msg string, args ...any)) *MockLogger_Log_Call {
	_c.Run(run)
	return _c
}

// LogAttrs provides a mock function for the type MockLogger
func (_mock *MockLogger) LogAttrs(ctx context.Context, level slog.Level, msg string, attrs ...slog.Attr) {
	if len(attrs) > 0 {
		_mock.Called(ctx, level, msg, attrs)
	} else {
		_mock.Called(ctx, level, msg)
	}

	return
}

// MockLogger_LogAttrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogAttrs'
type MockLogger_LogAttrs_Call struct {
	*mock.Call
}

// LogAttrs is a helper method to define mock.On call
//   - ctx context.Context
//   - level slog.Level
//   - msg string
//   - attrs ...slog.Attr
func (_e *MockLogger_Expecter) LogAttrs(ctx interface{}, level interface{}, msg interface{}, attrs ...interface{}) *MockLogger_LogAttrs_Call {
	return &MockLogger_LogAttrs_Call{Call: _e.mock.On("LogAttrs",
		append([]interface{}{ctx, level, msg}, attrs...)...)}
}

func (_c *MockLogger_LogAttrs_Call) Run(run func(ctx context.Context, level slog.Level, msg string, attrs ...slog.Attr)) *MockLogger_LogAttrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 slog.Level
		if args[1] != nil {
			arg1 = args[1].(slog.Level)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 3 {
			variadicArgs = args[3].([]slog.Attr)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_LogAttrs_Call) Return() *MockLogger_LogAttrs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_LogAttrs_Call) RunAndReturn(run func(ctx context.Context, level slog.Level, msg string, attrs ...slog.Attr)) *MockLogger_LogAttrs_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Warn(msg interface{}, args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// WarnContext provides a mock function for the type MockLogger
func (_mock *MockLogger) WarnContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_WarnContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnContext'
type MockLogger_WarnContext_Call struct {
	*mock.Call
}

// WarnContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) WarnContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_WarnContext_Call {
	return &MockLogger_WarnContext_Call{Call: _e.mock.On("WarnContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_WarnContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_WarnContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_WarnContext_Call) Return() *MockLogger_WarnContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_WarnContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_WarnContext_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type MockLogger
func (_mock *MockLogger) With(args ...any) *slog.Logger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func(...any) *slog.Logger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockLogger_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockLogger_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...any
func (_e *MockLogger_Expecter) With(args ...interface{}) *MockLogger_With_Call {
	return &MockLogger_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_With_Call) Run(run func(args ...any)) *MockLogger_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_With_Call) Return(logger *slog.Logger) *MockLogger_With_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLogger_With_Call) RunAndReturn(run func(args ...any) *slog.Logger) *MockLogger_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithGroup provides a mock function for the type MockLogger
func (_mock *MockLogger) WithGroup(name string) *slog.Logger {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithGroup")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func(string) *slog.Logger); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockLogger_WithGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithGroup'
type MockLogger_WithGroup_Call struct {
	*mock.Call
}

// WithGroup is a helper method to define mock.On call
//   - name string
func (_e *MockLogger_Expecter) WithGroup(name interface{}) *MockLogger_WithGroup_Call {
	return &MockLogger_WithGroup_Call{Call: _e.mock.On("WithGroup", name)}
}

func (_c *MockLogger_WithGroup_Call) Run(run func(name string)) *MockLogger_WithGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_WithGroup_Call) Return(logger *slog.Logger) *MockLogger_WithGroup_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLogger_WithGroup_Call) RunAndReturn(run func(name string) *slog.Logger) *MockLogger_WithGroup_Call {
	_c.Call.Return(run)
	return _c
}
