// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/logger"
)

// NewMockReformatter creates a new instance of MockReformatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReformatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReformatter {
	mock := &MockReformatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReformatter is an autogenerated mock type for the Reformatter type
type MockReformatter struct {
	mock.Mock
}

type MockReformatter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReformatter) EXPECT() *MockReformatter_Expecter {
	return &MockReformatter_Expecter{mock: &_m.Mock}
}

// SetFormatter provides a mock function for the type MockReformatter
func (_mock *MockReformatter) SetFormatter(f logger.Formatter) {
	_mock.Called(f)
	return
}

// MockReformatter_SetFormatter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFormatter'
type MockReformatter_SetFormatter_Call struct {
	*mock.Call
}

// SetFormatter is a helper method to define mock.On call
//   - f logger.Formatter
func (_e *MockReformatter_Expecter) SetFormatter(f interface{}) *MockReformatter_SetFormatter_Call {
	return &MockReformatter_SetFormatter_Call{Call: _e.mock.On("SetFormatter", f)}
}

func (_c *MockReformatter_SetFormatter_Call) Run(run func(f logger.Formatter)) *MockReformatter_SetFormatter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.Formatter
		if args[0] != nil {
			arg0 = args[0].(logger.Formatter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReformatter_SetFormatter_Call) Return() *MockReformatter_SetFormatter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReformatter_SetFormatter_Call) RunAndReturn(run func(f logger.Formatter)) *MockReformatter_SetFormatter_Call {
	_c.Run(run)
	return _c
}
