package generator

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/spf13/afero"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/phpboyscout/go-tool-base/internal/generator/templates"
	"gitlab.com/phpboyscout/go-tool-base/pkg/logger"
	"gitlab.com/phpboyscout/go-tool-base/pkg/props"
)

// cmd.go is generated, so the conflict machinery rewrites it without asking and
// is right to. But under spec 0190 that rewrite changes what the built binary
// DOES — a group that exited 2 now exits 0 — and a silent behaviour change
// arriving on an unrelated regeneration is the precise complaint in issue #22.
// The mechanism must not reproduce the surprise it exists to fix.

// wiredCmdGo is what the generator emitted before 0190: a RunE calling into
// main.go. Finding this on disk is what makes a regeneration a transition.
const wiredCmdGo = `// Code generated by gtb. DO NOT EDIT.

package lexicon

import (
	cobra "github.com/spf13/cobra"
	props "gitlab.com/phpboyscout/go-tool-base/pkg/props"
	setup "gitlab.com/phpboyscout/go-tool-base/pkg/setup"
)

type LexiconOptions struct{}

func NewCmdLexicon(props *props.Props) *setup.Command {
	opts := &LexiconOptions{}

	cmd := setup.Wrap("lexicon", &cobra.Command{
		Use: "lexicon",
		RunE: func(cmd *cobra.Command, args []string) error {
			return RunLexicon(cmd.Context(), props, opts, args)
		},
	})

	return cmd
}
`

func behaviourFixture(t *testing.T, cmdGo, mainGo string) (*Generator, string) {
	t.Helper()

	fs := afero.NewMemMapFs()
	root := "/work"
	cmdDir := filepath.Join(root, "pkg", "cmd", "lexicon")

	require.NoError(t, fs.MkdirAll(cmdDir, DefaultDirMode))

	for name, content := range map[string]string{"cmd.go": cmdGo, "main.go": mainGo} {
		if content != "" {
			require.NoError(t, afero.WriteFile(fs,
				filepath.Join(cmdDir, name), []byte(content), DefaultFileMode))
		}
	}

	p := &props.Props{FS: fs, Logger: logger.NewNoop()}
	g := New(p, &Config{Path: root, Name: "lexicon", Overwrite: "allow"})

	return g, cmdDir
}

func regenerateGroup(t *testing.T, g *Generator, cmdDir string) {
	t.Helper()

	data := &templates.CommandData{
		Package:        "lexicon",
		Name:           "lexicon",
		PascalName:     "Lexicon",
		HasSubcommands: true,
	}

	require.NoError(t, g.GenerateCommandFile(context.Background(), cmdDir, data))
}

func TestBehaviourChange_ReportedOnTheRunThatChangesIt(t *testing.T) {
	t.Parallel()

	g, cmdDir := behaviourFixture(t, wiredCmdGo, untouchedGroupStub)

	regenerateGroup(t, g, cmdDir)

	require.Len(t, g.conflicts.behaviourChanges, 1,
		"the run that rewrites a wired group's cmd.go is the run that must say so")

	change := g.conflicts.behaviourChanges[0]
	assert.Equal(t, "lexicon", change.Command)
	assert.Equal(t, filepath.Join("pkg", "cmd", "lexicon", "cmd.go"), change.RelPath)
	assert.Contains(t, change.Was, "2", "the report names the code it used to exit with")
	assert.Contains(t, change.Now, "0", "and the one it exits with now")
	assert.Contains(t, change.KeepOld, "ErrRunSubCommand",
		"and how to keep the old behaviour, which is what D6 keeps the sentinel for")
}

// The half that rots. A project already on the new model must report nothing, on
// every subsequent run, forever — a summary line that fires every time is one
// people learn to scroll past, and it would then hide the next real one.
func TestBehaviourChange_SilentOnEverySubsequentRun(t *testing.T) {
	t.Parallel()

	g, cmdDir := behaviourFixture(t, wiredCmdGo, untouchedGroupStub)

	regenerateGroup(t, g, cmdDir)
	require.Len(t, g.conflicts.behaviourChanges, 1, "first run: the transition")

	// A second generator over the same tree — cmd.go now wires GroupRunE.
	again := New(g.props, &Config{Path: "/work", Name: "lexicon", Overwrite: "allow"})
	regenerateGroup(t, again, cmdDir)

	assert.Empty(t, again.conflicts.behaviourChanges,
		"no transition occurred, so there is nothing to report")
}

func TestBehaviourChange_NotReportedForAFreshCommand(t *testing.T) {
	t.Parallel()

	// Nothing on disk to transition FROM: this command has never had the old
	// behaviour, so announcing a change would be announcing a fiction.
	g, cmdDir := behaviourFixture(t, "", "")

	regenerateGroup(t, g, cmdDir)

	assert.Empty(t, g.conflicts.behaviourChanges)
}

func TestBehaviourChange_NotReportedForAWorkingGroup(t *testing.T) {
	t.Parallel()

	// Its cmd.go still wires Run<Name> afterwards, so nothing changed.
	g, cmdDir := behaviourFixture(t, wiredCmdGo, developerWrittenRun)

	regenerateGroup(t, g, cmdDir)

	assert.Empty(t, g.conflicts.behaviourChanges)
}

// D2 leaves a group with a hand-written body alone, which means the consumer with
// ten verb-printing parents never hears about the new model. The run that reports
// a transition also names them, once, so the opt-in is offered rather than
// inferred — and never rewritten.
func TestAdoptableGroups_AreNamedAlongsideATransition(t *testing.T) {
	t.Parallel()

	g, cmdDir := behaviourFixture(t, wiredCmdGo, untouchedGroupStub)

	// A working group elsewhere in the same tree.
	other := filepath.Join("/work", "pkg", "cmd", "voice")
	require.NoError(t, g.props.FS.MkdirAll(other, DefaultDirMode))
	require.NoError(t, afero.WriteFile(g.props.FS, filepath.Join(other, "main.go"),
		[]byte(handWrittenVerbPrinter), DefaultFileMode))

	regenerateGroup(t, g, cmdDir)

	data := &templates.CommandData{
		Package:        "voice",
		Name:           "voice",
		PascalName:     "Lexicon", // the fixture's hand-written body names RunLexicon
		HasSubcommands: true,
	}
	require.NoError(t, g.GenerateCommandFile(context.Background(), other, data))

	assert.Contains(t, g.conflicts.adoptable, "voice",
		"a working group is offered the change it did not receive")
	assert.NotContains(t, g.conflicts.adoptable, "lexicon",
		"and the group that already adopted it is not offered it again")
}

func TestSummary_CountsBehaviourChangesAlongsideTheRest(t *testing.T) {
	t.Parallel()

	assert.Equal(t, "1 file kept, 1 command changed behaviour",
		pluraliseConflictSummary(0, 1, 0, 1))
	assert.Equal(t, "2 files ignored, 3 commands changed behaviour",
		pluraliseConflictSummary(2, 0, 0, 3))
	assert.Equal(t, "1 file sealed", pluraliseConflictSummary(0, 0, 1, 0))
}
