package generator

import (
	"testing"

	"github.com/spf13/afero"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/phpboyscout/go-tool-base/pkg/logger"
	"gitlab.com/phpboyscout/go-tool-base/pkg/props"
)

// TestProvenanceFile_RoundTrip is the D9 guard: the signing posture, template
// overlay provenance, and module_published — the properties the renderer does
// not put into generated source — survive an emit-then-recover cycle through the
// annotated provenance file, so a from-scratch manifest rebuild reconstructs
// them. Per-file overlay hashes are intentionally not recorded (they are
// recomputed when the overlay is re-applied).
func TestProvenanceFile_RoundTrip(t *testing.T) {
	t.Parallel()

	original := ManifestProperties{
		Signing: ManifestSigning{
			Enabled:          true,
			ExternalKeyEmail: "sec@acme.example",
			RequireSignature: true,
			KeySource:        "both",
			Backend:          "aws-kms",
			KeyID:            "arn:aws:kms:eu-west-2:1:key/abc",
			KMSRegion:        "eu-west-2",
			PublicKey:        "internal/trustkeys/keys/signing-key-v1.asc",
		},
		Templates: []TemplateSource{
			{Name: "corp", Type: "git", Location: "acme/tpl", Ref: "v1.2.0", Resolved: "abc123"},
			{Name: "local", Type: "local", Location: "./overlays", Fingerprint: "def456"},
		},
		ModulePublished: true,
	}

	fs := afero.NewMemMapFs()
	g := New(&props.Props{FS: fs, Logger: logger.NewNoop()}, &Config{Path: "/proj"})

	require.NoError(t, g.writeProvenanceFile(&Manifest{Properties: original}))

	// The emitted file must be a valid, generated, DO-NOT-EDIT Go source file.
	content, err := afero.ReadFile(fs, provenancePath("/proj"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "// Code generated by gtb. DO NOT EDIT.")
	assert.Contains(t, string(content), "package root")

	var recovered ManifestProperties
	g.applyProvenanceFile(&recovered)

	assert.Equal(t, original.Signing, recovered.Signing)
	assert.Equal(t, original.Templates, recovered.Templates)
	assert.True(t, recovered.ModulePublished)
}

// TestProvenanceFile_RemovedWhenEmpty verifies a project with no recordable
// provenance carries no file, and a stale one is dropped.
func TestProvenanceFile_RemovedWhenEmpty(t *testing.T) {
	t.Parallel()

	fs := afero.NewMemMapFs()
	g := New(&props.Props{FS: fs, Logger: logger.NewNoop()}, &Config{Path: "/proj"})

	// Pre-seed a stale provenance file.
	require.NoError(t, afero.WriteFile(fs, provenancePath("/proj"), []byte("// stale\npackage root\n"), 0o644))

	require.NoError(t, g.writeProvenanceFile(&Manifest{Properties: ManifestProperties{}}))

	exists, _ := afero.Exists(fs, provenancePath("/proj"))
	assert.False(t, exists, "empty provenance must remove any stale file")
}
