package generator

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"text/template"

	"github.com/cockroachdb/errors"
	"github.com/dave/jennifer/jen"
	"github.com/spf13/afero"
	"gopkg.in/yaml.v3"

	"gitlab.com/phpboyscout/go-tool-base/internal/generator/templates"
)

//go:embed assets/skeleton/*
var skeletonAssets embed.FS

//go:embed all:assets/skeleton-github
var skeletonGitHubAssets embed.FS

//go:embed all:assets/skeleton-gitlab
var skeletonGitLabAssets embed.FS

type SkeletonConfig struct {
	Name                  string
	Repo                  string
	Host                  string
	Description           string
	Path                  string
	GoVersion             string // overrides autodetected version when set
	Features              []ManifestFeature
	Private               bool   // true if the repository requires authentication to access
	HelpType              string // "slack", "teams", or ""
	SlackChannel          string
	SlackTeam             string
	TeamsChannel          string
	TeamsTeam             string
	TelemetryEndpoint     string            // populated from manifest telemetry.endpoint
	TelemetryOTelEndpoint string            // populated from manifest telemetry.otel_endpoint
	EnvPrefix             string            // environment variable prefix for config overrides
	Signing               ManifestSigning   // self-update signature-verification posture (disabled by default)
	Bootstrap             ManifestBootstrap // config-bootstrap lifecycle policy (auto-init / skip-config-check)
	// UpdatePolicy is the generated tool's self-update posture baseline
	// (disabled / prompt / enabled). Empty leaves it unset so the framework
	// default (disabled) applies; wired into the generated root command's
	// props.Tool.UpdatePolicy. See https://gitlab.com/phpboyscout/go-tool-base/-/wikis/specs/0087-forced-update-feature.
	UpdatePolicy string
	// UpdateCheckInterval is the generated tool's baseline self-update-check
	// throttle as a Go duration string (e.g. "24h"). Empty leaves it unset so
	// the framework default (24h) applies; wired into the generated root
	// command's props.Tool.UpdateCheckInterval.
	UpdateCheckInterval string
	// CIComponentSource overrides the phpboyscout/cicd include base in the
	// scaffolded GitLab pipeline. Empty falls back to
	// DefaultCICDComponentSource. GitLab-only; ignored for GitHub projects.
	CIComponentSource string
	// Templates carries the custom template-overlay sources (in layer order)
	// through generation. The wizard/flags populate it and
	// writeSkeletonManifest persists it.
	Templates []TemplateSource
}

// splitRepoPath splits a repository path on the last '/', returning the org
// (everything before) and repo name (everything after). This supports both
// simple GitHub paths ("org/repo") and deeply-nested GitLab group paths
// ("group/subgroup/repo").
func splitRepoPath(repo string) (org, repoName string, err error) {
	i := strings.LastIndex(repo, "/")
	if i <= 0 {
		return "", "", errors.Newf("invalid repository format: path must contain '/' with a non-empty org (e.g. org/repo)")
	}

	if i == len(repo)-1 {
		return "", "", errors.Newf("invalid repository format: repository name must not be empty (e.g. org/repo)")
	}

	return repo[:i], repo[i+1:], nil
}

// skeletonGenerateFile creates the pkg/cmd/root/generate.go file with
// a go:generate directive to produce the embedded CHANGELOG.md via the
// changelog tool. The directive is omitted when the changelog feature is disabled.
func skeletonGenerateFile(disabledFeatures []string) *jen.File {
	f := jen.NewFile("root")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	if !slices.Contains(disabledFeatures, "changelog") {
		f.Comment("//go:generate go tool changelog generate --output assets/CHANGELOG.md")
	}

	return f
}

func releaseProviderForHost(host string) string {
	if strings.Contains(host, "gitlab") {
		return "gitlab"
	}

	return "github"
}

// releaseProviderAccessor is a narrow interface for extracting the release
// provider from template data structs without brittle full-struct type assertions.
type releaseProviderAccessor interface {
	GetReleaseProvider() string
}

// extractReleaseProvider reads the release provider from the data struct via
// the releaseProviderAccessor interface. Every caller passes a named type that
// implements it (skeletonTemplateData, TemplateContractData), so a non-matching
// value simply yields "".
func extractReleaseProvider(data any) string {
	if rp, ok := data.(releaseProviderAccessor); ok {
		return rp.GetReleaseProvider()
	}

	return ""
}

func (g *Generator) currentVersion() string {
	if g.props.Version != nil {
		return g.props.Version.GetVersion()
	}

	return ""
}

func resolveGoVersion(configured string) string {
	if configured != "" {
		return configured
	}

	return strings.TrimPrefix(runtime.Version(), "go")
}

// resolveCIComponentSource returns the configured phpboyscout/cicd include
// base, falling back to the framework default when unset so a manifest with no
// ci block (or a hand-written one) still renders a complete pipeline.
func resolveCIComponentSource(configured string) string {
	if configured != "" {
		return configured
	}

	return DefaultCICDComponentSource
}

func (g *Generator) runSkeletonPostProcessing(ctx context.Context, path string) {
	g.props.Logger.Info("Running go mod tidy...")

	if err := g.runSkeletonCommand(ctx, path, "go", "mod", "tidy"); err != nil {
		g.props.Logger.Warn("Failed to run go mod tidy", "error", err)
	}

	g.props.Logger.Info("Running golangci-lint run --fix...")

	if err := g.runSkeletonCommand(ctx, path, "golangci-lint", "run", "--fix"); err != nil {
		g.props.Logger.Warn("Failed to run golangci-lint", "error", err)
	}
}

func (g *Generator) GenerateSkeleton(ctx context.Context, config SkeletonConfig) error {
	if g.config.DryRun {
		result, err := g.GenerateSkeletonDryRun(ctx, config)
		if err != nil {
			return err
		}

		result.Print(os.Stdout)

		return nil
	}

	return g.generateSkeleton(ctx, config)
}

// GenerateSkeletonDryRun previews what GenerateSkeleton would do without writing to disk.
func (g *Generator) GenerateSkeletonDryRun(ctx context.Context, config SkeletonConfig) (*DryRunResult, error) {
	g.props.Logger.Info("dry run: previewing skeleton", "name", config.Name, "path", config.Path)

	result, err := g.withDryRunOverlay(ctx, config.Path, func() error {
		return g.generateSkeletonFiles(config)
	}, &dryRunPostProcess{
		commands: [][]string{
			{"go", "mod", "tidy"},
			{"golangci-lint", "run", "--fix"},
		},
	})
	if err != nil {
		return nil, err
	}

	result.Actions = append(result.Actions, g.describeGitInit(config)...)

	return result, nil
}

// describeGitInit returns the would-be git side effects for the dry-run
// preview, mirroring the gating runSkeletonGitInit applies at write time.
func (g *Generator) describeGitInit(config SkeletonConfig) []string {
	if !g.config.GitInit {
		return nil
	}

	if found, err := repoDiscover(config.Path); err == nil && found {
		return []string{fmt.Sprintf("would skip git init: %s is already inside a git repository", config.Path)}
	}

	branch := g.config.GitBranch
	if branch == "" {
		branch = defaultGitBranch
	}

	actions := []string{fmt.Sprintf("would git init on branch %q and commit %q", branch, initialCommitSubject(config.Name))}

	if g.config.GitPush {
		if url, err := remoteURLFromConfig(config); err == nil {
			actions = append(actions, fmt.Sprintf("would push branch %q to %s", branch, url))
		}
	}

	return actions
}

func (g *Generator) generateSkeleton(ctx context.Context, config SkeletonConfig) error {
	g.props.Logger.Info("generating skeleton", "name", config.Name, "path", config.Path)

	if err := g.generateSkeletonFiles(config); err != nil {
		return err
	}

	if _, ok := g.props.FS.(*afero.OsFs); ok {
		g.runSkeletonPostProcessing(ctx, config.Path)

		// Post-processing tools (go mod tidy, golangci-lint) may have modified
		// tracked files. Refresh their hashes so the next run does not flag
		// post-processing changes as user customisations.
		storedHashes := g.loadProjectFileHashes(config.Path)
		if err := g.refreshProjectFileHashes(config.Path, storedHashes); err != nil {
			g.props.Logger.Warn("Failed to refresh project file hashes after post-processing", "error", err)
		}

		// The initial commit captures the fully-settled tree (post-tidy,
		// post-lint-fix, final manifest hashes). Best-effort: any git failure is
		// a warning, never a generation error.
		g.runSkeletonGitInit(ctx, config)
	}

	g.props.Logger.Info("successfully generated skeleton", "path", config.Path)

	return nil
}

// generateSkeletonFiles performs the core skeleton file generation: Go files,
// template files, and manifest. It does not run post-processing shell commands.
func (g *Generator) generateSkeletonFiles(config SkeletonConfig) error {
	org, repoName, err := splitRepoPath(config.Repo)
	if err != nil {
		return err
	}

	if config.Host == "" {
		config.Host = "github.com"
	}

	if config.Description == "" {
		config.Description = fmt.Sprintf("%s utility", config.Name)
	}

	data := skeletonTemplateData{
		Name:                  config.Name,
		Repo:                  config.Repo,
		Host:                  config.Host,
		ModulePath:            fmt.Sprintf("%s/%s", config.Host, config.Repo),
		Description:           config.Description,
		Org:                   org,
		RepoName:              repoName,
		ReleaseProvider:       releaseProviderForHost(config.Host),
		GoToolBaseVersion:     g.currentVersion(),
		GoVersion:             resolveGoVersion(config.GoVersion),
		DisabledFeatures:      calculateDisabledFeatures(config.Features),
		EnabledFeatures:       calculateEnabledFeatures(config.Features),
		Private:               config.Private,
		HelpType:              config.HelpType,
		SlackChannel:          config.SlackChannel,
		SlackTeam:             config.SlackTeam,
		TeamsChannel:          config.TeamsChannel,
		TeamsTeam:             config.TeamsTeam,
		TelemetryEndpoint:     config.TelemetryEndpoint,
		TelemetryOTelEndpoint: config.TelemetryOTelEndpoint,
		EnvPrefix:             config.EnvPrefix,
		Signing:               config.Signing,
		Bootstrap:             config.Bootstrap,
		UpdatePolicy:          config.UpdatePolicy,
		UpdateCheckInterval:   config.UpdateCheckInterval,
		CIComponentSource:     resolveCIComponentSource(config.CIComponentSource),
		CICDComponentVersion:  CICDComponentVersion,
		CIEnableE2E:           false,
	}

	// Load existing project-level hashes so we can detect customised files.
	storedHashes := g.loadProjectFileHashes(config.Path)

	if err := g.generateSkeletonGoFiles(config.Path, data); err != nil {
		return err
	}

	ignoreRules := LoadIgnoreRules(g.props.FS, config.Path)

	writtenHashes, updatedSources, err := g.generateSkeletonTemplateFilesWithSources(config.Path, data, storedHashes, ignoreRules, config.Templates)
	if err != nil {
		return err
	}

	// Persist the resolved pins (SHA/fingerprint) and per-source hashes back
	// onto the manifest entries.
	config.Templates = updatedSources

	// Scaffold a commented, inert .gtb/ignore so the opt-out mechanism is
	// discoverable in a fresh project. It is a no-op when the file already
	// exists, so it never clobbers a user's rules on regenerate.
	if err := ScaffoldIgnoreFile(g.props.FS, config.Path); err != nil {
		return err
	}

	// Merge: keep stored hashes for any files the user chose to skip so that
	// subsequent runs can still detect further modifications to those files.
	return g.writeSkeletonManifest(config, mergeHashes(storedHashes, writtenHashes))
}

// refreshProjectFileHashes re-reads the files in writtenKeys and updates
// their stored hashes in Manifest.Hashes to reflect any modifications made by
// post-processing tools (go mod tidy, golangci-lint, gofumpt).
//
// Only files present in writtenKeys are refreshed. Files where the user
// declined an overwrite are intentionally absent from writtenKeys and therefore
// retain their previously stored hash, ensuring the conflict is detected again
// on the next invocation.
func (g *Generator) refreshProjectFileHashes(projectPath string, writtenKeys map[string]string) error {
	if len(writtenKeys) == 0 {
		return nil
	}

	g.props.Logger.Debug("refreshing hashes for project files after post-processing", "files", len(writtenKeys))

	manifestPath := ManifestPathFor(projectPath)

	m, err := g.decodeManifestFile(manifestPath)
	if err != nil {
		return err
	}

	if m.Hashes == nil {
		m.Hashes = make(map[string]string)
	}

	for relPath := range writtenKeys {
		content, readErr := afero.ReadFile(g.props.FS, filepath.Join(projectPath, relPath))
		if readErr != nil {
			// File removed by post-processing; drop it from tracking.
			delete(m.Hashes, relPath)

			continue
		}

		m.Hashes[relPath] = calculateHash(content)
	}

	return g.marshalManifestFile(manifestPath, m)
}

// loadProjectFileHashes reads the existing manifest at the given path and
// returns the stored project-level file hashes, or an empty map if no
// manifest exists yet.
func (g *Generator) loadProjectFileHashes(projectPath string) map[string]string {
	manifestPath := filepath.Join(projectPath, ".gtb", "manifest.yaml")

	raw, err := afero.ReadFile(g.props.FS, manifestPath)
	if err != nil {
		return make(map[string]string)
	}

	var m Manifest
	if err := yaml.Unmarshal(raw, &m); err != nil || m.Hashes == nil {
		return make(map[string]string)
	}

	return m.Hashes
}

func (g *Generator) generateSkeletonGoFiles(destPath string, data skeletonTemplateData) error {
	goFiles := map[string]*jen.File{
		filepath.Join("cmd", data.Name, "main.go"): templates.SkeletonMain(data.ModulePath),
		"internal/version/version.go":              templates.SkeletonInternalVersion(data.ModulePath),
		"pkg/cmd/root/generate.go":                 skeletonGenerateFile(data.DisabledFeatures),
		"pkg/cmd/root/cmd.go": templates.SkeletonRoot(templates.SkeletonRootData{
			Name:                  data.Name,
			Description:           data.Description,
			ReleaseProvider:       data.ReleaseProvider,
			Host:                  data.Host,
			Org:                   data.Org,
			RepoName:              data.RepoName,
			Private:               data.Private,
			DisabledFeatures:      data.DisabledFeatures,
			EnabledFeatures:       data.EnabledFeatures,
			HelpType:              data.HelpType,
			SlackChannel:          data.SlackChannel,
			SlackTeam:             data.SlackTeam,
			TeamsChannel:          data.TeamsChannel,
			TeamsTeam:             data.TeamsTeam,
			TelemetryEndpoint:     data.TelemetryEndpoint,
			TelemetryOTelEndpoint: data.TelemetryOTelEndpoint,
			EnvPrefix:             data.EnvPrefix,
			UpdatePolicy:          data.UpdatePolicy,
			UpdateCheckInterval:   data.UpdateCheckInterval,
			SigningEnabled:        data.Signing.Enabled,
			ModulePath:            data.ModulePath,
			AutoInitialise:        data.Bootstrap.AutoInitialise,
			SkipConfigCheck:       data.Bootstrap.SkipConfigCheck,
		}),
	}

	// Signing is disabled by default. When enabled, scaffold the
	// internal/trustkeys embed package and the generated signing.go
	// enforcement defaults alongside the Signing: wiring in cmd.go.
	// The keys/.gitkeep is written separately as a raw file below.
	if data.Signing.Enabled {
		goFiles["internal/trustkeys/trustkeys.go"] = templates.SkeletonTrustKeys()
		goFiles["pkg/cmd/root/signing.go"] = templates.SkeletonSigning(templates.SkeletonSigningData{
			ExternalKeyEmail:          data.Signing.ExternalKeyEmail,
			RequireSignature:          data.Signing.RequireSignature,
			KeySource:                 data.Signing.KeySource,
			RequireExternalCrosscheck: data.Signing.RequireExternalCrosscheck,
		})
	}

	// Keychain support is default-enabled. Scaffold cmd/<name>/keychain.go
	// unless the operator explicitly opted out via --features or the
	// interactive multi-select. Deleting the scaffolded file later is
	// the escape hatch for regulated builds — linker dead-code elimination
	// then keeps go-keyring, godbus, and wincred out of the linked artefact.
	if !slices.Contains(data.DisabledFeatures, "keychain") {
		goFiles[filepath.Join("cmd", data.Name, "keychain.go")] = templates.SkeletonKeychain()
	}

	for path, f := range goFiles {
		fullPath := filepath.Join(destPath, path)

		g.props.Logger.Debug("generating Go file", "path", path)

		if err := g.props.FS.MkdirAll(filepath.Dir(fullPath), os.ModePerm); err != nil {
			return errors.Newf("failed to create directory %s: %w", filepath.Dir(fullPath), err)
		}

		out, err := g.props.FS.Create(fullPath)
		if err != nil {
			return errors.Newf("failed to create file %s: %w", fullPath, err)
		}

		if err := f.Render(out); err != nil {
			_ = out.Close()

			return errors.Newf("failed to render jennifer file %s: %w", path, err)
		}

		if err := out.Close(); err != nil {
			return errors.Newf("failed to close file %s: %w", fullPath, err)
		}

		g.props.Logger.Debug("wrote Go file", "path", fullPath)
	}

	// When signing is enabled, ensure internal/trustkeys/keys/.gitkeep
	// exists so the directory ships in git and the `all:keys` embed has a
	// file to match. Author-added *.asc keys live alongside it and are
	// never touched.
	if data.Signing.Enabled {
		if err := g.writeGitkeep(filepath.Join(destPath, "internal", "trustkeys", "keys")); err != nil {
			return err
		}
	}

	return nil
}

// writeGitkeep ensures an empty .gitkeep exists in dir, creating the
// directory if needed. It is a no-op when the file already exists so
// author-added sibling files are left untouched.
func (g *Generator) writeGitkeep(dir string) error {
	if err := g.props.FS.MkdirAll(dir, os.ModePerm); err != nil {
		return errors.Newf("failed to create directory %s: %w", dir, err)
	}

	gitkeepPath := filepath.Join(dir, ".gitkeep")

	if exists, _ := afero.Exists(g.props.FS, gitkeepPath); exists {
		return nil
	}

	if err := afero.WriteFile(g.props.FS, gitkeepPath, []byte{}, os.ModePerm); err != nil {
		return errors.Newf("failed to write %s: %w", gitkeepPath, err)
	}

	return nil
}

// generateSkeletonTemplateFilesWithSources renders the embedded skeleton
// template files and then layers the custom template overlays on top
// (D1/D6/D3). It resolves every source first so any gtb-template.yaml
// `replaces:` suppression is applied to the embedded walk before the overlay
// renders, then renders the sources in manifest order with last-writer-wins.
// It returns the collected embedded+overlay hashes and the updated source
// entries (with resolved SHA/fingerprint and per-source hashes).
func (g *Generator) generateSkeletonTemplateFilesWithSources(destPath string, data any, storedHashes map[string]string, rules *IgnoreRules, sources []TemplateSource) (map[string]string, []TemplateSource, error) {
	collectedHashes := make(map[string]string)

	// Resolve sources up-front so descriptor `replaces:` suppression is known
	// before the embedded walk runs.
	resolved, err := g.resolveAllSources(sources)
	if err != nil {
		return nil, nil, err
	}

	suppressed := collectSuppressedPrefixes(resolved)

	// On an incremental regenerate, embedded files written by a prior run may
	// already be on disk for a path a `replaces:` now suppresses. Remove those
	// stranded files (and drop them from tracking) so suppression takes effect
	// rather than leaving a now-orphaned embedded file behind (D3).
	g.removeStrandedSuppressed(destPath, suppressed, storedHashes)

	tmplFiles := map[string]string{
		"pkg/cmd/root/assets/init/config.yaml": templates.SkeletonConfig,
		"go.mod":                               templates.SkeletonGoMod,
	}

	for relPath, tmplStr := range tmplFiles {
		if rules.IsIgnored(relPath) {
			g.hashIgnoredFile(destPath, relPath, collectedHashes)

			continue
		}

		fullPath := filepath.Join(destPath, relPath)

		hash, err := g.renderAndHashSkeletonTemplate(fullPath, relPath, tmplStr, data, storedHashes)
		if err != nil {
			g.props.Logger.Warn("skipped file", "path", relPath, "error", err)

			continue
		}

		collectedHashes[relPath] = hash
	}

	// Extract the provider so we can filter CI files appropriately.
	// Uses a narrow interface to avoid brittle type assertions on anonymous
	// structs — adding fields to the data struct no longer silently breaks
	// provider detection.
	releaseProvider := extractReleaseProvider(data)

	// Walk the common skeleton assets.
	if err := g.walkSkeletonAssets(skeletonAssets, "assets/skeleton", destPath, data, storedHashes, collectedHashes, rules, suppressed); err != nil {
		return nil, nil, err
	}

	// Walk the provider-specific CI assets.
	providerFS, providerRoot := skeletonGitHubAssets, "assets/skeleton-github"
	if releaseProvider == "gitlab" {
		providerFS, providerRoot = skeletonGitLabAssets, "assets/skeleton-gitlab"
	}

	if err := g.walkSkeletonAssets(providerFS, providerRoot, destPath, data, storedHashes, collectedHashes, rules, suppressed); err != nil {
		return nil, nil, err
	}

	// Layer the custom template overlays on top of the embedded base.
	updatedSources, err := g.applyOverlays(destPath, data, storedHashes, collectedHashes, rules, sources, resolved)
	if err != nil {
		return nil, nil, err
	}

	return collectedHashes, updatedSources, nil
}

// walkSkeletonAssets walks an embedded filesystem rooted at assetRoot,
// rendering each file as a template and collecting its hash. Skipped files
// (e.g. user declined overwrite) are logged as warnings and the walk continues.
// A relPath matched by suppressed (a `replaces:` descriptor) is dropped from
// the walk entirely: it is not written and not hashed, so the overlay can
// supply the complete replacement with no stranded embedded files (D3).
func (g *Generator) walkSkeletonAssets(fsys fs.FS, assetRoot, destPath string, data any, storedHashes, collectedHashes map[string]string, rules *IgnoreRules, suppressed []string) error {
	return fs.WalkDir(fsys, assetRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}

		relPath, err := filepath.Rel(assetRoot, path)
		if err != nil {
			return errors.Newf("failed to get relative path: %w", err)
		}

		// A `replaces:` descriptor suppresses this embedded scaffold path
		// before the overlay renders — skip it entirely.
		if isSuppressed(relPath, suppressed) {
			g.props.Logger.Debug("suppressed by template replaces", "path", relPath)

			return nil
		}

		// Check ignore rules — skip generation but hash on-disk content
		if rules.IsIgnored(relPath) {
			g.props.Logger.Debug("ignored by .gtb/ignore", "path", relPath)
			g.hashIgnoredFile(destPath, relPath, collectedHashes)

			return nil
		}

		content, err := fs.ReadFile(fsys, path)
		if err != nil {
			return errors.Newf("failed to read embedded file %s: %w", path, err)
		}

		hash, err := g.renderAndHashSkeletonTemplate(filepath.Join(destPath, relPath), relPath, string(content), data, storedHashes)
		if err != nil {
			g.props.Logger.Warn("skipped file", "path", relPath, "error", err)

			return nil // non-fatal, continue walk
		}

		collectedHashes[relPath] = hash

		return nil
	})
}

// hashIgnoredFile reads the current on-disk content of an ignored file and
// records its hash. If the file doesn't exist on disk, it's skipped silently.
func (g *Generator) hashIgnoredFile(destPath, relPath string, collectedHashes map[string]string) {
	fullPath := filepath.Join(destPath, relPath)

	content, err := afero.ReadFile(g.props.FS, fullPath)
	if err != nil {
		return // file doesn't exist on disk — skip silently
	}

	collectedHashes[relPath] = calculateHash(content)
}

// renderAndHashSkeletonTemplate renders a template to disk, checking the
// stored hash first so customised files are not silently overwritten.
// It returns the SHA256 hash of the content that was written.
func (g *Generator) renderAndHashSkeletonTemplate(fullPath, relPath, tmplStr string, data any, storedHashes map[string]string) (string, error) {
	g.props.Logger.Debug("rendering skeleton template", "path", relPath)

	if err := g.props.FS.MkdirAll(filepath.Dir(fullPath), os.ModePerm); err != nil {
		return "", errors.Newf("failed to create directory %s: %w", filepath.Dir(fullPath), err)
	}

	tmpl, err := template.New(fullPath).Funcs(templateFuncMap).Parse(tmplStr)
	if err != nil {
		return "", errors.Newf("failed to parse template %s: %w", fullPath, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", errors.Newf("failed to execute template %s: %w", fullPath, err)
	}

	return g.writeRenderedSkeletonFile(fullPath, relPath, buf.Bytes(), storedHashes)
}

// renderPreRenderedSkeletonFile writes already-rendered content (e.g. a custom
// template overlay file, rendered through the restricted overlay engine) to
// disk via the same conflict-checked write path the embedded templates use, so
// a user-edited overlay output is protected identically (D8). It returns the
// written content hash.
func (g *Generator) renderPreRenderedSkeletonFile(fullPath, relPath string, content []byte, storedHashes map[string]string) (string, error) {
	if err := g.props.FS.MkdirAll(filepath.Dir(fullPath), os.ModePerm); err != nil {
		return "", errors.Newf("failed to create directory %s: %w", filepath.Dir(fullPath), err)
	}

	return g.writeRenderedSkeletonFile(fullPath, relPath, content, storedHashes)
}

// writeRenderedSkeletonFile is the shared write+conflict-check+hash tail used
// by both the embedded template render and the pre-rendered overlay write.
func (g *Generator) writeRenderedSkeletonFile(fullPath, relPath string, newContent []byte, storedHashes map[string]string) (string, error) {
	exists, _ := afero.Exists(g.props.FS, fullPath)

	// Operator-owned seed files (the init assets the operator fills in, the
	// README, the docs landing page, the justfile) are scaffolded once and then
	// belong to the developer. On a re-run they are preserved unconditionally —
	// even under --overwrite allow, which otherwise auto-approves overwriting a
	// modified file — so regenerate never destroys developer content (keryx
	// defect C). The stored hash is kept in sync with what is actually on disk.
	if exists && isUserOwnedSeedFile(relPath) {
		g.props.Logger.Debug("preserving operator-owned file (not overwritten on regenerate)", "path", relPath)

		existing, err := afero.ReadFile(g.props.FS, fullPath)
		if err != nil {
			return "", errors.Newf("failed to read existing file %s: %w", fullPath, err)
		}

		return calculateHash(existing), nil
	}

	// If the file already exists, verify the user has not customised it.
	if exists {
		g.props.Logger.Debug("checking for conflicts on existing file", "path", relPath)

		if err := g.checkSkeletonConflict(fullPath, relPath, newContent, storedHashes); err != nil {
			return "", err
		}
	}

	if err := afero.WriteFile(g.props.FS, fullPath, newContent, os.ModePerm); err != nil {
		return "", errors.Newf("failed to write file %s: %w", fullPath, err)
	}

	hash := calculateHash(newContent)

	g.props.Logger.Debug("wrote skeleton file", "path", relPath, "bytes", len(newContent), "hash", hash)

	return hash, nil
}

// joinProjectPath joins a project root and a clean slash-separated relative
// path into an OS path.
func joinProjectPath(destPath, relPath string) string {
	return filepath.Join(destPath, filepath.FromSlash(relPath))
}

// isUserOwnedSeedFile reports whether relPath (slash-separated, project-root
// relative) is a file gtb scaffolds once and then hands to the developer:
// operator-filled config and other assets under a command's assets/ directory,
// the project README, the docs landing page, and the justfile. These are
// preserved on every regenerate so developer content is never clobbered.
// Framework-structural files (CI pipelines, .goreleaser.yaml, go.mod, the
// generated DO-NOT-EDIT cmd.go) are deliberately NOT in this set — they remain
// gtb-managed and continue to update.
func isUserOwnedSeedFile(relPath string) bool {
	rel := filepath.ToSlash(relPath)

	switch rel {
	case "README.md", "docs/index.md", "justfile":
		return true
	}

	// Seeded assets the operator fills in, e.g. pkg/cmd/root/assets/init/config.yaml.
	return strings.HasPrefix(rel, "pkg/cmd/") && strings.Contains(rel, "/assets/")
}

// checkSkeletonConflict compares the on-disk file against its stored hash. If
// the file has been manually modified it prompts the user; it returns a
// non-nil error when the write should be skipped.
func (g *Generator) checkSkeletonConflict(fullPath, relPath string, newContent []byte, storedHashes map[string]string) error {
	existingContent, err := afero.ReadFile(g.props.FS, fullPath)
	if err != nil {
		return errors.Newf("failed to read existing file %s: %w", fullPath, err)
	}

	storedHash := storedHashes[relPath]
	if storedHash == "" || storedHash == calculateHash(existingContent) || g.config.Force {
		return nil
	}

	g.props.Logger.Warn("conflict detected: file has been manually modified", "path", fullPath,
		"hint", ignoreConflictHint(relPath))

	if !g.promptOverwrite(fullPath, existingContent, newContent) {
		g.props.Logger.Warn("skipping overwrite", "path", fullPath)

		return errors.Newf("overwrite skipped by user")
	}

	g.props.Logger.Warn("overwriting modified file", "path", fullPath)

	return nil
}

func (g *Generator) writeSkeletonManifest(config SkeletonConfig, fileHashes map[string]string) error {
	g.props.Logger.Debug("writing skeleton manifest", "hashes", len(fileHashes))

	org, repoName, err := splitRepoPath(config.Repo)
	if err != nil {
		return err
	}

	manifest := Manifest{
		Properties: ManifestProperties{
			Name:                config.Name,
			Description:         MultilineString(config.Description),
			Features:            normaliseManifestFeatures(config.Features),
			EnvPrefix:           config.EnvPrefix,
			UpdatePolicy:        config.UpdatePolicy,
			UpdateCheckInterval: config.UpdateCheckInterval,
			DocsLayout:          DocsLayoutDiataxis,
			Help: ManifestHelp{
				Type:         config.HelpType,
				SlackChannel: config.SlackChannel,
				SlackTeam:    config.SlackTeam,
				TeamsChannel: config.TeamsChannel,
				TeamsTeam:    config.TeamsTeam,
			},
			Signing:   config.Signing,
			Bootstrap: config.Bootstrap,
			CI: ManifestCI{
				// Persist only an explicit non-default source so the manifest
				// stays minimal; an absent ci block defaults on render.
				ComponentSource: config.CIComponentSource,
			},
			Templates: config.Templates,
		},
		ReleaseSource: ManifestReleaseSource{
			Type:    releaseProviderForHost(config.Host),
			Host:    config.Host,
			Owner:   org,
			Repo:    repoName,
			Private: config.Private,
		},
		Version: ManifestVersion{
			GoToolBase: func() string {
				if g.props.Version != nil {
					return g.props.Version.GetVersion()
				}

				return ""
			}(),
		},
		Hashes: fileHashes,
	}

	manifestDir := filepath.Join(config.Path, ".gtb")
	if err := g.props.FS.MkdirAll(manifestDir, os.ModePerm); err != nil {
		return errors.Newf("failed to create manifest directory: %w", err)
	}

	return g.marshalManifestFile(filepath.Join(manifestDir, "manifest.yaml"), &manifest)
}

func (g *Generator) runSkeletonCommand(ctx context.Context, dir, name string, args ...string) error {
	if g.runCommand != nil {
		_, err := g.runCommand(ctx, dir, name, args...)

		return err
	}

	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

// calculateDisabledFeatures returns the default-on features whose effective
// state is off — the ones the rendered SetFeatures must Disable. Derived from
// templates.FeatureCatalogue (the single source of truth), so it stays complete
// as features are added and is correct whether the manifest is delta-normalised
// or lists every feature explicitly.
func calculateDisabledFeatures(features []ManifestFeature) []string {
	disabled := []string{}

	for _, d := range templates.FeatureCatalogue {
		name := string(d.Cmd)
		if d.Default && !featureEnabledIn(features, name) {
			disabled = append(disabled, name)
		}
	}

	return disabled
}

// calculateEnabledFeatures returns the opt-in (default-off) features whose
// effective state is on — the ones the rendered SetFeatures must Enable. Derived
// from templates.FeatureCatalogue for the same reasons as calculateDisabledFeatures.
func calculateEnabledFeatures(features []ManifestFeature) []string {
	enabled := []string{}

	for _, d := range templates.FeatureCatalogue {
		name := string(d.Cmd)
		if !d.Default && featureEnabledIn(features, name) {
			enabled = append(enabled, name)
		}
	}

	return enabled
}

// normaliseManifestFeatures drops any feature entry that matches its framework
// default, so the manifest carries only the delta. This mirrors the
// enable/disable path (upsertOrClearFeature) and keeps generate's manifest in
// the same canonical form the scanner reconstructs, so a from-scratch rebuild
// reproduces it. A feature with no catalogue default (keychain) is treated as
// default-off and retained.
func normaliseManifestFeatures(features []ManifestFeature) []ManifestFeature {
	out := make([]ManifestFeature, 0, len(features))

	for _, f := range features {
		if f.Enabled != featureDefaultEnabled(f.Name) {
			out = append(out, f)
		}
	}

	return sortManifestFeatures(out)
}

// sortManifestFeatures orders feature entries by name so the manifest form is
// canonical regardless of how the entries were produced (generate's requested
// order vs the scanner's catalogue order plus keychain), making a from-scratch
// rebuild reproduce the exact bytes.
func sortManifestFeatures(features []ManifestFeature) []ManifestFeature {
	slices.SortStableFunc(features, func(a, b ManifestFeature) int {
		return strings.Compare(a.Name, b.Name)
	})

	return features
}
