package generator

import (
	"context"
	"testing"

	"github.com/spf13/afero"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestSyncAdapterFiles_KeychainFollowsTheManifest pins spec 0197 D8: the
// keychain import is a synced adapter file like chat.go, written while the
// feature is enabled and removed when it is not. Deleting it by hand lasts
// until the next sync; `disable keychain` is the durable way.
func TestSyncAdapterFiles_KeychainFollowsTheManifest(t *testing.T) {
	t.Parallel()

	g, fs := newPureGenerator(t, &Config{Path: "/proj"})

	// The manifest records keychain as an explicit entry when selected
	// (it has no catalogue default), so absence means off.
	enabled := &Manifest{Properties: ManifestProperties{Name: "tool",
		Features: []ManifestFeature{{Name: KeychainFeature, Enabled: true}}}}
	require.NoError(t, g.syncAdapterFiles(enabled))

	src, err := afero.ReadFile(fs, "/proj/cmd/tool/keychain.go")
	require.NoError(t, err, "the file is written while the feature is enabled")
	assert.Contains(t, string(src), "pkg/setup/keychain")

	disabled := &Manifest{Properties: ManifestProperties{Name: "tool"}}
	require.NoError(t, g.syncAdapterFiles(disabled))

	exists, _ := afero.Exists(fs, "/proj/cmd/tool/keychain.go")
	assert.False(t, exists, "disabling the feature removes the file")

	require.NoError(t, g.syncAdapterFiles(enabled))
	exists, _ = afero.Exists(fs, "/proj/cmd/tool/keychain.go")
	assert.True(t, exists, "a hand-deleted file comes back while the feature is enabled")
}

// TestSyncAdapterFiles_MCPFollowsTheManifest: the mcp link defaults on, so a
// manifest that says nothing writes cmd/<name>/mcp.go, an explicit mcp: false
// removes it, and the same sync brings a deleted file back (spec 0202 D3, D6).
func TestSyncAdapterFiles_MCPFollowsTheManifest(t *testing.T) {
	t.Parallel()

	g, fs := newPureGenerator(t, &Config{Path: "/proj"})

	silent := &Manifest{Properties: ManifestProperties{Name: "tool"}}
	require.NoError(t, g.syncAdapterFiles(silent))

	src, err := afero.ReadFile(fs, "/proj/cmd/tool/mcp.go")
	require.NoError(t, err, "a manifest that says nothing about mcp links it")
	assert.Contains(t, string(src), `_ "gitlab.com/phpboyscout/go-tool-base/pkg/mcp"`)

	disabled := &Manifest{Properties: ManifestProperties{Name: "tool",
		Features: []ManifestFeature{{Name: "mcp", Enabled: false}}}}
	require.NoError(t, g.syncAdapterFiles(disabled))

	exists, _ := afero.Exists(fs, "/proj/cmd/tool/mcp.go")
	assert.False(t, exists, "mcp: false removes the link")

	require.NoError(t, g.syncAdapterFiles(silent))
	exists, _ = afero.Exists(fs, "/proj/cmd/tool/mcp.go")
	assert.True(t, exists, "the link comes back with the manifest")
}

// TestSyncDerivedFromManifest_RewritesTheFrameworkOwnedGoFiles pins #84:
// the entry point, the version package and the generate directives are
// generated files with no hash, so every writer of the manifest brings them
// to the current skeleton, as it does the root. A rule in .gtb/ignore still
// outranks the write.
func TestSyncDerivedFromManifest_RewritesTheFrameworkOwnedGoFiles(t *testing.T) {
	t.Parallel()

	manifest := "properties:\n  name: mytool\n  features:\n    - name: changelog\n      enabled: false\nversion:\n  gtb: v1.0.0\ncommands: []\n"

	t.Run("brings the three files to the current skeleton", func(t *testing.T) {
		t.Parallel()

		g, fs, _ := newPerimeterTestProject(t, manifest)
		stale := "// Code generated by gtb. DO NOT EDIT.\n\npackage main\n\nfunc main() {\n\trootCmd, p := root.NewCmdRoot(version.Get())\n\tgtbRoot.Execute(rootCmd, p)\n}\n"
		require.NoError(t, afero.WriteFile(fs, "/work/cmd/mytool/main.go", []byte(stale), 0o644))
		require.NoError(t, afero.WriteFile(fs, "/work/pkg/cmd/root/generate.go", []byte("package root\n\n//go:generate go tool changelog generate --output assets/CHANGELOG.md\n"), 0o644))

		m, err := g.loadManifest()
		require.NoError(t, err)
		require.NoError(t, g.syncDerivedFromManifest(m))

		mainGo, err := afero.ReadFile(fs, "/work/cmd/mytool/main.go")
		require.NoError(t, err)
		assert.Contains(t, string(mainGo), "rootCmd, p, err := root.NewCmdRoot(version.Get())", "the entry point is the current skeleton's")
		assert.Contains(t, string(mainGo), "errorhandling.ExitCodeUsage")
		assert.Contains(t, string(mainGo), `"test-mod/pkg/cmd/root"`, "imports follow go.mod's module path")
		assert.NotContains(t, string(mainGo), "rootCmd, p := root.NewCmdRoot")

		versionGo, err := afero.ReadFile(fs, "/work/internal/version/version.go")
		require.NoError(t, err, "a missing version package comes back")
		assert.Contains(t, string(versionGo), "package version")

		generateGo, err := afero.ReadFile(fs, "/work/pkg/cmd/root/generate.go")
		require.NoError(t, err)
		assert.NotContains(t, string(generateGo), "go tool changelog", "the directive follows the manifest: changelog is off")
		assert.Contains(t, string(generateGo), "go tool docs", "docs is on, so its embed directive is written")
	})

	t.Run("a rule leaves the file alone", func(t *testing.T) {
		t.Parallel()

		g, fs, _ := newPerimeterTestProject(t, manifest)
		require.NoError(t, afero.WriteFile(fs, "/work/.gtb/ignore", []byte("cmd/mytool/main.go\n"), 0o644))
		require.NoError(t, afero.WriteFile(fs, "/work/cmd/mytool/main.go", []byte("package main\n// mine\n"), 0o644))

		m, err := g.loadManifest()
		require.NoError(t, err)
		require.NoError(t, g.syncDerivedFromManifest(m))

		mainGo, err := afero.ReadFile(fs, "/work/cmd/mytool/main.go")
		require.NoError(t, err)
		assert.Equal(t, "package main\n// mine\n", string(mainGo))

		exists, _ := afero.Exists(fs, "/work/internal/version/version.go")
		assert.True(t, exists, "the rule covers one file, not the set")
	})
}

// TestApplyFeatures_LeavesTheTreeInLine pins spec 0197 D7: enable ai alone
// records the default providers and writes chat.go with their modules; no
// regenerate is needed afterwards. It used to re-render the root and stop.
func TestApplyFeatures_LeavesTheTreeInLine(t *testing.T) {
	t.Parallel()

	manifest := "properties:\n  name: mytool\n  features: []\nversion:\n  gtb: v1.0.0\ncommands: []\n"
	g, fs, _ := newPerimeterTestProject(t, manifest)

	changed, err := g.ApplyFeatures(context.Background(), map[string]bool{"ai": true})
	require.NoError(t, err)
	assert.Equal(t, []string{"ai"}, changed)

	chatGo, err := afero.ReadFile(fs, "/work/cmd/mytool/chat.go")
	require.NoError(t, err, "the adapter file is written by the same command")
	assert.Contains(t, string(chatGo), "chat-anthropic")

	m, err := g.loadManifest()
	require.NoError(t, err)
	assert.Equal(t, DefaultChatProviders(), m.Properties.Chat.Providers, "the derived provider list is recorded")
	assert.True(t, featureEnabledIn(m.Properties.Features, "ai"))
}
