// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vcs

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenConfig creates a new instance of MockTokenConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenConfig {
	mock := &MockTokenConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenConfig is an autogenerated mock type for the TokenConfig type
type MockTokenConfig struct {
	mock.Mock
}

type MockTokenConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenConfig) EXPECT() *MockTokenConfig_Expecter {
	return &MockTokenConfig_Expecter{mock: &_m.Mock}
}

// GetString provides a mock function for the type MockTokenConfig
func (_mock *MockTokenConfig) GetString(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenConfig_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockTokenConfig_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *MockTokenConfig_Expecter) GetString(key interface{}) *MockTokenConfig_GetString_Call {
	return &MockTokenConfig_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *MockTokenConfig_GetString_Call) Run(run func(key string)) *MockTokenConfig_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenConfig_GetString_Call) Return(s string) *MockTokenConfig_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenConfig_GetString_Call) RunAndReturn(run func(key string) string) *MockTokenConfig_GetString_Call {
	_c.Call.Return(run)
	return _c
}
