// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockConfigReader creates a new instance of MockConfigReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigReader {
	mock := &MockConfigReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigReader is an autogenerated mock type for the ConfigReader type
type MockConfigReader struct {
	mock.Mock
}

type MockConfigReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigReader) EXPECT() *MockConfigReader_Expecter {
	return &MockConfigReader_Expecter{mock: &_m.Mock}
}

// GetConfigView provides a mock function for the type MockConfigReader
func (_mock *MockConfigReader) GetConfigView() *config.View {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigView")
	}

	var r0 *config.View
	if returnFunc, ok := ret.Get(0).(func() *config.View); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.View)
		}
	}
	return r0
}

// MockConfigReader_GetConfigView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigView'
type MockConfigReader_GetConfigView_Call struct {
	*mock.Call
}

// GetConfigView is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetConfigView() *MockConfigReader_GetConfigView_Call {
	return &MockConfigReader_GetConfigView_Call{Call: _e.mock.On("GetConfigView")}
}

func (_c *MockConfigReader_GetConfigView_Call) Run(run func()) *MockConfigReader_GetConfigView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetConfigView_Call) Return(view *config.View) *MockConfigReader_GetConfigView_Call {
	_c.Call.Return(view)
	return _c
}

func (_c *MockConfigReader_GetConfigView_Call) RunAndReturn(run func() *config.View) *MockConfigReader_GetConfigView_Call {
	_c.Call.Return(run)
	return _c
}
