// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockConfigFSProvider creates a new instance of MockConfigFSProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigFSProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigFSProvider {
	mock := &MockConfigFSProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigFSProvider is an autogenerated mock type for the ConfigFSProvider type
type MockConfigFSProvider struct {
	mock.Mock
}

type MockConfigFSProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigFSProvider) EXPECT() *MockConfigFSProvider_Expecter {
	return &MockConfigFSProvider_Expecter{mock: &_m.Mock}
}

// GetConfigFS provides a mock function for the type MockConfigFSProvider
func (_mock *MockConfigFSProvider) GetConfigFS() config.FS {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigFS")
	}

	var r0 config.FS
	if returnFunc, ok := ret.Get(0).(func() config.FS); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.FS)
		}
	}
	return r0
}

// MockConfigFSProvider_GetConfigFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigFS'
type MockConfigFSProvider_GetConfigFS_Call struct {
	*mock.Call
}

// GetConfigFS is a helper method to define mock.On call
func (_e *MockConfigFSProvider_Expecter) GetConfigFS() *MockConfigFSProvider_GetConfigFS_Call {
	return &MockConfigFSProvider_GetConfigFS_Call{Call: _e.mock.On("GetConfigFS")}
}

func (_c *MockConfigFSProvider_GetConfigFS_Call) Run(run func()) *MockConfigFSProvider_GetConfigFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigFSProvider_GetConfigFS_Call) Return(fS config.FS) *MockConfigFSProvider_GetConfigFS_Call {
	_c.Call.Return(fS)
	return _c
}

func (_c *MockConfigFSProvider_GetConfigFS_Call) RunAndReturn(run func() config.FS) *MockConfigFSProvider_GetConfigFS_Call {
	_c.Call.Return(run)
	return _c
}
