// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileSystemProvider creates a new instance of MockFileSystemProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystemProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystemProvider {
	mock := &MockFileSystemProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileSystemProvider is an autogenerated mock type for the FileSystemProvider type
type MockFileSystemProvider struct {
	mock.Mock
}

type MockFileSystemProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystemProvider) EXPECT() *MockFileSystemProvider_Expecter {
	return &MockFileSystemProvider_Expecter{mock: &_m.Mock}
}

// GetFS provides a mock function for the type MockFileSystemProvider
func (_mock *MockFileSystemProvider) GetFS() afero.Fs {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFS")
	}

	var r0 afero.Fs
	if returnFunc, ok := ret.Get(0).(func() afero.Fs); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}
	return r0
}

// MockFileSystemProvider_GetFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFS'
type MockFileSystemProvider_GetFS_Call struct {
	*mock.Call
}

// GetFS is a helper method to define mock.On call
func (_e *MockFileSystemProvider_Expecter) GetFS() *MockFileSystemProvider_GetFS_Call {
	return &MockFileSystemProvider_GetFS_Call{Call: _e.mock.On("GetFS")}
}

func (_c *MockFileSystemProvider_GetFS_Call) Run(run func()) *MockFileSystemProvider_GetFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileSystemProvider_GetFS_Call) Return(fs afero.Fs) *MockFileSystemProvider_GetFS_Call {
	_c.Call.Return(fs)
	return _c
}

func (_c *MockFileSystemProvider_GetFS_Call) RunAndReturn(run func() afero.Fs) *MockFileSystemProvider_GetFS_Call {
	_c.Call.Return(run)
	return _c
}
