// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go-tool-base/pkg/props"
)

// NewMockTelemetryProvider creates a new instance of MockTelemetryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryProvider {
	mock := &MockTelemetryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelemetryProvider is an autogenerated mock type for the TelemetryProvider type
type MockTelemetryProvider struct {
	mock.Mock
}

type MockTelemetryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryProvider) EXPECT() *MockTelemetryProvider_Expecter {
	return &MockTelemetryProvider_Expecter{mock: &_m.Mock}
}

// GetCollector provides a mock function for the type MockTelemetryProvider
func (_mock *MockTelemetryProvider) GetCollector() props.TelemetryCollector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCollector")
	}

	var r0 props.TelemetryCollector
	if returnFunc, ok := ret.Get(0).(func() props.TelemetryCollector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(props.TelemetryCollector)
		}
	}
	return r0
}

// MockTelemetryProvider_GetCollector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollector'
type MockTelemetryProvider_GetCollector_Call struct {
	*mock.Call
}

// GetCollector is a helper method to define mock.On call
func (_e *MockTelemetryProvider_Expecter) GetCollector() *MockTelemetryProvider_GetCollector_Call {
	return &MockTelemetryProvider_GetCollector_Call{Call: _e.mock.On("GetCollector")}
}

func (_c *MockTelemetryProvider_GetCollector_Call) Run(run func()) *MockTelemetryProvider_GetCollector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelemetryProvider_GetCollector_Call) Return(telemetryCollector props.TelemetryCollector) *MockTelemetryProvider_GetCollector_Call {
	_c.Call.Return(telemetryCollector)
	return _c
}

func (_c *MockTelemetryProvider_GetCollector_Call) RunAndReturn(run func() props.TelemetryCollector) *MockTelemetryProvider_GetCollector_Call {
	_c.Call.Return(run)
	return _c
}
