// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/props"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelemetryCollector creates a new instance of MockTelemetryCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryCollector {
	mock := &MockTelemetryCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelemetryCollector is an autogenerated mock type for the TelemetryCollector type
type MockTelemetryCollector struct {
	mock.Mock
}

type MockTelemetryCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryCollector) EXPECT() *MockTelemetryCollector_Expecter {
	return &MockTelemetryCollector_Expecter{mock: &_m.Mock}
}

// BackendInfo provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) BackendInfo() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BackendInfo")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTelemetryCollector_BackendInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackendInfo'
type MockTelemetryCollector_BackendInfo_Call struct {
	*mock.Call
}

// BackendInfo is a helper method to define mock.On call
func (_e *MockTelemetryCollector_Expecter) BackendInfo() *MockTelemetryCollector_BackendInfo_Call {
	return &MockTelemetryCollector_BackendInfo_Call{Call: _e.mock.On("BackendInfo")}
}

func (_c *MockTelemetryCollector_BackendInfo_Call) Run(run func()) *MockTelemetryCollector_BackendInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelemetryCollector_BackendInfo_Call) Return(s string) *MockTelemetryCollector_BackendInfo_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTelemetryCollector_BackendInfo_Call) RunAndReturn(run func() string) *MockTelemetryCollector_BackendInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelemetryCollector_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTelemetryCollector_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTelemetryCollector_Expecter) Close(ctx interface{}) *MockTelemetryCollector_Close_Call {
	return &MockTelemetryCollector_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockTelemetryCollector_Close_Call) Run(run func(ctx context.Context)) *MockTelemetryCollector_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelemetryCollector_Close_Call) Return(err error) *MockTelemetryCollector_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelemetryCollector_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockTelemetryCollector_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Drop provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) Drop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Drop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelemetryCollector_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockTelemetryCollector_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
func (_e *MockTelemetryCollector_Expecter) Drop() *MockTelemetryCollector_Drop_Call {
	return &MockTelemetryCollector_Drop_Call{Call: _e.mock.On("Drop")}
}

func (_c *MockTelemetryCollector_Drop_Call) Run(run func()) *MockTelemetryCollector_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelemetryCollector_Drop_Call) Return(err error) *MockTelemetryCollector_Drop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelemetryCollector_Drop_Call) RunAndReturn(run func() error) *MockTelemetryCollector_Drop_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) Flush(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelemetryCollector_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockTelemetryCollector_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTelemetryCollector_Expecter) Flush(ctx interface{}) *MockTelemetryCollector_Flush_Call {
	return &MockTelemetryCollector_Flush_Call{Call: _e.mock.On("Flush", ctx)}
}

func (_c *MockTelemetryCollector_Flush_Call) Run(run func(ctx context.Context)) *MockTelemetryCollector_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelemetryCollector_Flush_Call) Return(err error) *MockTelemetryCollector_Flush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelemetryCollector_Flush_Call) RunAndReturn(run func(ctx context.Context) error) *MockTelemetryCollector_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) Track(eventType props.EventType, name string, extra map[string]string) {
	_mock.Called(eventType, name, extra)
	return
}

// MockTelemetryCollector_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockTelemetryCollector_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - eventType props.EventType
//   - name string
//   - extra map[string]string
func (_e *MockTelemetryCollector_Expecter) Track(eventType interface{}, name interface{}, extra interface{}) *MockTelemetryCollector_Track_Call {
	return &MockTelemetryCollector_Track_Call{Call: _e.mock.On("Track", eventType, name, extra)}
}

func (_c *MockTelemetryCollector_Track_Call) Run(run func(eventType props.EventType, name string, extra map[string]string)) *MockTelemetryCollector_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 props.EventType
		if args[0] != nil {
			arg0 = args[0].(props.EventType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTelemetryCollector_Track_Call) Return() *MockTelemetryCollector_Track_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryCollector_Track_Call) RunAndReturn(run func(eventType props.EventType, name string, extra map[string]string)) *MockTelemetryCollector_Track_Call {
	_c.Run(run)
	return _c
}

// TrackCommand provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) TrackCommand(name string, durationMs int64, exitCode int, extra map[string]string) {
	_mock.Called(name, durationMs, exitCode, extra)
	return
}

// MockTelemetryCollector_TrackCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackCommand'
type MockTelemetryCollector_TrackCommand_Call struct {
	*mock.Call
}

// TrackCommand is a helper method to define mock.On call
//   - name string
//   - durationMs int64
//   - exitCode int
//   - extra map[string]string
func (_e *MockTelemetryCollector_Expecter) TrackCommand(name interface{}, durationMs interface{}, exitCode interface{}, extra interface{}) *MockTelemetryCollector_TrackCommand_Call {
	return &MockTelemetryCollector_TrackCommand_Call{Call: _e.mock.On("TrackCommand", name, durationMs, exitCode, extra)}
}

func (_c *MockTelemetryCollector_TrackCommand_Call) Run(run func(name string, durationMs int64, exitCode int, extra map[string]string)) *MockTelemetryCollector_TrackCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTelemetryCollector_TrackCommand_Call) Return() *MockTelemetryCollector_TrackCommand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryCollector_TrackCommand_Call) RunAndReturn(run func(name string, durationMs int64, exitCode int, extra map[string]string)) *MockTelemetryCollector_TrackCommand_Call {
	_c.Run(run)
	return _c
}

// TrackCommandExtended provides a mock function for the type MockTelemetryCollector
func (_mock *MockTelemetryCollector) TrackCommandExtended(name string, args []string, durationMs int64, exitCode int, errMsg string, extra map[string]string) {
	_mock.Called(name, args, durationMs, exitCode, errMsg, extra)
	return
}

// MockTelemetryCollector_TrackCommandExtended_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackCommandExtended'
type MockTelemetryCollector_TrackCommandExtended_Call struct {
	*mock.Call
}

// TrackCommandExtended is a helper method to define mock.On call
//   - name string
//   - args []string
//   - durationMs int64
//   - exitCode int
//   - errMsg string
//   - extra map[string]string
func (_e *MockTelemetryCollector_Expecter) TrackCommandExtended(name interface{}, args interface{}, durationMs interface{}, exitCode interface{}, errMsg interface{}, extra interface{}) *MockTelemetryCollector_TrackCommandExtended_Call {
	return &MockTelemetryCollector_TrackCommandExtended_Call{Call: _e.mock.On("TrackCommandExtended", name, args, durationMs, exitCode, errMsg, extra)}
}

func (_c *MockTelemetryCollector_TrackCommandExtended_Call) Run(run func(name string, args []string, durationMs int64, exitCode int, errMsg string, extra map[string]string)) *MockTelemetryCollector_TrackCommandExtended_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 map[string]string
		if args[5] != nil {
			arg5 = args[5].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockTelemetryCollector_TrackCommandExtended_Call) Return() *MockTelemetryCollector_TrackCommandExtended_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryCollector_TrackCommandExtended_Call) RunAndReturn(run func(name string, args []string, durationMs int64, exitCode int, errMsg string, extra map[string]string)) *MockTelemetryCollector_TrackCommandExtended_Call {
	_c.Run(run)
	return _c
}
